#!/usr/bin/env python3
"""Generate and validate the review-only G4-A R2 Batch 3 input packet."""

from __future__ import annotations

import csv
import io
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
BASE = "11b2de229f7b1c51065abc3ec338fbf3d41df702"
INVENTORY = "docs/G4A_R2_PROPOSAL_GAP_INVENTORY.csv"
SUPPLEMENTAL = "docs/G4A_R2_SUPPLEMENTAL_PROPOSALS.csv"
PACKET = ROOT / "docs/batches/G4A_R2_PROPOSAL_BATCH3_INPUT.csv"
IDS = (
    "SB-1270", "SB-1275", "SB-1335", "SB-1495", "SB-1523", "SB-1570",
    "SB-1585", "SB-1590", "SB-1630", "SB-1668", "SB-1747",
)
FROZEN_FIELDS = (
    "word", "pos", "ua", "definitionUa", "category", "existing_rationale",
    "proposal_state",
)
COLUMNS = ("id", "batch", *FROZEN_FIELDS)
FROZEN_PATHS = (
    INVENTORY,
    "docs/G4A_R2_PROPOSAL_REVIEW_LOG.md",
    SUPPLEMENTAL,
    "docs/G4A_R2_RECON_CHUNK1.csv",
    "docs/G4A_R2_RECON_CHUNK2.csv",
    "docs/G4A_R2_RECON_CHUNK3.csv",
    "docs/G4A_R2_RECON_ROSTER.csv",
    "docs/G4A_R2_RECON_SUMMARY.md",
    "web/vocabulary.js",
)


def read_csv(payload: bytes, label: str) -> tuple[list[str], list[dict[str, str]]]:
    text = payload.decode("utf-8")
    reader = csv.DictReader(io.StringIO(text, newline=""))
    columns = reader.fieldnames
    if columns is None or len(columns) != len(set(columns)):
        raise ValueError(f"{label}: missing or duplicate CSV header")
    rows = list(reader)
    if any(None in row or any(value is None for value in row.values()) for row in rows):
        raise ValueError(f"{label}: malformed CSV row")
    return columns, rows


def check_frozen() -> None:
    for path in FROZEN_PATHS:
        original = subprocess.run(
            ["git", "show", f"{BASE}:{path}"], cwd=ROOT,
            capture_output=True, check=True,
        ).stdout
        if (ROOT / path).read_bytes() != original:
            raise ValueError(f"{path}: differs from the exact execution base")


def expected_packet() -> bytes:
    columns, rows = read_csv((ROOT / INVENTORY).read_bytes(), INVENTORY)
    if not set(("id", *FROZEN_FIELDS)).issubset(columns):
        raise ValueError(f"{INVENTORY}: required frozen field missing")
    selected: dict[str, dict[str, str]] = {}
    for row in rows:
        if row["id"] in IDS:
            if row["id"] in selected:
                raise ValueError(f"{INVENTORY}: duplicate {row['id']}")
            selected[row["id"]] = row
    if set(selected) != set(IDS):
        raise ValueError(f"{INVENTORY}: missing expected IDs {sorted(set(IDS) - set(selected))}")

    output = io.StringIO(newline="")
    writer = csv.DictWriter(output, fieldnames=COLUMNS, lineterminator="\n")
    writer.writeheader()
    for sid in IDS:
        writer.writerow({"id": sid, "batch": "3", **{
            field: selected[sid][field] for field in FROZEN_FIELDS
        }})
    return output.getvalue().encode("utf-8")


def validate_packet(expected: bytes) -> None:
    actual = PACKET.read_bytes()
    if b"\r" in actual or not actual.endswith(b"\n"):
        raise ValueError("packet must use LF line endings")
    columns, rows = read_csv(actual, str(PACKET.relative_to(ROOT)))
    if tuple(columns) != COLUMNS:
        raise ValueError("packet header differs from the required columns or contains proposal fields")
    ids = [row["id"] for row in rows]
    if len(rows) != 11 or len(set(ids)) != 11 or ids != list(IDS):
        raise ValueError("packet must contain exactly the 11 expected IDs once, in order")
    if any(row["batch"] != "3" for row in rows):
        raise ValueError("packet batch must be 3 on every row")
    if actual != expected:
        raise ValueError("packet frozen fields differ from inventory or regenerated bytes differ")


def validate_supplemental() -> None:
    _, rows = read_csv((ROOT / SUPPLEMENTAL).read_bytes(), SUPPLEMENTAL)
    ids = [row["id"] for row in rows]
    if len(rows) != 20 or len(set(ids)) != 20:
        raise ValueError("supplemental proposals must retain 20 unique accepted rows")
    _, gaps = read_csv((ROOT / INVENTORY).read_bytes(), INVENTORY)
    if set(ids) != {row["id"] for row in gaps} - set(IDS):
        raise ValueError("supplemental proposals must cover only Batches 1 and 2")


def main() -> int:
    try:
        check_frozen()
        validate_supplemental()
        expected = expected_packet()
        if sys.argv[1:] == ["--write"]:
            PACKET.parent.mkdir(parents=True, exist_ok=True)
            PACKET.write_bytes(expected)
        elif sys.argv[1:]:
            raise ValueError("usage: g4a_r2_batch3_packet.py [--write]")
        validate_packet(expected)
    except (OSError, ValueError, UnicodeError, subprocess.CalledProcessError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    print("PASS: Batch 3 packet has 11 frozen rows, LF bytes, and no proposal fields")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
