# -*- coding: utf-8 -*-
"""R2 A/B reconciliation — chunk 1 final verdicts (evidence-first).

J[id] = {fd, conf, ev (exact ua/def substring), why}. Defect category/target/
value default to Pass A's reviewed proposal in the builder. Final disposition
equals Pass A's where the frozen Ukrainian text confirms the defect (it does on
inspection — Pass B's clean calls here were too lenient), with two evidence-
based severity divergences toward Pass B: SB-1771 and SB-1521.
"""

JUDGMENTS = {
 "SB-0152": {"fd":"P1","conf":"medium","ev":"випадковий знайомий","why":"buddy is a pal/close informal friend; «випадковий знайомий» (a chance acquaintance) mis-teaches the relationship as distant, so Pass A's defect stands over Pass B's clean call."},
 "SB-0806": {"fd":"P2","conf":"medium","ev":"Організація або діяльність","why":"non-profit is an adjective, but the definition opens by naming «Організація або діяльність»; the sense is recoverable, so a minor POS-framing defect (Pass A), not clean (Pass B)."},
 "SB-1374": {"fd":"P1","conf":"high","ev":"напрямок","why":"the trailing «напрямок» renders English 'direction' as bearing/heading, a false sense of administration; Pass A's semantic defect is confirmed against the frozen text."},
 "SB-1075": {"fd":"P2","conf":"medium","ev":"Знаходиться","why":"«Знаходиться» is a Russian-influenced locative where standard Ukrainian prefers «розташований»; understandable but a real stylistic calque (Pass A P2)."},
 "SB-0063": {"fd":"P1","conf":"medium","ev":"до Конституції","why":"amendment is defined only «до Конституції», misinforming a learner that it is constitution-specific and omitting laws/agreements/documents; Pass A's over-narrowing defect holds."},
 "SB-0917": {"fd":"P1","conf":"high","ev":"проблеми(-й):","why":"the definition is malformed («Постановка проблеми; мати або страждати…») and ends on a dangling colon «проблеми(-й):»; broken learner-facing syntax, so P1 (Pass A) over Pass B's P2."},
 "SB-1768": {"fd":"P2","conf":"high","ev":"сформований у свідомості","why":"content is correct; the definition merely starts lowercase and lacks terminal punctuation — a cosmetic P2 (Pass A)."},
 "SB-0761": {"fd":"P1","conf":"medium","ev":"бере на себе сторона-покупець","why":"«активи та зобов’язання … бере на себе сторона-покупець» miscoordinates number/agent and garbles which party assumes what; Pass A's syntax defect is confirmed."},
 "SB-1162": {"fd":"P2","conf":"medium","ev":"Як питання припущення","why":"«Як питання припущення» is a stiff literal calque of 'as a matter of supposition'; conveys the sense but is unidiomatic (Pass A P2)."},
 "SB-1521": {"fd":"P2","conf":"medium","ev":"однаково віддалені один від одного","why":"DIVERGENCE from Pass A (P1): «У всіх точках однаково віддалені один від одного» is a valid, if telegraphic, description of parallelism — «віддалені» agrees with the implied points/lines, not the headword — so this is minor style (P2), not a material grammar defect."},
 "SB-1141": {"fd":"P2","conf":"medium","ev":"Великі за розміром","why":"«Великі» is plural where the singular adjective істотний is being defined — a real agreement slip, but the meaning is clear, so P2 (Pass A graded P1; the error is a minor inflection)."},
 "SB-1241": {"fd":"P2","conf":"medium","ev":"Тривожний","why":"leading «Тривожний» can mean anxiety-causing, whereas troubled = worried/burdened; a mild sense drift with the correct gloss present, so P2 (Pass A)."},
 "SB-1457": {"fd":"P1","conf":"medium","ev":"посилання","why":"the gloss «посилання» reads as hyperlink/reference in contemporary Ukrainian, inconsistent with the general-connection definition; Pass A's ua↔definition mismatch is confirmed."},
 "SB-0748": {"fd":"P1","conf":"medium","ev":"тим часом","why":"the noun meantime is glossed with the adverbial «тим часом» ('meanwhile'), a POS mismatch that mistrains usage; Pass A's defect holds over Pass B's clean."},
 "SB-1424": {"fd":"P2","conf":"medium","ev":"План дій","why":"plural strategies is defined by the singular «План дій» — a number mismatch, minor and comprehensible, so P2 (Pass A graded P1)."},
 "SB-1166": {"fd":"P2","conf":"medium","ev":"Відносно, використовується","why":"«Відносно,» is a Russian-influenced opener and the following verb forms fit awkwardly; understandable, so P2 (Pass A graded P1)."},
 "SB-0088": {"fd":"P1","conf":"high","ev":"Нападати","why":"assault is tagged n.,v. but ua «напад» is noun-only while the definition «Нападати… атакувати» is verb-only — an internal POS mismatch; Pass A's coverage defect is confirmed."},
 "SB-0906": {"fd":"P2","conf":"medium","ev":"Високого престижу","why":"«Високого престижу» is a fragment that circularly repeats the headword; thin but not misleading, so P2 (Pass A)."},
 "SB-0126": {"fd":"P2","conf":"medium","ev":"отримує перевагу","why":"«користується або отримує перевагу» is vaguer than 'receives a benefit/entitlement'; a mild pedagogical imprecision (Pass A P2)."},
 "SB-0196": {"fd":"P2","conf":"medium","ev":"для певної переваги","why":"«для певної переваги» understates the shared-purpose nature of a coalition; comprehensible, so a minor pedagogical P2 (Pass A)."},
 "SB-1085": {"fd":"P2","conf":"medium","ev":"Насичуватися рідиною","why":"ua «замочити» is transitive/perfective but the definition «Насичуватися рідиною» is reflexive/intransitive, covering one construction; a real voice mismatch, minor, P2 (Pass A graded P1)."},
 "SB-1462": {"fd":"P2","conf":"medium","ev":"Те, що виробляється","why":"plural outcomes is defined by singular «Те, що виробляється»; a number mismatch, minor, P2 (Pass A graded P1)."},
 "SB-0485": {"fd":"P2","conf":"medium","ev":"засноване","why":"«Відносно» calque plus neuter «засноване» not agreeing with the masculine adjective; understandable, so P2 (Pass A graded P1)."},
 "SB-0472": {"fd":"P2","conf":"medium","ev":"описувати більше, ніж факт","why":"the definition is near-circular and «описувати більше, ніж факт» is unidiomatic; conveys exaggerate, so P2 (Pass A)."},
 "SB-0162": {"fd":"P2","conf":"medium","ev":"генерувати результат","why":"«генерувати результат» is an avoidable technical calque in a general learner definition; minor, P2 (Pass A)."},
 "SB-1709": {"fd":"P2","conf":"medium","ev":"Був або містить підкріплення","why":"«Був або містить» mixes past and present and is terse; conveys reinforced, so P2 (Pass A graded P1)."},
 "SB-0129": {"fd":"P2","conf":"medium","ev":"особливо опублікованої","why":"«особливо опублікованої» grammatically attaches to the person rather than the life-account; a mild misparse, comprehensible, P2 (Pass A graded P1)."},
 "SB-0581": {"fd":"P1","conf":"high","ev":"Мати на увазі без прямого твердження","why":"hint is n.,v. but ua «підказка» is noun-only while the definition is verb-framed and breaks its own pattern — a POS coverage/consistency defect (Pass A) confirmed."},
 "SB-1633": {"fd":"P2","conf":"medium","ev":"пов'язаної з нею","why":"«З хімії або пов’язаної з нею» is a feminine-agreeing fragment for the masculine adjective; understandable, so P2 (Pass A graded P1)."},
 "SB-1058": {"fd":"P2","conf":"medium","ev":"Маючи відношення","why":"«Маючи відношення» is Russian-influenced and «розташовані» disagrees with the adjective; comprehensible, so P2 (Pass A graded P1)."},
 "SB-0438": {"fd":"P2","conf":"medium","ev":"на відміну від теорії","why":"neuter «засноване» does not agree with the masculine adjective; a minor agreement slip, P2 (Pass A)."},
 "SB-1065": {"fd":"P1","conf":"medium","ev":"прямо; повний; чистий","why":"«прямо; повний; чистий» mixes adverb/adjective forms and the gloss «чистий» misses sheer's core 'utter/complete' and 'steep' senses; Pass A's POS/sense defect holds."},
 "SB-1394": {"fd":"P2","conf":"medium","ev":"короткий опис конкретної ситуації","why":"folding «короткий опис конкретної ситуації» into evaluation blurs unlike senses; the core appraisal sense is right, so P2 (Pass A graded P1)."},
 "SB-1530": {"fd":"P2","conf":"medium","ev":"вашому зберіганні","why":"ua impersonal «зберігається» plus second-person «вашому» misalign with the participle retained; comprehensible, so P2 (Pass A graded P1)."},
 "SB-1715": {"fd":"P2","conf":"medium","ev":"художнього твору; тема","why":"the definition repeats «тема» and adds little distinction; thin, P2 (Pass A)."},
 "SB-0981": {"fd":"P2","conf":"high","ev":"Процес реабілітації","why":"«Процес реабілітації когось або чогось» is fully circular on the cognate; not misleading, so P2 (Pass A)."},
 "SB-1352": {"fd":"P1","conf":"high","ev":"з наступним додаванням, до або для мети процесу","why":"the parenthetical «з наступним додаванням, до або для мети процесу» is unintelligible learner-facing text; Pass A's broken-syntax defect is confirmed."},
 "SB-0754": {"fd":"P2","conf":"medium","ev":"яким хтось або щось згадується","why":"«яким хтось або щось згадується» is a literal, unidiomatic passive; conveys memorial, so P2 (Pass A)."},
 "SB-1340": {"fd":"P2","conf":"medium","ev":"Пов'язані з фінансами","why":"plural «Пов’язані» does not agree with the singular фінансовий; a minor agreement slip, P2 (Pass A graded P1)."},
 "SB-1442": {"fd":"P2","conf":"high","ev":"зробити очевидним","why":"content is correct; only the terminal period is missing — cosmetic P2 (Pass A)."},
 "SB-1152": {"fd":"P2","conf":"high","ev":"Акт навмисного самогубства","why":"«Акт навмисного самогубства» is fully circular on the headword; not misleading, so P2 (Pass A)."},
 "SB-1089": {"fd":"P2","conf":"high","ev":"поодинці; виключно","why":"content is correct; the definition merely starts lowercase — cosmetic P2 (Pass A)."},
 "SB-1771": {"fd":"P2","conf":"medium","ev":"зіткнувся","why":"DIVERGENCE from Pass A (P1): ua «зіткнувся» is a finite masculine-past citation rather than a neutral participle, but the definition is correct and the learner is not misled on meaning — a citation-form issue (P2), matching Pass B's severity."},
 "SB-0852": {"fd":"P2","conf":"medium","ev":"Піддаватися дії без реакції","why":"«Піддаватися дії без реакції» uses an infinitive to gloss the adjective; conveys passive adequately, so P2 (Pass A)."},
 "SB-0190": {"fd":"P2","conf":"high","ev":"опозиція; протиріччя","why":"content is correct; the definition merely starts lowercase — cosmetic P2 (Pass A)."},
 "SB-1559": {"fd":"P2","conf":"medium","ev":"Приводити в життя","why":"present infinitives «Приводити в життя; породжувати» gloss the past participle generated; conveys the sense, so P2 (Pass A graded P1)."},
 "SB-0794": {"fd":"P1","conf":"high","ev":"Не дбати про щось","why":"neglect is v.,n. but ua «нехтувати» and the definition cover only the verb, dropping the noun sense; Pass A's coverage defect is confirmed."},
 "SB-1092": {"fd":"P1","conf":"high","ev":"виконане однією особою","why":"solo is adj.,n. but ua «соло» and the definition cover only the noun, dropping the adjective sense; Pass A's coverage defect holds."},
 "SB-0764": {"fd":"P1","conf":"high","ev":"посеред","why":"midst is a noun but ua «посеред» is a preposition/adverb, giving no noun equivalent; Pass A's POS mismatch is confirmed."},
 "SB-0494": {"fd":"P2","conf":"medium","ev":"відмінну від людей","why":"the comparison «думку, відмінну від людей» contrasts an opinion with people rather than with their views; a mild logical slip, comprehensible, P2 (Pass A graded P1)."},
 "SB-0092": {"fd":"P2","conf":"medium","ev":"авермент","why":"«авермент» is a rare, unexplained borrowing unsuitable for learner-facing Ukrainian; the rest is fine, so a register P2 (Pass A graded P1)."},
 "SB-0060": {"fd":"P1","conf":"high","ev":"не займаючись цим професійно","why":"amateur is adj.,n. but ua «любитель» and the definition cover only the noun, omitting the adjective; Pass A's coverage defect is confirmed (Pass B wrongly claimed noun/adj matched)."},
 "SB-0475": {"fd":"P1","conf":"medium","ev":"Стан перевищення","why":"excess is n.,adj. but ua «надлишок» and the definition cover only the noun sense; Pass A's coverage defect holds."},
 "SB-0500": {"fd":"P2","conf":"medium","ev":"Вираження або вказівка","why":"the definition uses a noun phrase plus adverbial participles instead of defining the adjective; conveys favourable, so P2 (Pass A graded P1)."},
 "SB-0353": {"fd":"P1","conf":"high","ev":"від їхнього імені або від їхнього імені","why":"the definition has singular/plural disagreement and nonsensically repeats «від їхнього імені»; Pass A's broken-syntax defect is confirmed."},
 "SB-1558": {"fd":"P2","conf":"medium","ev":"надзвичайно важливо","why":"adverbial «надзвичайно важливо» does not agree with the adjective fundamental; comprehensible, so P2 (Pass A graded P1)."},
 "SB-0664": {"fd":"P2","conf":"medium","ev":"з поля зору; не видно","why":"«Неможливо побачити; з поля зору; не видно» is a chain of loosely joined fragments; conveys invisible, so P2 (Pass A)."},
 "SB-0695": {"fd":"P2","conf":"medium","ev":"Створення закону або законів","why":"«Створення закону» is a noun phrase rather than an adjective definition; conveys legislative, so P2 (Pass A graded P1)."},
 "SB-1415": {"fd":"P2","conf":"medium","ev":"Закон або адміністративне правило","why":"plural regulations is defined by singular «Закон або адміністративне правило»; a number mismatch, minor, P2 (Pass A graded P1)."},
 "SB-1665": {"fd":"P2","conf":"medium","ev":"Фрагмент людського виразу","why":"«Фрагмент людського виразу» is a literal, unidiomatic rendering of someone's words; conveys quotation, so P2 (Pass A graded P1)."},
 "SB-1692": {"fd":"P2","conf":"medium","ev":"серія проблем","why":"nominative «серія» after «після» should be genitive «серії» — a case error; comprehensible, so P2 (Pass A graded P1)."},
 "SB-1511": {"fd":"P2","conf":"medium","ev":"З або розташована всередині","why":"«З або розташована всередині» is a feminine-agreeing fragment for the masculine adjective internal; conveys the sense, so P2 (Pass A graded P1)."},
 "SB-1509": {"fd":"P2","conf":"medium","ev":"Можливий або непрямий ефект","why":"plural implications is defined by a singular effect; a number mismatch, minor, P2 (Pass A graded P1)."},
 "SB-1252": {"fd":"P2","conf":"medium","ev":"Ніколи раніше не бачив","why":"subjectless masculine-past verbs «не бачив, не робив» gloss the adjective; conveys unprecedented, so P2 (Pass A graded P1)."},
 "SB-1669": {"fd":"P2","conf":"medium","ev":"Про людину, продовжувати жити","why":"«Про людину, продовжувати жити» is a broken construction that also over-narrows to persons; conveys survive, so P2 (Pass A graded P1)."},
 "SB-0892": {"fd":"P2","conf":"medium","ev":"Переважним чином","why":"«Переважним чином» is awkward and the second sentence is a fragment; conveys predominantly, so P2 (Pass A)."},
 "SB-1203": {"fd":"P2","conf":"medium","ev":"в одне або кілька безперервних ниток","why":"the definition redundantly loops «ниток … в … ниток» with broken number; conveys thread, so P2 (Pass A graded P1)."},
 "SB-1721": {"fd":"P2","conf":"medium","ev":"зором або впливають на нього","why":"plural «Пов’язані … впливають» does not agree with the singular adjective visual; comprehensible, so P2 (Pass A graded P1)."},
 "SB-1236": {"fd":"P2","conf":"medium","ev":"супутній подарунок","why":"«супутній подарунок» is awkward and loosely tied to honouring someone; conveys tribute, so P2 (Pass A)."},
 "SB-1087": {"fd":"P2","conf":"medium","ev":"Відносно, підтримка чи пропаганда","why":"«Відносно, підтримка чи пропаганда соціалізму» is malformed with mismatched noun forms; conveys socialist, so P2 (Pass A graded P1)."},
 "SB-0257": {"fd":"P2","conf":"medium","ev":"щоб об’єднатися або приєднатися","why":"«щоб об’єднатися» breaks the infinitive definition and shifts the agent; conveys consolidate, so P2 (Pass A graded P1)."},
 "SB-0400": {"fd":"P2","conf":"medium","ev":"Спричинення дистресу або занепокоєння","why":"the definition mixes a verbal-noun phrase with nouns rather than defining the adjective; conveys disturbing, so P2 (Pass A)."},
 "SB-0539": {"fd":"P1","conf":"high","ev":"Дивитися пильно або серйозно","why":"gaze is n.,v. but ua «погляд» is noun-only while the definition is verb-only — an internal POS mismatch; Pass A's coverage defect is confirmed."},
 "SB-0437": {"fd":"P1","conf":"high","ev":"зовнішній вигляд","why":"the definition ends «зовнішній вигляд» (physical looks), a false-friend reading of 'appearance' that mis-teaches emergence; P1 (Pass A) over Pass B's P2."},
 "SB-1371": {"fd":"P1","conf":"high","ev":"відомого чи спос","why":"the learner-facing definition is physically truncated mid-word at «…відомого чи спос…»; broken text, so P1 (Pass A) over Pass B's P2."},
 "SB-0883": {"fd":"P2","conf":"medium","ev":"для зображення персонажа","why":"«для зображення» breaks the infinitive definition; conveys portray, so P2 (Pass A graded P1)."},
 "SB-1235": {"fd":"P2","conf":"medium","ev":"Збори, до складу яких","why":"«Збори» suggests a gathering rather than a court, but the trailing «; суд» repairs it; comprehensible, so P2 (Pass A graded P1)."},
 "SB-1119": {"fd":"P2","conf":"medium","ev":"Статистики або пов’язані зі статистикою","why":"«Статистики або пов’язані» combines a noun with a plural adjective; conveys statistical, so P2 (Pass A graded P1)."},
 "SB-0649": {"fd":"P2","conf":"high","ev":"Якість інтенсивності","why":"«Якість інтенсивності» is circular on the cognate and gives no usable meaning; not misleading, so P2 (Pass A)."},
 "SB-1377": {"fd":"P2","conf":"medium","ev":"Будь-яка конкретна особливість","why":"plural aspects is defined by the singular «Будь-яка … особливість»; a number mismatch, minor, P2 (Pass A graded P1)."},
 "SB-1491": {"fd":"P2","conf":"medium","ev":"Інструкція до комп'ютера","why":"the definition treats code as a single instruction and oddly lists a browser as a translator; imprecise, so P2 (Pass A)."},
 "SB-1414": {"fd":"P2","conf":"high","ev":"країна; район;","why":"content is correct; the definition ends on a semicolon rather than terminal punctuation — cosmetic P2 (Pass A)."},
 "SB-0545": {"fd":"P2","conf":"medium","ev":"Демонстрація атрибутів","why":"«Демонстрація атрибутів…» is a noun phrase rather than an adjective definition; conveys glorious, so P2 (Pass A graded P1)."},
 "SB-1552": {"fd":"P2","conf":"medium","ev":"Те, що існує як окрема одиниця","why":"plural entities is defined by singular «Те, що»; a number mismatch, minor, P2 (Pass A graded P1)."},
 "SB-0911": {"fd":"P2","conf":"medium","ev":"ризиків для здоров’я","why":"prevention is narrowed to «ризиків для здоров’я», matching «профілактика» but omitting the general 'stopping something'; comprehensible, so P2 (Pass A graded P1)."},
 "SB-1697": {"fd":"P1","conf":"high","ev":"Пропонується опосередковано","why":"«Пропонується опосередковано» renders 'implied' as 'is proposed/offered', a false sense of implicit; Pass A's semantic defect is confirmed over Pass B's clean."},
 "SB-0592": {"fd":"P2","conf":"medium","ev":"Мати низьку думку про себе","why":"«Мати низьку думку про себе» over-states humility as low self-esteem; the corrective «не гордий… скромний» follows, so P2 (Pass A)."},
 "SB-0700": {"fd":"P2","conf":"medium","ev":"меншої за розміром","why":"the post-colon phrasing has mismatched case and parses awkwardly; conveys lesser, so P2 (Pass A)."},
 "SB-0165": {"fd":"P2","conf":"high","ev":"Вантаж, що перевозиться","why":"«Вантаж, що перевозиться…» circularly repeats the headword gloss; not misleading, so P2 (Pass A)."},
 "SB-0910": {"fd":"P2","conf":"medium","ev":"широке розширення або поширення","why":"«широке розширення» is redundant and the definition stays circular/abstract; comprehensible, so P2 (Pass A)."},
 "SB-0366": {"fd":"P2","conf":"medium","ev":"планування або проектування","why":"the parenthetical accusative «(щось)» after «планування або проектування» is malformed; conveys devise, so P2 (Pass A)."},
 "SB-0588": {"fd":"P1","conf":"medium","ev":"показ розташування ворога","why":"«показ розташування ворога» is a false rendering of 'showing the disposition of an enemy' (розташування = physical position); Pass A's semantic defect is confirmed."},
 "SB-0518": {"fd":"P2","conf":"medium","ev":"на відміну від твердого або газоподібного","why":"scientifically a fluid includes gases, but the everyday liquid sense (ua «рідина» + «на відміну від… газоподібного») is internally consistent for a learner; minor imprecision, so P2 (Pass A graded P1)."},
 "SB-1730": {"fd":"P2","conf":"high","ev":"Відбувається одночасно; одночасний","why":"the definition repeats «одночасний» without adding information; not misleading, so P2 (Pass A)."},
 "SB-1476": {"fd":"P2","conf":"medium","ev":"Ретельно пояснено","why":"specified means 'named explicitly', not «Ретельно пояснено» (carefully explained), and ua «зазначено» is impersonal; a mild imprecision, P2 (Pass A)."},
 "SB-1575": {"fd":"P2","conf":"medium","ev":"Відхилений або не прийнятий","why":"ua «відхилено» is impersonal where a participle «відхилений» fits the family better; the definition is correct, so a minor citation P2 (Pass A)."},
 "SB-0769": {"fd":"P2","conf":"medium","ev":"Найменша можлива сума","why":"«Найменша можлива сума…» is a noun phrase rather than an adjective definition; conveys minimal, so P2 (Pass A)."},
 "SB-0471": {"fd":"P2","conf":"medium","ev":"Відносно біологічної теорії еволюції або до неї","why":"«Відносно… або до неї» is a malformed Russian-influenced calque; conveys evolutionary, so P2 (Pass A graded P1)."},
 "SB-0276": {"fd":"P2","conf":"medium","ev":"(неофіційного) в моральному сенсі","why":"the parenthetical «(неофіційного) в моральному сенсі» is not valid Ukrainian syntax; conveys convict, so P2 (Pass A graded P1)."},
 "SB-1724": {"fd":"P2","conf":"medium","ev":"очікується прибуття; заплановано","why":"lowercase impersonal «очікується… заплановано» does not align with the participle anticipated; conveys the sense, so P2 (Pass A graded P1)."},
 "SB-0936": {"fd":"P2","conf":"medium","ev":"наявність удачі та багатства","why":"«наявність удачі та багатства» is a stiff, narrow description of prosperity; comprehensible, so P2 (Pass A)."},
 "SB-0359": {"fd":"P2","conf":"medium","ev":"Заподіяння руйнування; завдає шкоди","why":"the definition alternates a noun phrase with a finite verb rather than defining the adjective; conveys destructive, so P2 (Pass A)."},
 "SB-0620": {"fd":"P2","conf":"high","ev":"щоб збудник почав діяти на організм;","why":"content is correct; the definition ends on a semicolon rather than terminal punctuation — cosmetic P2 (Pass A)."},
 "SB-0842": {"fd":"P2","conf":"medium","ev":"Емоційно долати","why":"«Емоційно долати» covers only emotional overwhelm and omits being overcome by quantity/force/demands; comprehensible, so P2 (Pass A)."},
 "SB-0799": {"fd":"P1","conf":"medium","ev":"для якої вона добре підходить","why":"the pronoun «вона» has no valid antecedent, leaving the definition ungrammatical and unclear; Pass A's broken-syntax defect is confirmed."},
 "SB-0205": {"fd":"P2","conf":"medium","ev":"відноситься до неї","why":"«відноситься до» is a Russian-influenced calque and the coordination is defective; conveys colonial, so P2 (Pass A graded P1)."},
 "SB-1410": {"fd":"P2","conf":"high","ev":"попередній; що відбувається","why":"the definition starts lowercase and restates the headword before clarifying; cosmetic/thin, so P2 (Pass A)."},
 "SB-1557": {"fd":"P1","conf":"high","ev":"на зовнішній вигляд","why":"«на зовнішній вигляд» means 'apparently/in appearance', not external; a false-sense addition that mis-teaches the adjective; Pass A's defect is confirmed."},
 "SB-0442": {"fd":"P2","conf":"high","ev":"підвищують чиюсь впевненість","why":"content is correct; only the terminal period is missing — cosmetic P2 (Pass A)."},
}
