# -*- coding: utf-8 -*-
"""R2 A/B reconciliation — chunk 1 final verdicts (evidence-first).

Final disposition defaults to Pass A's (each defect independently confirmed
against the frozen Ukrainian text — Pass B's clean calls on these rows were too
lenient), applying the project's established severity standard (non-idiomatic
calques, agreement errors, POS/coverage gaps, false friends, broken syntax and
truncation are P1; purely cosmetic issues are P2). Two evidence-based
divergences toward Pass B are marked with an explicit "fd": SB-1771 and SB-1521.
J[id] = {ev (exact ua/def substring), why, optional fd}.
"""

JUDGMENTS = {
 "SB-0152": {"ev":"випадковий знайомий","why":"buddy is a pal/close informal friend; «випадковий знайомий» (chance acquaintance) mis-teaches the relationship as distant — Pass A's semantic defect confirmed on the frozen text."},
 "SB-0806": {"ev":"Організація або діяльність","why":"non-profit is an adjective, but the definition defines a noun («Організація або діяльність») — the POS-framing defect is confirmed."},
 "SB-1374": {"ev":"напрямок","why":"the trailing «напрямок» renders 'direction' as bearing/heading, a false sense that breaks administration — confirmed."},
 "SB-1075": {"ev":"Знаходиться","why":"«Знаходиться» is a Russian-influenced locative where standard Ukrainian uses «розташований» — the calque is confirmed."},
 "SB-0063": {"ev":"до Конституції","why":"amendment is defined only «до Конституції», misinforming that it is constitution-specific and omitting laws/agreements/documents — confirmed."},
 "SB-0917": {"ev":"проблеми(-й):","why":"the definition is malformed and ends on a dangling colon «проблеми(-й):» — broken learner-facing syntax, confirmed."},
 "SB-1768": {"ev":"сформований у свідомості","why":"content is correct; the definition only starts lowercase and lacks terminal punctuation — cosmetic P2, confirmed."},
 "SB-0761": {"ev":"бере на себе сторона-покупець","why":"«активи та зобов’язання … бере на себе сторона-покупець» miscoordinates number/agent and garbles which party assumes what — confirmed."},
 "SB-1162": {"ev":"Як питання припущення","why":"«Як питання припущення» is a stiff literal calque of 'as a matter of supposition' — the non-idiomatic rendering is confirmed."},
 "SB-1521": {"fd":"P2","conf":"medium","ev":"однаково віддалені один від одного","why":"DIVERGENCE from Pass A (P1→P2): «У всіх точках однаково віддалені один від одного» is a valid, if telegraphic, description of parallelism — «віддалені» agrees with the implied points/lines, not the headword — so this is minor style, not a material grammar defect."},
 "SB-1141": {"ev":"Великі за розміром","why":"«Великі» is plural where the singular adjective істотний is defined — an agreement error in learner-facing metalanguage, confirmed."},
 "SB-1241": {"ev":"Тривожний","why":"leading «Тривожний» (anxiety-causing) diverges from troubled = worried/burdened — a sense drift confirmed (Pass A P2)."},
 "SB-1457": {"ev":"посилання","why":"the gloss «посилання» reads as hyperlink/reference in contemporary Ukrainian, inconsistent with the general-connection definition — the ua↔definition mismatch is confirmed."},
 "SB-0748": {"ev":"тим часом","why":"the noun meantime is glossed with the adverbial «тим часом» ('meanwhile'), a POS mismatch that mistrains usage — confirmed."},
 "SB-1424": {"ev":"План дій","why":"plural strategies is defined by the singular «План дій» — a number-agreement defect confirmed."},
 "SB-1166": {"ev":"Відносно, використовується","why":"«Відносно,» is a Russian-influenced opener and the following verbs disagree with the adjective — confirmed."},
 "SB-0088": {"ev":"Нападати","why":"assault is n.,v. but ua «напад» is noun-only while the definition «Нападати… атакувати» is verb-only — an internal POS mismatch confirmed."},
 "SB-0906": {"ev":"Високого престижу","why":"«Високого престижу» is a fragment that circularly repeats the headword — the pedagogical defect is confirmed (Pass A P2)."},
 "SB-0126": {"ev":"отримує перевагу","why":"«користується або отримує перевагу» is vaguer than receiving a benefit/entitlement — the imprecision is confirmed (Pass A P2)."},
 "SB-0196": {"ev":"для певної переваги","why":"«для певної переваги» understates the shared-purpose nature of a coalition — the pedagogical imprecision is confirmed (Pass A P2)."},
 "SB-1085": {"ev":"Насичуватися рідиною","why":"ua «замочити» is transitive/perfective but the definition «Насичуватися рідиною» is reflexive/intransitive — the voice mismatch is confirmed."},
 "SB-1462": {"ev":"Те, що виробляється","why":"plural outcomes is defined by singular «Те, що виробляється» — a number-agreement defect confirmed."},
 "SB-0485": {"ev":"засноване","why":"«Відносно» calque plus neuter «засноване» not agreeing with the masculine adjective — confirmed."},
 "SB-0472": {"ev":"описувати більше, ніж факт","why":"the definition is near-circular and «описувати більше, ніж факт» is unidiomatic — confirmed (Pass A P2)."},
 "SB-0162": {"ev":"генерувати результат","why":"«генерувати результат» is an avoidable technical calque in a general learner definition — confirmed (Pass A P2)."},
 "SB-1709": {"ev":"Був або містить підкріплення","why":"«Був або містить» mixes past and present tense against the participle reinforced — the tense misalignment is confirmed."},
 "SB-0129": {"ev":"особливо опублікованої","why":"«особливо опублікованої» grammatically attaches to the person rather than the life-account — the syntax defect is confirmed."},
 "SB-0581": {"ev":"Мати на увазі без прямого твердження","why":"hint is n.,v. but ua «підказка» is noun-only while the definition is verb-framed and breaks its own pattern — the POS coverage/consistency defect is confirmed."},
 "SB-1633": {"ev":"пов'язаної з нею","why":"«З хімії або пов’язаної з нею» is a feminine-agreeing fragment for the masculine adjective — confirmed."},
 "SB-1058": {"ev":"Маючи відношення","why":"«Маючи відношення» is Russian-influenced and «розташовані» disagrees with the adjective — confirmed."},
 "SB-0438": {"ev":"на відміну від теорії","why":"neuter «засноване» does not agree with the masculine adjective empirical — the agreement defect is confirmed (Pass A P2)."},
 "SB-1065": {"ev":"прямо; повний; чистий","why":"«прямо; повний; чистий» mixes adverb/adjective forms and the gloss «чистий» misses sheer's core 'utter/complete' and 'steep' senses — confirmed."},
 "SB-1394": {"ev":"короткий опис конкретної ситуації","why":"folding «короткий опис конкретної ситуації» into evaluation conflates unlike senses — the semantic defect is confirmed."},
 "SB-1530": {"ev":"вашому зберіганні","why":"ua impersonal «зберігається» plus second-person «вашому» misalign with the participle retained — confirmed."},
 "SB-1715": {"ev":"художнього твору; тема","why":"the definition repeats «тема» and adds little distinction — the pedagogical thinness is confirmed (Pass A P2)."},
 "SB-0981": {"ev":"Процес реабілітації","why":"«Процес реабілітації когось або чогось» is fully circular on the cognate — confirmed (Pass A P2)."},
 "SB-1352": {"ev":"з наступним додаванням, до або для мети процесу","why":"the parenthetical «з наступним додаванням, до або для мети процесу» is unintelligible learner-facing text — confirmed."},
 "SB-0754": {"ev":"яким хтось або щось згадується","why":"«яким хтось або щось згадується» is a literal, unidiomatic passive calque — confirmed (Pass A P2)."},
 "SB-1340": {"ev":"Пов'язані з фінансами","why":"plural «Пов’язані» does not agree with the singular фінансовий — the agreement defect is confirmed."},
 "SB-1442": {"ev":"зробити очевидним","why":"content is correct; only the terminal period is missing — cosmetic P2, confirmed."},
 "SB-1152": {"ev":"Акт навмисного самогубства","why":"«Акт навмисного самогубства» is fully circular on the headword — confirmed (Pass A P2)."},
 "SB-1089": {"ev":"поодинці; виключно","why":"content is correct; the definition only starts lowercase — cosmetic P2, confirmed."},
 "SB-1771": {"fd":"P2","conf":"medium","ev":"зіткнувся","why":"DIVERGENCE from Pass A (P1→P2): ua «зіткнувся» is a finite masculine-past citation rather than a neutral participle, but the definition is correct and the learner is not misled on meaning — a citation-form issue, matching Pass B's severity."},
 "SB-0852": {"ev":"Піддаватися дії без реакції","why":"«Піддаватися дії без реакції» uses an infinitive to gloss the adjective passive — the POS-framing defect is confirmed (Pass A P2)."},
 "SB-0190": {"ev":"опозиція; протиріччя","why":"content is correct; the definition only starts lowercase — cosmetic P2, confirmed."},
 "SB-1559": {"ev":"Приводити в життя","why":"present infinitives «Приводити в життя; породжувати» gloss the past participle generated — the POS/tense misalignment is confirmed."},
 "SB-0794": {"ev":"Не дбати про щось","why":"neglect is v.,n. but ua «нехтувати» and the definition cover only the verb, dropping the noun sense — the coverage defect is confirmed."},
 "SB-1092": {"ev":"виконане однією особою","why":"solo is adj.,n. but ua «соло» and the definition cover only the noun — the coverage defect is confirmed."},
 "SB-0764": {"ev":"посеред","why":"midst is a noun but ua «посеред» is a preposition/adverb, giving no noun equivalent — the POS mismatch is confirmed."},
 "SB-0494": {"ev":"відмінну від людей","why":"«думку, відмінну від людей» contrasts an opinion with people rather than with their views — the semantic slip is confirmed."},
 "SB-0092": {"ev":"авермент","why":"«авермент» is a rare, unexplained borrowing unsuitable for learner-facing Ukrainian — the register defect is confirmed."},
 "SB-0060": {"ev":"не займаючись цим професійно","why":"amateur is adj.,n. but ua «любитель» and the definition cover only the noun, omitting the adjective — the coverage defect is confirmed (Pass B wrongly claimed noun/adj matched)."},
 "SB-0475": {"ev":"Стан перевищення","why":"excess is n.,adj. but ua «надлишок» and the definition cover only the noun sense — the coverage defect is confirmed."},
 "SB-0500": {"ev":"Вираження або вказівка","why":"the definition uses a noun phrase plus adverbial participles instead of defining the adjective favourable — confirmed."},
 "SB-0353": {"ev":"від їхнього імені або від їхнього імені","why":"the definition has singular/plural disagreement and nonsensically repeats «від їхнього імені» — the broken syntax is confirmed."},
 "SB-1558": {"ev":"надзвичайно важливо","why":"adverbial «надзвичайно важливо» does not agree with the adjective fundamental — confirmed."},
 "SB-0664": {"ev":"з поля зору; не видно","why":"«Неможливо побачити; з поля зору; не видно» is a chain of loosely joined fragments — the syntax defect is confirmed (Pass A P2)."},
 "SB-0695": {"ev":"Створення закону або законів","why":"«Створення закону» is a noun phrase rather than an adjective definition for legislative — confirmed."},
 "SB-1415": {"ev":"Закон або адміністративне правило","why":"plural regulations is defined by singular «Закон або адміністративне правило» — a number-agreement defect confirmed."},
 "SB-1665": {"ev":"Фрагмент людського виразу","why":"«Фрагмент людського виразу» is a literal, unidiomatic rendering of someone's words — the calque is confirmed."},
 "SB-1692": {"ev":"серія проблем","why":"nominative «серія» after «після» should be genitive «серії» — the case error is confirmed."},
 "SB-1511": {"ev":"З або розташована всередині","why":"«З або розташована всередині» is a feminine-agreeing fragment for the masculine adjective internal — confirmed."},
 "SB-1509": {"ev":"Можливий або непрямий ефект","why":"plural implications is defined by a singular effect — a number-agreement defect confirmed."},
 "SB-1252": {"ev":"Ніколи раніше не бачив","why":"subjectless masculine-past verbs «не бачив, не робив» gloss the adjective unprecedented — the POS/syntax defect is confirmed."},
 "SB-1669": {"ev":"Про людину, продовжувати жити","why":"«Про людину, продовжувати жити» is a broken construction that also over-narrows survive to persons — confirmed."},
 "SB-0892": {"ev":"Переважним чином","why":"«Переважним чином» is awkward and the second sentence is a fragment — confirmed (Pass A P2)."},
 "SB-1203": {"ev":"в одне або кілька безперервних ниток","why":"the definition redundantly loops «ниток … в … ниток» with broken number — the syntax defect is confirmed."},
 "SB-1721": {"ev":"зором або впливають на нього","why":"plural «Пов’язані … впливають» does not agree with the singular adjective visual — confirmed."},
 "SB-1236": {"ev":"супутній подарунок","why":"«супутній подарунок» is awkward and loosely tied to honouring someone — confirmed (Pass A P2)."},
 "SB-1087": {"ev":"Відносно, підтримка чи пропаганда","why":"«Відносно, підтримка чи пропаганда соціалізму» is malformed with mismatched noun forms — confirmed."},
 "SB-0257": {"ev":"щоб об’єднатися або приєднатися","why":"«щоб об’єднатися» breaks the infinitive definition and shifts the agent — the syntax defect is confirmed."},
 "SB-0400": {"ev":"Спричинення дистресу або занепокоєння","why":"the definition mixes a verbal-noun phrase with nouns rather than defining the adjective disturbing — confirmed (Pass A P2)."},
 "SB-0539": {"ev":"Дивитися пильно або серйозно","why":"gaze is n.,v. but ua «погляд» is noun-only while the definition is verb-only — the coverage defect is confirmed."},
 "SB-0437": {"ev":"зовнішній вигляд","why":"the definition ends «зовнішній вигляд» (physical looks), a false-friend reading of 'appearance' that mis-teaches emergence — confirmed over Pass B's P2."},
 "SB-1371": {"ev":"відомого чи спос","why":"the learner-facing definition is physically truncated mid-word at «…відомого чи спос…» — broken text, confirmed over Pass B's P2."},
 "SB-0883": {"ev":"для зображення персонажа","why":"«для зображення» breaks the infinitive definition of portray — the syntax defect is confirmed."},
 "SB-1235": {"ev":"Збори, до складу яких","why":"«Збори» denotes a gathering rather than a court/adjudicative body — the semantic defect is confirmed."},
 "SB-1119": {"ev":"Статистики або пов’язані зі статистикою","why":"«Статистики або пов’язані» combines a noun with a plural adjective and does not define the singular adjective — confirmed."},
 "SB-0649": {"ev":"Якість інтенсивності","why":"«Якість інтенсивності» is circular on the cognate and gives no usable meaning — confirmed (Pass A P2)."},
 "SB-1377": {"ev":"Будь-яка конкретна особливість","why":"plural aspects is defined by the singular «Будь-яка … особливість» — a number-agreement defect confirmed."},
 "SB-1491": {"ev":"Інструкція до комп'ютера","why":"the definition treats code as a single instruction and lists a browser as a translator — the pedagogical inaccuracy is confirmed (Pass A P2)."},
 "SB-1414": {"ev":"країна; район;","why":"content is correct; the definition ends on a semicolon rather than terminal punctuation — cosmetic P2, confirmed."},
 "SB-0545": {"ev":"Демонстрація атрибутів","why":"«Демонстрація атрибутів…» is a noun phrase rather than an adjective definition for glorious — confirmed."},
 "SB-1552": {"ev":"Те, що існує як окрема одиниця","why":"plural entities is defined by singular «Те, що» — a number-agreement defect confirmed."},
 "SB-0911": {"ev":"ризиків для здоров’я","why":"prevention is narrowed to «ризиків для здоров’я», omitting the general act of stopping something — the sense-coverage defect is confirmed."},
 "SB-1697": {"ev":"Пропонується опосередковано","why":"«Пропонується опосередковано» renders 'implied' as 'is proposed/offered', a false sense of implicit — confirmed over Pass B's clean."},
 "SB-0592": {"ev":"Мати низьку думку про себе","why":"«Мати низьку думку про себе» overstates humility as low self-esteem — the semantic imprecision is confirmed (Pass A P2)."},
 "SB-0700": {"ev":"меншої за розміром","why":"the post-colon phrasing has mismatched case and parses awkwardly — the syntax defect is confirmed (Pass A P2)."},
 "SB-0165": {"ev":"Вантаж, що перевозиться","why":"«Вантаж, що перевозиться…» circularly repeats the headword gloss — confirmed (Pass A P2)."},
 "SB-0910": {"ev":"широке розширення або поширення","why":"«широке розширення» is redundant and the definition stays circular/abstract — confirmed (Pass A P2)."},
 "SB-0366": {"ev":"планування або проектування","why":"the parenthetical accusative «(щось)» after «планування або проектування» is malformed — confirmed (Pass A P2)."},
 "SB-0588": {"ev":"показ розташування ворога","why":"«показ розташування ворога» is a false rendering of 'showing the disposition of an enemy' (розташування = physical position) — confirmed."},
 "SB-0518": {"ev":"на відміну від твердого або газоподібного","why":"the definition contrasts fluid with gas and ua gives only «рідина», whereas a fluid includes gases — the semantic defect is confirmed."},
 "SB-1730": {"ev":"Відбувається одночасно; одночасний","why":"the definition repeats «одночасний» without adding information — confirmed (Pass A P2)."},
 "SB-1476": {"ev":"Ретельно пояснено","why":"specified means 'named explicitly', not «Ретельно пояснено» (carefully explained), and ua «зазначено» is impersonal — confirmed (Pass A P2)."},
 "SB-1575": {"ev":"Відхилений або не прийнятий","why":"ua «відхилено» is impersonal where the participle «відхилений» fits the family — the citation defect is confirmed (Pass A P2)."},
 "SB-0769": {"ev":"Найменша можлива сума","why":"«Найменша можлива сума…» is a noun phrase rather than an adjective definition for minimal — confirmed (Pass A P2)."},
 "SB-0471": {"ev":"Відносно біологічної теорії еволюції або до неї","why":"«Відносно… або до неї» is a malformed Russian-influenced calque — confirmed."},
 "SB-0276": {"ev":"(неофіційного) в моральному сенсі","why":"the parenthetical «(неофіційного) в моральному сенсі» is not valid Ukrainian syntax — confirmed."},
 "SB-1724": {"ev":"очікується прибуття; заплановано","why":"lowercase impersonal «очікується… заплановано» does not align with the participle anticipated — confirmed."},
 "SB-0936": {"ev":"наявність удачі та багатства","why":"«наявність удачі та багатства» is a stiff, narrow description of prosperity — confirmed (Pass A P2)."},
 "SB-0359": {"ev":"Заподіяння руйнування; завдає шкоди","why":"the definition alternates a noun phrase with a finite verb rather than defining the adjective destructive — confirmed (Pass A P2)."},
 "SB-0620": {"ev":"щоб збудник почав діяти на організм;","why":"content is correct; the definition ends on a semicolon — cosmetic P2, confirmed."},
 "SB-0842": {"ev":"Емоційно долати","why":"«Емоційно долати» covers only emotional overwhelm and omits being overcome by quantity/force/demands — confirmed (Pass A P2)."},
 "SB-0799": {"ev":"для якої вона добре підходить","why":"the pronoun «вона» has no valid antecedent, leaving the definition ungrammatical — the broken syntax is confirmed."},
 "SB-0205": {"ev":"відноситься до неї","why":"«відноситься до» is a Russian-influenced calque and the coordination is defective — confirmed."},
 "SB-1410": {"ev":"попередній; що відбувається","why":"the definition starts lowercase and restates the headword before clarifying — confirmed (Pass A P2)."},
 "SB-1557": {"ev":"на зовнішній вигляд","why":"«на зовнішній вигляд» means 'apparently/in appearance', not external — the false-sense addition is confirmed."},
 "SB-0442": {"ev":"підвищують чиюсь впевненість","why":"content is correct; only the terminal period is missing — cosmetic P2, confirmed."},
}
