# -*- coding: utf-8 -*-
"""R2 A/B reconciliation — chunk 2 final verdicts (evidence-first).

Same standard as chunk 1: final disposition defaults to Pass A's, each defect
confirmed on the frozen text; project severity standard. Documented divergences:
SB-1124 (Pass A clean -> P2, upholding Pass B) and SB-0537 (Pass A P1 -> clean,
overturning Pass A). J[id] = {ev, why, optional fd/conf/cat/tgt/val}.
"""

JUDGMENTS = {
 "SB-0693": {"ev":"викликати історії","why":"«неймовірну велич» and «викликати історії» are stiff and do not directly define legendary — confirmed (Pass A P2)."},
 "SB-0736": {"ev":"Практика маніпулювання або стан маніпулювання","why":"the definition merely repeats manipulation and gives no usable explanation — confirmed (Pass A P2)."},
 "SB-1124": {"fd":"P2","conf":"medium","cat":"imprecise-gloss","tgt":"ua","val":"розмішувати; помішувати","ev":"ворушити","why":"DIVERGENCE from Pass A (clean→P2): the definition describes stirring the particles of a liquid, but the gloss «ворушити» (to move slightly) is imprecise; «помішувати/розмішувати» fits the liquid-stirring sense — Pass B's P2 upheld."},
 "SB-0537": {"fd":"clean-candidate","conf":"medium","ev":"із ставкою на результат","why":"DIVERGENCE from Pass A (P1→clean): the definition does state «із ставкою на результат» and names skill and chance, so it does capture wagering on an uncertain outcome; Pass A's 'does not explain wagering' claim does not hold against the frozen text, so no learner-facing defect remains."},
 "SB-1068": {"ev":"контрактувати","why":"«контрактувати» is a nonstandard calque of 'contract' meaning become smaller — confirmed."},
 "SB-0956": {"ev":"Примушувати","why":"rape is n.,v. but ua «зґвалтування» is noun-only while the definition «Примушувати…» is verb-only — coverage defect confirmed."},
 "SB-0925": {"ev":"Отримання прибутку","why":"«Отримання прибутку» is a noun phrase, not an adjective definition for profitable — confirmed (Pass A P2)."},
 "SB-0977": {"ev":"Не звертаючи уваги на; ігнорування","why":"«Не звертаючи уваги на; ігнорування» mixes an incomplete participial phrase with a noun and does not define the adverb — confirmed."},
 "SB-0694": {"ev":"Закон, прийнятий законодавчим","why":"legislation is a body or process of lawmaking, not the single «Закон» the definition states — semantic defect confirmed."},
 "SB-0199": {"ev":"Відноситься до","why":"«Відноситься до» is a Russian-influenced calque and the definition is unnecessarily narrow — confirmed."},
 "SB-1760": {"ev":"Змусив на деякий час зупинитися","why":"impersonal ua «призупинено» clashes with the masculine-past/present-reflexive definition «Змусив… переривається» — misalignment confirmed."},
 "SB-0963": {"ev":"Задня або крайня задня частина","why":"rear is adj.,n. but ua «задній» is adjective-only while the definition is noun-only — coverage defect confirmed."},
 "SB-0015": {"ev":"викликати звіт","why":"«викликати звіт» is a literal calque of 'call to account', non-idiomatic Ukrainian — confirmed (Pass B wrongly cleared it)."},
 "SB-0187": {"ev":"Про або щодо","why":"«Про або щодо» is a fragmentary calque rather than an adjective definition for civic — confirmed (Pass A P2)."},
 "SB-1680": {"ev":"Автоматичним способом","why":"«Автоматичним способом» is circular and provides no usable sense — confirmed (Pass A P2)."},
 "SB-0098": {"ev":"юрист; той, хто","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
 "SB-1229": {"ev":"відкритість; доступність для перевірки","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
 "SB-0999": {"ev":"Для створення або розмноження","why":"the purpose phrase «Для створення» does not define the verb and the entry covers only biological reproduction — confirmed."},
 "SB-1455": {"ev":"Розмова або обмін між людьми","why":"the definition narrows interaction to conversation/exchange between people — sense-coverage confirmed (Pass A P2)."},
 "SB-1573": {"ev":"Вивчення людського розуму","why":"psychology studies mind and behaviour, not only the human mind — sense-coverage confirmed (Pass A P2)."},
 "SB-0944": {"ev":"артерії поблизу шкіри","why":"the definition confuses pulse with heartbeat and says arteries are compressed rather than palpated — semantic defect confirmed."},
 "SB-1565": {"ev":"змінений; змінено","why":"the definition «змінений; змінено» merely restates the headword forms and teaches nothing — both passes agree P2."},
 "SB-1752": {"ev":"невимушено; неквапливий","why":"the definition mixes adjective and adverb forms («невимушено; неквапливий») — grammar defect confirmed."},
 "SB-1532": {"ev":"демографічною інформацією","why":"the definition narrows statistics to demographic collections and repeats population count — sense-coverage confirmed (Pass A P2)."},
 "SB-0775": {"ev":"біль тіла або розуму","why":"«біль тіла або розуму» and the unexplained «дистрес» are unnatural learner-facing Ukrainian — register confirmed (Pass A P2)."},
 "SB-0765": {"ev":"переїзду на деякий час","why":"the definition unnecessarily limits migration to living elsewhere only for a time — sense-coverage confirmed (Pass A P2)."},
 "SB-1009": {"ev":"кожен до кожного","why":"«кожен до кожного; особливий; власні» has broken agreement and does not explain respective — confirmed."},
 "SB-1617": {"ev":"експозиція","why":"«експозиція» is a false friend here; a lecture is an oral presentation or lesson — semantic defect confirmed."},
 "SB-0542": {"ev":"етнічної приналежності","why":"the semicolon creates an awkward lowercase participial continuation and «етнічна приналежність» is less idiomatic — confirmed (Pass A P2)."},
 "SB-1418": {"ev":"напр. сировини або персоналу","why":"the example after «напр.» uses incorrect genitive and lacks clean punctuation — confirmed (Pass A P2)."},
 "SB-1118": {"ev":"Простий на вигляд","why":"ua «разючий; суворий» (striking/severe) is not reconciled with the definition «Простий на вигляд; безплідний» (plain/barren) — ua↔definition inconsistency confirmed."},
 "SB-0642": {"ev":"Прийнята кількість","why":"«Прийнята кількість» is too vague to explain intake in the consumption sense — pedagogical confirmed (Pass A P2)."},
 "SB-0782": {"ev":"нову або змінену форму","why":"accusative «нову або змінену форму» does not agree with the nominative «результат» — agreement defect confirmed."},
 "SB-1191": {"ev":"відмінно, дивовижно","why":"adverbial «добре; відмінно» does not directly define the adjective terrific — confirmed (Pass A P2)."},
 "SB-1638": {"ev":"змінилася форма чи функція","why":"lowercase feminine-past «змінилася» does not align with the participle converted — confirmed."},
 "SB-1663": {"ev":"Заборонено; заборонений; недозволено","why":"ua and the definition mix impersonal, adjective and adverb forms — confirmed (Pass A P2)."},
 "SB-0827": {"ev":"сприятливого результату","why":"the definition starts lowercase and lacks terminal punctuation — cosmetic P2, confirmed."},
 "SB-0118": {"ev":"Тіло води","why":"«Тіло води … міститься увігнутою береговою лінією» is an unintelligible literal calque — confirmed over Pass B's P2."},
 "SB-1513": {"ev":"завдання.","why":"the definition starts lowercase and reduces job to an unexplained one-word synonym — confirmed (Pass A P2)."},
 "SB-1690": {"ev":"постановка з місця","why":"«постановка з місця» is a false, unidiomatic rendering of displacement — confirmed."},
 "SB-1452": {"ev":"Пропонується без прямого","why":"the active headword implies and ua «передбачає» are paired with passive/plural fragments «Пропонується … причетні» with an agreement error — confirmed over Pass B's P2."},
 "SB-0069": {"ev":"конкретне виробництво","why":"«конкретне виробництво» is not an accurate account of apparatus as equipment for a task — semantic defect confirmed."},
 "SB-0310": {"ev":"критикується, рецензується","why":"the comma between «критикується, рецензується» joins alternatives incorrectly and the wording is narrow — confirmed (Pass A P2)."},
 "SB-1487": {"ev":"Розраховується наближено","why":"present reflexive «Розраховується» misaligns with the participle approximated and the definition lacks a period — confirmed (Pass A P2)."},
 "SB-0081": {"ev":"Для забезпечення бронею","why":"the definition begins with the purpose construction «Для забезпечення» instead of defining the verb arm — confirmed."},
 "SB-0914": {"ev":"в приватну","why":"the phrase ends at «в приватну» without the required noun «власність» — broken syntax confirmed."},
 "SB-1175": {"ev":"рубання, удару, рубання","why":"the definition lists «рубання» three times, a redundant repetition — both passes agree P2."},
 "SB-0573": {"ev":"Принести врожай; жати; підбирати","why":"harvest is n.,v. but ua «урожай» is noun-only while the definition is verb-only — coverage defect confirmed."},
 "SB-0872": {"ev":"Яма в землі","why":"«Яма — яма в землі» is circular and adds no usable explanation — confirmed (Pass A P2)."},
 "SB-1518": {"ev":"варіантів, які можна зробити","why":"«варіант із набору варіантів, які можна зробити» is circular and uses the wrong collocation «зробити» — confirmed."},
 "SB-0156": {"ev":"Уряд через бюро","why":"«Уряд через бюро» is a literal, unidiomatic rendering that does not explain bureaucracy — confirmed."},
 "SB-1400": {"ev":"заснована для просування справи","why":"the definition is missing terminal punctuation — cosmetic P2, confirmed."},
 "SB-1312": {"ev":"Мати цінність, заслуги або цінність","why":"the finite phrase repeats «цінність» and does not directly define the adjective worthy — confirmed (Pass A P2)."},
 "SB-0965": {"ev":"Запевнити заново","why":"«Запевнити заново» is a literal calque and «звільнитися» changes the subject of the transitive verb — confirmed."},
 "SB-0895": {"ev":"При підготовці до основної справи","why":"the prepositional phrase «При підготовці» does not directly define the adjective preliminary — confirmed (Pass A P2)."},
 "SB-1753": {"ev":"контроль або обережність; резерв","why":"the definition is lowercase and vague, and «резерв» (reserve) is a false-friend sense for restraint — confirmed over Pass B's P2."},
 "SB-1484": {"ev":"виконує певну вимогу","why":"«виконує певну вимогу» is a literal calque; idiomatic Ukrainian is «відповідає вимозі» — confirmed."},
 "SB-1503": {"ev":"випадкова неправильна дія","why":"the definition starts lowercase and redundantly repeats «помилка» — confirmed (Pass A P2)."},
 "SB-0789": {"ev":"Муніципалітет або","why":"the definition begins with the noun municipality instead of defining the adjective municipal — confirmed."},
 "SB-1010": {"ev":"У відносний спосіб","why":"«У відносний спосіб» is a false literal rendering and the arrays explanation is needlessly technical — confirmed."},
 "SB-0271": {"ev":"будує або вдосконалює будівлі","why":"the definition restricts contractor to construction, omitting contracted services and other work — sense-coverage confirmed."},
 "SB-1769": {"ev":"У стані віри","why":"«У стані віри» is a literal calque and does not express being firmly persuaded — confirmed."},
 "SB-1524": {"ev":"передбачив","why":"ua «передбачив» is a masculine-past finite verb (a bad citation) and «відомо заздалегідь» is a lowercase fragment — the combined defect is confirmed over Pass B's P2."},
 "SB-0823": {"ev":"дочка чи син людини","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
 "SB-1465": {"ev":"Відноситься до світу","why":"the definition twice uses the Russian-influenced «відноситься/має відношення» — calque confirmed."},
 "SB-0360": {"ev":"висуваючи претензії на їх увагу","why":"the definition uses mismatched plural pronouns and an opaque attention-claim sense instead of detention — confirmed."},
 "SB-1482": {"ev":"кубічних футах в англійській мові","why":"the unit sentence confuses metric/imperial systems with languages and is grammatically malformed — confirmed."},
 "SB-0172": {"ev":"Домашня тварина виду","why":"the plural mass noun cattle is defined as one «Домашня тварина» and then broadened inconsistently — number-agreement confirmed."},
 "SB-0636": {"ev":"З, відноситься до","why":"«З, відноситься до» is malformed and contains the Russian-influenced «відноситься до» — confirmed."},
 "SB-0860": {"ev":"та садівни","why":"the learner-facing definition is physically truncated mid-word at «…та садівни…» — broken text confirmed over Pass B's P2."},
 "SB-1176": {"ev":"Непряме представлення","why":"«Непряме представлення» is a noun phrase, not an adjective definition for symbolic — confirmed (Pass A P2)."},
 "SB-1637": {"ev":"Перевірено або ратифіковано","why":"ua «підтверджено» is impersonal where a participle fits the family — citation confirmed (Pass A P2)."},
 "SB-0445": {"ev":"Не маючи кінця","why":"«Не маючи кінця» is an adverbial participle, not a direct adjective definition for endless — confirmed (Pass A P2)."},
 "SB-0987": {"ev":"вже виникли","why":"«вже виникли» does not express items already used, taken or accounted for — semantic defect confirmed."},
 "SB-1480": {"ev":"Спосіб досягнення чогось","why":"plural techniques is defined as one «Спосіб» — number-agreement confirmed."},
 "SB-1099": {"ev":"адаптована до неї","why":"masculine «Має» and feminine «адаптована» lack an agreeing subject — confirmed."},
 "SB-1341": {"ev":"Що щось робить або для чого використовується","why":"the word-family ua includes noun and verb, but the definition covers only the noun sense — coverage confirmed."},
 "SB-1026": {"ev":"обряд; повторюваний набір дій","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
 "SB-1137": {"ev":"надання напр. завершена робота","why":"«напр. завершена робота» has a case error (should be genitive) and an unexpanded abbreviation — both passes agree P2."},
 "SB-0634": {"ev":"стимулювання впливу","why":"«піднесення чи стимулювання впливу» is grammatically opaque and does not explain inspiration — confirmed."},
 "SB-1738": {"ev":"як льодовик на скелі або море на скелі","why":"erosion is a process, not merely its result, and «як льодовик на скелі» is grammatically defective — confirmed."},
 "SB-1338": {"ev":"Акт вивезення","why":"the word-family ua includes noun and verb, but the definition gives only the noun act — coverage confirmed."},
 "SB-1688": {"ev":"Будучи поміченим","why":"ua impersonal «виявлено» and «Будучи поміченим» do not align cleanly with detected — confirmed (Pass A P2)."},
 "SB-0385": {"ev":"Вираження словами, усним або письмовим","why":"«Вираження словами, усним або письмовим» has broken case and adjective agreement — confirmed."},
 "SB-0430": {"ev":"Дозвіл і відповідність необхідним умовам","why":"the noun-phrase definition does not define an adjective, and «придатний» alone misses having the right to participate — confirmed."},
 "SB-1273": {"ev":"по воді, повітрі або в космосі","why":"bare «судно» suggests watercraft, while the definition extends it to air and space without qualifiers — ua↔definition inconsistency confirmed (Pass A P2)."},
 "SB-1510": {"ev":"викладено авторитетно як","why":"lowercase plural «обов’язкові» has no agreeing noun and does not define imposed — confirmed."},
 "SB-1339": {"ev":"Один із елементів","why":"the plural headword factors is defined with singular «Один із елементів» — number-agreement confirmed."},
 "SB-1479": {"ev":"Технології або","why":"«Технології або пов’язані з ними» combines a noun with a plural adjective and does not define technical — confirmed."},
 "SB-1463": {"ev":"для ведення бізнесу","why":"the definition restricts partnership to conducting a business, omitting other formal cooperation — sense-coverage confirmed (Pass A P2)."},
 "SB-1733": {"ev":"З іншої точки зору; з іншого боку","why":"conversely means in an opposite or reversed relation, not merely from another viewpoint — semantic defect confirmed."},
 "SB-0533": {"ev":"служіння меті","why":"the noun phrase «служіння меті» does not directly define the adjective functional — confirmed (Pass A P2)."},
 "SB-0547": {"ev":"Процес, або сила, управління","why":"«Процес, або сила, управління» has invalid punctuation and does not coherently define governance — confirmed."},
 "SB-0658": {"ev":"Знаходження між двома крайнощами","why":"the noun phrase «Знаходження між» is a Russian-influenced construction and does not define the adjective intermediate — confirmed."},
 "SB-0853": {"ev":"Хтось із духовною владою","why":"«Хтось із духовною владою» is vague and does not identify a pastor as a Christian minister — pedagogical confirmed (Pass A P2)."},
 "SB-0972": {"ev":"Акт відображення або стан відображення","why":"the definition merely repeats reflection and does not explain the stated image sense — pedagogical confirmed (Pass A P2)."},
 "SB-1096": {"ev":"Протягнути через відстань","why":"span is v.,n. but ua and the definition provide only verb senses — coverage defect confirmed."},
 "SB-1246": {"ev":"Повертати кінці чого-небудь","why":"twist is v.,n. but ua and the definition cover only the verb — coverage defect confirmed."},
 "SB-0039": {"ev":"Стурбований красою","why":"«Стурбований красою» mistranslates 'concerned with' and gives the wrong Ukrainian sense of aesthetic — confirmed (Pass B wrongly cleared it)."},
 "SB-1184": {"ev":"Спровокувати когось на неправоту","why":"«Спровокувати когось на неправоту» is an unidiomatic false rendering of enticing someone to wrongdoing — confirmed."},
 "SB-1677": {"ev":"Наявність супроводу","why":"prepositional ua «у супроводі» and the noun/infinitive definition do not align with accompanied — confirmed."},
 "SB-0943": {"ev":"Психіатрія або","why":"the noun «Психіатрія» followed by feminine «пов’язана» does not define the adjective psychiatric — confirmed."},
 "SB-0047": {"ev":"Не належать до тієї самої країни","why":"the singular adjective alien is defined with plural verb and adjective forms, making the sentence grammatically incoherent — confirmed (Pass B wrongly cleared it)."},
 "SB-0871": {"ev":"зазвичай нападають","why":"the definition shifts from singular «злочинець» to plural «нападають» without an antecedent — confirmed."},
 "SB-1783": {"ev":"Так названо; зазвичай називають","why":"the ua abbreviation lacks its final period and the passive definition is awkward — confirmed (Pass A P2)."},
 "SB-0622": {"ev":"Володіння чи здійснення впливу","why":"the noun phrase «Володіння чи здійснення впливу» does not define the adjective influential — confirmed (Pass A P2)."},
 "SB-1431": {"ev":"Усне або письмове зауваження","why":"plural comments is defined as one «зауваження» — number-agreement confirmed."},
 "SB-0446": {"ev":"індосамент","why":"the unexplained specialist borrowing «індосамент» is inappropriate in a general definition of endorse — register confirmed."},
 "SB-0740": {"ev":"Приналежність або характеристика моря","why":"the definition shifts from a singular noun to plural participles, producing broken adjective agreement — confirmed."},
}
