# -*- coding: utf-8 -*-
"""R2 A/B reconciliation — chunk 3 final verdicts (evidence-first).

Same standard as chunks 1-2. Documented divergences: SB-0882 (Pass A clean -> P2,
upholding Pass B) and SB-1640 (Pass A P1 -> P2: a gloss citation-form issue only,
with a correct definition, consistent with the SB-1771/SB-1575 treatment).
J[id] = {ev, why, optional fd/conf/cat/tgt/val}.
"""

JUDGMENTS = {
 "SB-1560": {"ev":"культурні стосунки","why":"«певний період років» and «культурні стосунки» are literal, unidiomatic renderings — the calque is confirmed."},
 "SB-0623": {"ev":"Природно, як частина","why":"«Природно, як частина або наслідок чогось» is a fragment rather than an adjective definition for inherent — confirmed (Pass A P2)."},
 "SB-1750": {"ev":"Описів або відмінностей","why":"genitive plural «Описів або відмінностей» has no governing word and does not define the adjective qualitative — confirmed."},
 "SB-1373": {"ev":"Успішно виконувати; виконати","why":"the definition mixes imperfective and perfective near-synonyms without clarifying achieve — confirmed (Pass A P2)."},
 "SB-1025": {"ev":"гвалтом","why":"archaic «гвалтом» is unsuitable in an otherwise contemporary learner definition — register confirmed (Pass A P2)."},
 "SB-1200": {"ev":"За ним; цим","why":"«За ним; цим» does not convey thereby and presents false equivalents — semantic defect confirmed."},
 "SB-0492": {"ev":"особливо той, хто","why":"masculine «той» does not agree with feminine «людина» — agreement defect confirmed (Pass A P2)."},
 "SB-1432": {"ev":"Менша самодостатня частина","why":"plural components is defined as one «Менша самодостатня частина» — number-agreement confirmed."},
 "SB-1037": {"ev":"один видатний для благочестя","why":"«один видатний для благочестя» is an unintelligible literal calque — confirmed."},
 "SB-0377": {"ev":"чи міжнародними організаціями","why":"the definition is missing terminal punctuation — cosmetic P2, confirmed."},
 "SB-1073": {"ev":"Відбувається одночасно.","why":"finite «Відбувається» does not directly define the adverb simultaneously — confirmed (Pass A P2)."},
 "SB-1384": {"ev":"великі обсяги даних;","why":"the definition ends with a semicolon instead of terminal punctuation — cosmetic P2, confirmed."},
 "SB-1627": {"ev":"дочірньою компанією або дочірньою компанією","why":"the definition repeats «дочірня компанія» twice around 'або' — both passes agree P2."},
 "SB-0519": {"ev":"Кількість плівки або стрічки","why":"footage is recorded moving-image material, not «Кількість плівки або стрічки» consumed — semantic defect confirmed."},
 "SB-1653": {"ev":"Маючи повну схожість","why":"plural ua «однакові» and the participial definition do not align with the singular adjective identical — confirmed."},
 "SB-0993": {"ev":"для відновлення свіжості","why":"the second clause begins with the purpose phrase «для відновлення» instead of continuing the verb definition of renew — confirmed."},
 "SB-1522": {"ev":"Значення, яке залишається постійним","why":"plural parameters is defined as one «Значення» — number-agreement confirmed."},
 "SB-0134": {"ev":"Пролити кров","why":"the transitive perfective «Пролити кров» does not define the intransitive verb кровоточити — confirmed."},
 "SB-0567": {"ev":"або як руками","why":"the ending «або як руками» is nonsensical and leaves handling undefined — confirmed."},
 "SB-1293": {"ev":"один під одним","why":"weaving alternates material over and under; the definition says only «один під одним» — semantic defect confirmed."},
 "SB-0865": {"ev":"кривди чи","why":"the learner-facing definition is physically truncated mid-clause at «…кривди чи…» — broken text confirmed over Pass B's P2."},
 "SB-0122": {"ev":"Дуже любив, ніжно любив","why":"past-tense «Дуже любив» neither agrees with nor defines the adjective beloved — POS/grammar defect confirmed over Pass B's P2."},
 "SB-0313": {"ev":"згуртовувати в масу","why":"«згуртовувати в масу» is the wrong verb and obscures the physical crush sense — confirmed."},
 "SB-1650": {"ev":"Виконання тесту","why":"ua «клас» conflicts with the definition's assessment-mark sense — ua↔definition inconsistency confirmed."},
 "SB-0790": {"ev":"Маючи однакові відносини, один до одного","why":"«Маючи однакові відносини, один до одного» is grammatically broken and is not an adjective definition of mutual — confirmed."},
 "SB-1661": {"ev":"факт чи подія цього","why":"the ending «факт чи подія цього» is grammatically meaningless — confirmed."},
 "SB-1129": {"ev":"Відносно стратегії.","why":"«Відносно стратегії» is a Russian-influenced calque and not a complete adjective definition — confirmed."},
 "SB-0644": {"ev":"складений і скоординований","why":"the definition starts lowercase and lacks terminal punctuation — cosmetic P2, confirmed."},
 "SB-1245": {"ev":"Сума грошей, прийнята як продажі","why":"«Сума грошей, прийнята як продажі» is an unidiomatic literal calque — confirmed."},
 "SB-1759": {"ev":"додано, щоб забезпечити","why":"lowercase «додано» is impersonal/perfective and does not align with the adjective supplementary — confirmed."},
 "SB-1094": {"ev":"стан здатний контролювати","why":"«стан здатний контролювати» is ungrammatical; sovereignty is the right or ability to self-govern — confirmed."},
 "SB-0508": {"ev":"часто виготовляється зі свинцю","why":"the definition is over-specific about a lead projectile and uses the vague category «особиста зброя» — pedagogical confirmed (Pass A P2)."},
 "SB-0215": {"ev":"з ким проводять час або супроводжують","why":"the definition lacks a period and ends with a subjectless plural verb not agreeing with «хтось» — confirmed."},
 "SB-0654": {"ev":"Вплутуватися або втягуватись","why":"«Вплутуватися або втягуватись» is an awkward way to express unwanted intervention — confirmed (Pass A P2)."},
 "SB-0285": {"ev":"бути суб’єктом, який визначає","why":"«Право … бути суб’єктом, який визначає» is a literal legalistic calque unsuitable for learners — confirmed."},
 "SB-0099": {"ev":"Пов'язувати право власності","why":"attribute is v.,n. but ua «атрибут» gives only the noun while the definition «Пов’язувати…» gives only the verb — coverage defect confirmed over Pass B's P2."},
 "SB-1469": {"ev":"Внесення свого імені","why":"registered is a participle, but the definition «Внесення свого імені» names the act of entering a name — POS misalignment confirmed."},
 "SB-1108": {"ev":"головна або найважливіша частина","why":"ua includes the physical prожектор, but the definition covers only the figurative center of attention — sense-coverage confirmed."},
 "SB-0217": {"ev":"вони мотивовані","why":"plural «вони» has no valid antecedent after singular «усвідомлення», breaking the definition of compassion — confirmed."},
 "SB-1594": {"ev":"наявність бажання щось зробити","why":"the definition uses noun phrases and wrongly treats willingness as part of being capable — semantic defect confirmed."},
 "SB-1613": {"ev":"мають намір формувати","why":"data cannot «мати намір»; the literal construction wrongly assigns intention to input — confirmed."},
 "SB-0435": {"ev":"Для інкапсуляції","why":"the purpose noun phrase «Для інкапсуляції» does not define the verb вбудовувати — confirmed."},
 "SB-0639": {"ev":"типу або виду, якого недостатньо","why":"«Недостатньо; типу або виду…» is a malformed adverbial fragment, not an adjective definition — confirmed."},
 "SB-0107": {"ev":"розіграної вистави","why":"the definition is circular and awkwardly limits backdrop to a performed show — pedagogical confirmed (Pass A P2)."},
 "SB-1345": {"ev":"яку вважають самотньою","why":"«самотньою» means lonely, not considered separately as an individual — semantic defect confirmed over Pass B's P2."},
 "SB-1525": {"ev":"Прихід раніше за порядком","why":"the noun «Прихід» does not define the adjective prior — confirmed."},
 "SB-0599": {"ev":"фігури в дискурсі","why":"ua «зображення» misses literary imagery and «фігури в дискурсі» is opaque and unidiomatic — confirmed."},
 "SB-0966": {"ev":"часто насильницький","why":"masculine «насильницький» dangles after «часто» and does not modify the intended noun — confirmed."},
 "SB-0136": {"ev":"Викликати божественну прихильність","why":"«Викликати божественну прихильність» is stiff and does not directly explain blessing someone — confirmed (Pass A P2)."},
 "SB-0602": {"ev":"реалізація відноситься до","why":"«відноситься до» is a Russian-influenced calque and the definition wrongly equates implementation with construction — confirmed."},
 "SB-1254": {"ev":"Відбудеться або з'явиться","why":"future-tense «Відбудеться» does not directly define the adjective upcoming — confirmed (Pass A P2)."},
 "SB-1443": {"ev":"має відношення до такого до","why":"the learner-facing definition is truncated at «…має відношення до такого до…» and also repeats «документ» — broken text confirmed over Pass B's P2."},
 "SB-1544": {"ev":"містить підмет і дієслово","why":"ua «пункт» selects the document/contract sense but the definition describes a grammatical clause — ua↔definition inconsistency confirmed."},
 "SB-0718": {"ev":"лінійне, поетапне мислення","why":"the definition inaccurately reduces logic to linear step-by-step problem solving — semantic defect confirmed."},
 "SB-1356": {"ev":"якщо формально виражено","why":"«якщо формально виражено» lacks agreement with політика/принцип, leaving the clause malformed — confirmed."},
 "SB-0132": {"ev":"яким вона ріже","why":"the pronoun in «яким вона ріже» has an unclear antecedent and produces awkward syntax — confirmed (Pass A P2)."},
 "SB-0614": {"ev":"особливо до вторгнення","why":"past-tense «Народився» does not define the adjective and the invasion qualifier is inaccurate — confirmed."},
 "SB-0719": {"ev":"тривалого існування","why":"the adverbial participle «Існуючи» does not directly define the adjective and the phrase is redundant — confirmed (Pass A P2)."},
 "SB-1640": {"fd":"P2","conf":"medium","ev":"десятиліть","why":"DIVERGENCE from Pass A (P1→P2): ua «десятиліть» is genitive plural where the nominative «десятиліття» is the citation form, but the definition is correct and the meaning is clear — a citation-form issue, consistent with the SB-1771 treatment."},
 "SB-0188": {"ev":"займається цивільним життям","why":"civilian is n.,adj. but ua «цивільний» is adjective-only while the definition is noun-only — coverage defect confirmed."},
 "SB-0352": {"ev":"Вживається з «від»","why":"the usage note wrongly says deprive is used with «від» rather than the genitive «позбавляти когось чогось» — pedagogical-accuracy defect confirmed."},
 "SB-0733": {"ev":"вимагається або наказується владою","why":"the definition starts lowercase and repeats the headword without useful structure — confirmed (Pass A P2)."},
 "SB-1502": {"ev":"Прийти в поле зору.","why":"the past headword emerged is defined with the present infinitive «Прийти» — tense misalignment confirmed (Pass A P2)."},
 "SB-1310": {"ev":"виконувати релігійні вправи","why":"worship is n.,v. but ua «поклоніння» is noun-only while the definition is verb-only — coverage defect confirmed."},
 "SB-1303": {"ev":"не одружилася повторно:","why":"the definition ends with a dangling colon and no following text — both passes agree P2."},
 "SB-0048": {"ev":"діапазон","why":"the definition includes the unrelated noun «діапазон» and does not clearly separate physical alignment from agreement — confirmed over Pass B's clean."},
 "SB-0800": {"ev":"Наявність почесних якостей","why":"the definition alternates a noun phrase with an infinitive instead of defining the adjective noble — confirmed."},
 "SB-1100": {"ev":"має задовольняти матеріал","why":"a material or product cannot «задовольняти вимогам»; Ukrainian requires «відповідати вимогам» — grammar defect confirmed."},
 "SB-1477": {"ev":"Достатнього типу або виду","why":"«Достатнього типу або виду» is circular and unnatural — pedagogical confirmed (Pass A P2)."},
 "SB-0241": {"ev":"розташовані або зібрані;","why":"the definition ends with a semicolon instead of terminal punctuation — cosmetic P2, confirmed."},
 "SB-0527": {"ev":"не міцний","why":"the adjective «не міцний» should be written together as «неміцний» in this meaning — orthography defect confirmed (Pass A P2)."},
 "SB-0812": {"ev":"загально чи широко відома","why":"the definition mixes feminine and masculine agreement and handles person and organization inconsistently — confirmed."},
 "SB-0662": {"ev":"Викликання бажання знати більше","why":"the noun phrase «Викликання бажання» does not directly define the adjective intriguing — confirmed (Pass A P2)."},
 "SB-0055": {"ev":"Відкладати для певної мети","why":"«Відкладати» suggests postponement and does not reliably express allocating for a purpose — semantic defect confirmed."},
 "SB-0030": {"ev":"Дія регулювання чогось","why":"the definition is missing terminal punctuation — cosmetic P2, confirmed."},
 "SB-0252": {"ev":"Слідом, по черзі, без перерви","why":"«Слідом, по черзі, без перерви» is a fragment and not an idiomatic adjective definition — confirmed (Pass A P2)."},
 "SB-0337": {"ev":"Ситуація, коли або сума, за якої","why":"«Ситуація, коли або сума, за якої» is grammatically malformed and not usable as a definition — confirmed."},
 "SB-1778": {"ev":"все так само","why":"«все так само» is not an idiomatic equivalent of nevertheless in this entry — confirmed (Pass A P2)."},
 "SB-1438": {"ev":"в оточенні інших істотних речей","why":"«в оточенні інших істотних речей» is nonsensical and does not explain core — confirmed."},
 "SB-0995": {"ev":"Плата за оренду чогось","why":"ua «оренда» denotes renting, while the definition covers only the fee paid — ua↔definition inconsistency confirmed."},
 "SB-0441": {"ev":"підкладати","why":"the definition contains unclear pronoun reference and the unrelated verb «підкладати» — confirmed."},
 "SB-0543": {"ev":"Звернути (очі чи погляд)","why":"glance is n.,v. but ua «погляд» is noun-only while the definition is verb-only — coverage defect confirmed."},
 "SB-1737": {"ev":"Проміжок часу або певний проміжок часу","why":"the definition tautologically repeats «проміжок часу» — pedagogical confirmed (Pass A P2)."},
 "SB-1563": {"ev":"Про медичну практику","why":"the definition begins with a «Про» noun construction and then uses feminine agreement instead of defining the adjective — confirmed."},
 "SB-0848": {"ev":"З, пов’язані з парламентом","why":"«З, пов’язані з парламентом» is a malformed fragment with number disagreement — confirmed."},
 "SB-1723": {"ev":"часто після «до»","why":"the usage note says analogous is followed by Ukrainian «до», obscuring the English pattern analogous to — pedagogical-accuracy defect confirmed."},
 "SB-1540": {"ev":"Щоб змінити форму або структуру","why":"«Щоб змінити форму або структуру» reads as a purpose clause rather than a definition — both passes agree P2."},
 "SB-0753": {"ev":"автобіографія; книга","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
 "SB-1481": {"ev":"у донаукові епохи","why":"singular technology is paired with plural ua «технології» — number-agreement confirmed (Pass A P2)."},
 "SB-0114": {"ev":"зроблена з держаків","why":"the definition reverses the dimensions and mistranslates staves as «держаки» — confirmed over Pass B's P2."},
 "SB-0026": {"ev":"інтенсивний; чутливий; різкий","why":"the definition starts with a lowercase letter, inconsistent with the learner UI sentence style — cosmetic P2, confirmed."},
 "SB-1155": {"ev":"виключно добре","why":"adverbial «виключно добре» does not agree with the adjective superb and is less idiomatic than «винятково добрий» — confirmed (Pass A P2)."},
 "SB-0087": {"ev":"з політичних мотивів","why":"the bare gloss «вбивство» loses the targeted, often political character of assassination — sense-coverage confirmed."},
 "SB-1678": {"ev":"Відкритий для багатьох інтерпретацій","why":"«багатьох інтерпретацій» overstates the sense; ambiguity requires more than one plausible meaning — confirmed (Pass A P2)."},
 "SB-0980": {"ev":"Регулювання чи відношення до нього","why":"the noun phrase contains the Russian-influenced «відношення до» and does not define the adjective regulatory — confirmed."},
 "SB-0084": {"ev":"Суцільні залишки пожежі","why":"«Суцільні залишки» means continuous remains, not the solid residue left after burning — semantic defect confirmed."},
 "SB-1545": {"ev":"Все, що зроблено","why":"plural compounds is defined with singular «Все, що» — number-agreement confirmed."},
 "SB-0290": {"ev":"Взаємний обмін люб'язністю","why":"«обмін люб’язністю» means exchange of courtesy and does not define correspondence — confirmed over Pass B's P2."},
 "SB-1327": {"ev":"виконання певної роботи або замовлення","why":"the word-family ua lists a noun and two verb senses, but the definition covers only an agreement — coverage confirmed."},
 "SB-0186": {"ev":"Стан громадянства; статус громадянина","why":"«Стан громадянства» is circular and does not explain the legal status of citizenship — confirmed (Pass A P2)."},
 "SB-0158": {"ev":"Зламати від внутрішнього тиску","why":"«Зламати від внутрішнього тиску» is transitive and does not match the intransitive лопнути/burst sense — confirmed."},
 "SB-0882": {"fd":"P2","conf":"medium","cat":"ua-definition-sense-mismatch","tgt":"ua","val":"портфель (інвестиційний)","ev":"Група інвестицій","why":"DIVERGENCE from Pass A (clean→P2): the definition «Група інвестицій та інших активів» is the finance sense, but the gloss «портфоліо» is the creative/works sense; standard Ukrainian finance uses «портфель» — Pass B's ua↔definition mismatch upheld."},
 "SB-1603": {"ev":"Відноситься до рівня національного уряду","why":"«Відноситься до» is a Russian-influenced calque — confirmed."},
 "SB-1223": {"ev":"передньому транспортному засобі","why":"«передній транспортний засіб» is a literal false rendering of the towing vehicle — confirmed."},
 "SB-1041": {"ev":"Розпорошені, розбиті на роз'єднані одиниці","why":"plural «Розпорошені, розбиті» does not agree with the singular adjective розкиданий — confirmed."},
 "SB-0478": {"ev":"на виключення будь-чого","why":"lowercase «на виключення» is an unidiomatic calque and the definition lacks terminal punctuation — confirmed."},
 "SB-1082": {"ev":"один для прийому шматка","why":"«особливо, один для прийому шматка» has invalid pronoun reference and unusable syntax — confirmed."},
 "SB-0320": {"ev":"Скептично ставиться","why":"the finite-verb phrase «Скептично ставиться» lacks a subject and does not directly define the adjective cynical — confirmed (Pass A P2)."},
 "SB-1777": {"ev":"також; крім того; теж","why":"the definition starts with a lowercase letter — cosmetic P2, confirmed."},
}
