# -*- coding: utf-8 -*-
"""Pass-B chunk 1 row-level judgments (hand-authored, blind).

One entry per manifest chunk-1 ID. Fields:
  disp  : P0 | P1 | P2 | clean-candidate
  conf  : high | medium | low
  why   : row-specific rationale (affirmative evidence for clean; defect note otherwise)
  flag  : letters of flagged axes (defects only): s n g p r c k d u
          s=semantic n=natural g=grammar p=pos r=register c=calque
          k=ua/def consistency d=pedagogical u=ui/formatting
  cat/target/value : defect category, proposed field (ua|definitionUa|both), proposed value
"""

JUDGMENTS = {
 "SB-0170": {"disp":"clean-candidate","conf":"high","why":"«каталог» is the standard equivalent of catalogue; definition correctly frames a complete, usually ordered list; noun POS matches."},
 "SB-0730": {"disp":"clean-candidate","conf":"medium","why":"mainstream rendered «мейнстрим; загальноприйнятий напрям» — accepted borrowing plus a native gloss; noun/adj senses both covered; def 'норма' fits."},
 "SB-0072": {"disp":"clean-candidate","conf":"high","why":"«аплодувати» is the exact verb for applaud; definition (approval by clapping) is accurate and idiomatic."},
 "SB-0939": {"disp":"clean-candidate","conf":"high","why":"province → «провінція»; definition names it an administrative division; examples (Canada, China) are apt; noun POS matches."},
 "SB-1640": {"disp":"P2","conf":"medium","flag":"gp","cat":"citation-form-morphology","target":"ua","value":"десятиліття","why":"decades glossed «десятиліть» is genitive plural ('of decades'); the citation form for a plural noun should be nominative «десятиліття»."},
 "SB-0668": {"disp":"clean-candidate","conf":"high","why":"«іронічно» matches ironically; adverb POS and manner definition are correct."},
 "SB-0575": {"disp":"clean-candidate","conf":"high","why":"haunt → «переслідувати»; definition covers both the ghost sense and 'frequent a place'; verb POS matches."},
 "SB-1238": {"disp":"clean-candidate","conf":"high","why":"trio → «тріо»; definition 'group of three' is exact; noun POS matches."},
 "SB-0033": {"disp":"clean-candidate","conf":"high","why":"administrator → «адміністратор»; definition covers one who manages/directs affairs across domains; noun POS correct."},
 "SB-0632": {"disp":"clean-candidate","conf":"high","why":"inspect → «оглядати»; definition (examine critically, look for problems) is accurate; verb POS matches."},
 "SB-0852": {"disp":"clean-candidate","conf":"medium","why":"passive → «пасивний»; definition 'undergo action without reaction' conveys the adjective sense adequately for a learner."},
 "SB-0880": {"disp":"clean-candidate","conf":"high","why":"pond → «ставок»; definition (small still inland water body, smaller than a lake) is precise; noun POS matches."},
 "SB-0161": {"disp":"clean-candidate","conf":"high","why":"canvas → «полотно»; definition (coarse hemp cloth for sails/tents or painting surface) is accurate and complete."},
 "SB-1700": {"disp":"clean-candidate","conf":"high","why":"infrastructure → «інфраструктура»; definition (facilities/services needed for a community) is correct; noun POS matches."},
 "SB-1181": {"disp":"clean-candidate","conf":"high","why":"tactic → «тактика»; definition (a maneuver toward a goal) is accurate; noun POS matches."},
 "SB-1513": {"disp":"clean-candidate","conf":"medium","why":"job → «робота»; definition «завдання.» is terse but gives a valid 'task' sense; lowercase start is trivial house-style, not misleading."},
 "SB-1487": {"disp":"clean-candidate","conf":"medium","why":"approximated → «наближений»; definition 'is calculated approximately' conveys the estimation sense; adjective/participle gloss acceptable."},
 "SB-0156": {"disp":"clean-candidate","conf":"medium","why":"bureaucracy → «бюрократія»; definition (government via bureaus and their officials) conveys the sense despite slightly literal phrasing."},
 "SB-0921": {"disp":"clean-candidate","conf":"high","why":"processor → «процесор»; definition covers computing and food-processor senses; noun POS matches."},
 "SB-0426": {"disp":"clean-candidate","conf":"high","why":"ego → «его»; definition ('the self, esp. with a sense of self-importance') is accurate; noun POS matches."},
 "SB-1575": {"disp":"clean-candidate","conf":"high","why":"rejected → «відхилено»; definition (rejected/not accepted after consideration) is accurate and consistent."},
 "SB-0967": {"disp":"clean-candidate","conf":"high","why":"rebellion → «повстання»; definition (armed resistance to established government) is accurate; noun POS matches."},
 "SB-0623": {"disp":"clean-candidate","conf":"high","why":"inherent → «властивий»; definition (naturally, as a part or consequence of something) captures the adjective sense."},
 "SB-1394": {"disp":"clean-candidate","conf":"high","why":"evaluation → «оцінка»; definition (appraisal, e.g. annual staff review) is accurate; noun POS matches."},
 "SB-1493": {"disp":"clean-candidate","conf":"high","why":"communication → «спілкування»; definition (exchange of data/information between entities) is accurate; noun POS matches."},
 "SB-0801": {"disp":"clean-candidate","conf":"high","why":"nod → «кивати»; definition (tilt head up-down to show agreement) is accurate; verb POS matches."},
 "SB-0636": {"disp":"clean-candidate","conf":"high","why":"institutional → «інституційний»; definition (of/relating to an institution) is accurate; adjective POS matches."},
 "SB-1680": {"disp":"clean-candidate","conf":"high","why":"automatically → «автоматично»; definition 'in an automatic manner' is correct; adverb POS matches."},
 "SB-1757": {"disp":"clean-candidate","conf":"high","why":"scenario → «сценарій»; definition (outline/model of an expected sequence of events) is accurate; noun POS matches."},
 "SB-1753": {"disp":"P2","conf":"medium","flag":"nd","cat":"weak-imprecise-definition","target":"definitionUa","value":"Контроль або стриманість; самовладання.","why":"restraints → «обмеження» is fine, but the definition «контроль або обережність; резерв» is weak and the gloss 'резерв' (reserve) does not fit restraint."},
 "SB-0265": {"disp":"clean-candidate","conf":"high","why":"contempt → «презирство»; definition (feeling of someone/something as inferior or worthless) is accurate; noun POS matches."},
 "SB-0413": {"disp":"clean-candidate","conf":"high","why":"dual → «подвійний»; definition (having two, usually equivalent, components) is accurate; adjective POS matches."},
 "SB-0688": {"disp":"clean-candidate","conf":"high","why":"lawsuit → «позов»; definition (civil case brought to court to resolve a disagreement) is accurate; noun POS matches."},
 "SB-1102": {"disp":"clean-candidate","conf":"high","why":"spectacle → «видовище»; definition (striking or extraordinary scene/display/performance) is accurate; noun POS matches."},
 "SB-0344": {"disp":"clean-candidate","conf":"high","why":"denounce → «засуджувати»; definition (publicly and firmly condemn) is accurate; verb POS matches."},
 "SB-1026": {"disp":"clean-candidate","conf":"high","why":"ritual → «ритуал»; definition (a rite; repeated set of actions, esp. religious) is accurate; lowercase start is trivial."},
 "SB-0083": {"disp":"clean-candidate","conf":"medium","why":"articulate (v) → «артикулювати» with definition 'speak clearly; enunciate' — acceptable, though «чітко висловлювати» would also capture the 'express ideas' sense."},
 "SB-1744": {"disp":"clean-candidate","conf":"high","why":"mediation → «посередництво»; definition (negotiation to resolve differences by an impartial party) is accurate; noun POS matches."},
 "SB-1614": {"disp":"clean-candidate","conf":"high","why":"instructions → «інструкції»; definition (directions explaining what/how to do) is accurate; plural noun POS matches."},
 "SB-0919": {"disp":"clean-candidate","conf":"medium","why":"proceeds → «доходи»; definition 'income; gross income' captures the money-received sense; plural noun POS matches."},
 "SB-1677": {"disp":"clean-candidate","conf":"high","why":"accompanied → «у супроводі»; definition (being escorted; part of a group of at least two) is accurate and consistent."},
 "SB-0883": {"disp":"clean-candidate","conf":"high","why":"portray → «зображувати»; definition (play a role; depict a character/situation) is accurate; verb POS matches."},
 "SB-1037": {"disp":"clean-candidate","conf":"high","why":"saint → «святий»; definition (deceased person recognised as holy by a church) is accurate; noun POS matches."},
 "SB-0762": {"disp":"clean-candidate","conf":"high","why":"merit → «заслуга»; definition (something deserving positive recognition or reward) is accurate; noun POS matches."},
 "SB-0972": {"disp":"clean-candidate","conf":"medium","why":"reflection → «відображення»; definition (act/state of reflecting) covers the mirror/optical sense correctly; contemplation sense is a separate entry concern."},
 "SB-1714": {"disp":"clean-candidate","conf":"high","why":"termination → «припинення»; definition (process/state of terminating) is accurate; noun POS matches."},
 "SB-0593": {"disp":"clean-candidate","conf":"high","why":"hydrogen → «водень»; definition (lightest element, H, atomic number 1) is factually correct; noun POS matches."},
 "SB-0146": {"disp":"clean-candidate","conf":"high","why":"breakthrough → «прорив»; definition (major advance/innovation overcoming an obstacle) is accurate; noun POS matches."},
 "SB-1176": {"disp":"clean-candidate","conf":"high","why":"symbolic → «символічний»; definition (indirect representation of/reference to another thing) is accurate; adjective POS matches."},
 "SB-1324": {"disp":"clean-candidate","conf":"high","why":"concept → «поняття; концепція»; definition (abstract, general idea) is accurate; noun POS matches with a good native+borrowed pair."},
 "SB-1095": {"disp":"clean-candidate","conf":"high","why":"spam → «спам»; definition (unwanted bulk electronic messages) is accurate; noun POS matches."},
 "SB-1472": {"disp":"clean-candidate","conf":"high","why":"scheme → «схема»; definition (systematic plan of future action) is accurate; noun POS matches."},
 "SB-1465": {"disp":"clean-candidate","conf":"high","why":"physical → «фізичний»; definition (of the material world perceived by senses) is accurate; adjective POS matches."},
 "SB-1701": {"disp":"clean-candidate","conf":"high","why":"minimised → «зведений до мінімуму»; definition (reduced to the lowest possible level/amount) is accurate and consistent."},
 "SB-0152": {"disp":"clean-candidate","conf":"high","why":"buddy → «приятель»; definition (a friend or casual acquaintance) is accurate; register matches the informal headword; noun POS correct."},
 "SB-0789": {"disp":"clean-candidate","conf":"high","why":"municipal → «муніципальний»; definition (of/related to a municipality) is accurate; adjective POS matches."},
 "SB-0139": {"disp":"clean-candidate","conf":"high","why":"bonus → «бонус»; definition (something extra that is good; an added benefit) is accurate; noun POS matches."},
 "SB-0827": {"disp":"clean-candidate","conf":"high","why":"optimism → «оптимізм»; definition (tendency to expect the best/favourable outcome) is accurate; lowercase/no-period is trivial house-style."},
 "SB-0981": {"disp":"clean-candidate","conf":"medium","why":"rehabilitation → «реабілітація»; definition restates the cognate ('process of rehabilitating') — thin but not misleading for a direct cognate."},
 "SB-0066": {"disp":"clean-candidate","conf":"high","why":"anchor → «якір»; definition (device to moor a vessel to the seabed against movement) is accurate; noun POS matches."},
 "SB-0025": {"disp":"clean-candidate","conf":"high","why":"activist → «активіст»; definition (politically active citizen fighting for change) is accurate; noun POS matches."},
 "SB-1177": {"disp":"clean-candidate","conf":"high","why":"syndrome → «синдром»; definition (recognisable pattern of signs/symptoms, esp. of a condition) is accurate; noun POS matches."},
 "SB-0582": {"disp":"clean-candidate","conf":"high","why":"homeland → «батьківщина»; definition (the country one regards as home) is accurate; noun POS matches."},
 "SB-1777": {"disp":"clean-candidate","conf":"high","why":"likewise → «так само»; definition (also; moreover; too) is accurate; adverb sense matches; lowercase trivial."},
 "SB-0394": {"disp":"clean-candidate","conf":"high","why":"disruption → «порушення»; definition (interruption of a regular flow/sequence) is accurate; noun POS matches."},
 "SB-0642": {"disp":"clean-candidate","conf":"high","why":"intake → «споживання»; definition (the amount taken in) fits the consumption sense; noun POS matches."},
 "SB-1778": {"disp":"clean-candidate","conf":"high","why":"notwithstanding → «незважаючи на це»; definition (nevertheless, all the same) is accurate; lowercase trivial."},
 "SB-0550": {"disp":"clean-candidate","conf":"high","why":"grave → «могила»; definition (place in the ground where a dead person is buried) is accurate; the headword's disambiguation matches; noun POS correct."},
 "SB-1593": {"disp":"clean-candidate","conf":"high","why":"brief → «короткий»; definition (short-lived; happening quickly) is accurate for the adjective sense."},
 "SB-0865": {"disp":"P2","conf":"high","flag":"u","cat":"truncated-definition","target":"definitionUa","value":"Офіційний письмовий запит, зроблений окремою особою чи групою людей до суверенної чи політичної влади, який часто містить багато підписів, із проханням про якусь благодать, право, милосердя або виправлення якоїсь кривди.","why":"petition definition is truncated mid-clause, ending in a dangling «кривди чи...»; the gloss «петиція» is correct but the learner sees an unfinished sentence."},
 "SB-0574": {"disp":"clean-candidate","conf":"high","why":"hatred → «ненависть»; definition (strong aversion; intense dislike) is accurate; noun POS matches."},
 "SB-1356": {"disp":"clean-candidate","conf":"high","why":"policy → «політика; стратегічний курс»; definition (principle of conduct adopted by a government/organisation) is accurate; noun POS matches."},
 "SB-1185": {"disp":"clean-candidate","conf":"high","why":"tenant → «орендар»; definition (one who holds a lease/rental) is accurate; noun POS matches."},
 "SB-1645": {"disp":"clean-candidate","conf":"high","why":"equipment → «обладнання»; definition (items used to equip something/someone) is accurate; noun POS matches."},
 "SB-0377": {"disp":"clean-candidate","conf":"high","why":"diplomat → «дипломат»; definition (accredited official representing a government abroad) is accurate; missing terminal period is trivial."},
 "SB-0341": {"disp":"clean-candidate","conf":"high","why":"delicate → «делікатний»; definition (easily damaged; needing careful handling) is accurate; adjective POS matches."},
 "SB-0302": {"disp":"clean-candidate","conf":"high","why":"coup → «переворот»; definition (a coup d'etat) is accurate; noun POS matches."},
 "SB-1341": {"disp":"clean-candidate","conf":"high","why":"function → «функція; функціонувати»; definition (what something does/is used for) is accurate; noun+verb pair matches the word family."},
 "SB-0311": {"disp":"clean-candidate","conf":"high","why":"crown → «корона»; definition (royal/imperial/princely headdress; diadem) is accurate; noun POS matches."},
 "SB-0250": {"disp":"clean-candidate","conf":"high","why":"conscience → «совість»; definition (moral sense of right and wrong affecting one's conduct) is accurate; noun POS matches."},
 "SB-0794": {"disp":"clean-candidate","conf":"high","why":"neglect → «нехтувати»; definition (fail to care for or pay attention) is accurate for the verb sense; POS covers v.,n."},
 "SB-1385": {"disp":"clean-candidate","conf":"high","why":"conclusion → «висновок»; definition (the end, closing, or last part of something) is accurate; noun POS matches."},
 "SB-0602": {"disp":"clean-candidate","conf":"high","why":"implementation → «впровадження»; definition (bringing an idea from concept to reality) is accurate; noun POS matches."},
 "SB-1162": {"disp":"clean-candidate","conf":"high","why":"supposedly → «нібито»; definition (as a matter of supposition; according to some claims) is accurate; adverb POS matches."},
 "SB-0848": {"disp":"clean-candidate","conf":"high","why":"parliamentary → «парламентський»; definition (of/relating to or enacted by a parliament) is accurate; adjective POS matches."},
 "SB-0527": {"disp":"clean-candidate","conf":"high","why":"fragile → «крихкий»; definition (easily broken; not strong; of delicate material) is accurate; adjective POS matches."},
 "SB-0092": {"disp":"clean-candidate","conf":"high","why":"assertion → «твердження»; definition (act of asserting; a positive declaration) is accurate; noun POS matches."},
 "SB-0662": {"disp":"clean-candidate","conf":"high","why":"intriguing → «інтригуючий»; definition (arousing a desire to know more; mysterious) is accurate; adjective POS matches."},
 "SB-0275": {"disp":"clean-candidate","conf":"medium","why":"conversion → «перетворення»; definition restates the cognate ('act of converting') — thin but not misleading; noun POS matches."},
 "SB-1518": {"disp":"clean-candidate","conf":"high","why":"option → «варіант»; definition (one of a set of choices) is accurate; noun POS matches."},
 "SB-1232": {"disp":"clean-candidate","conf":"high","why":"treaty → «договір»; definition (formal binding agreement between states/international bodies) is accurate; noun POS matches."},
 "SB-0784": {"disp":"clean-candidate","conf":"high","why":"monk → «чернець»; definition (male member of a monastic order devoted to religious service) is accurate; noun POS matches."},
 "SB-1100": {"disp":"clean-candidate","conf":"high","why":"specification → «специфікація»; definition (clear set of requirements to be satisfied) is accurate; noun POS matches."},
 "SB-0515": {"disp":"clean-candidate","conf":"high","why":"flesh → «плоть»; definition (soft body tissues, esp. muscle and fat) is accurate; noun POS matches."},
 "SB-1051": {"disp":"clean-candidate","conf":"high","why":"seldom → «рідко»; definition (infrequently, rarely) is accurate; adverb POS matches."},
 "SB-0162": {"disp":"clean-candidate","conf":"high","why":"capability → «здатність»; definition (power or ability to produce a result) is accurate; noun POS matches."},
 "SB-0069": {"disp":"clean-candidate","conf":"high","why":"apparatus → «апарат»; definition (the means by which a production is made or a task performed) is accurate; noun POS matches."},
 "SB-1329": {"disp":"clean-candidate","conf":"high","why":"data → «дані»; definition (recorded material accepted as facts, basis for reasoning/computation) is accurate; plural noun POS matches."},
 "SB-1234": {"disp":"clean-candidate","conf":"high","why":"tribal → «племінний»; definition (relating to tribes) is accurate; adjective POS matches."},
 "SB-1547": {"disp":"clean-candidate","conf":"high","why":"contact → «контакт»; definition (the establishing of a connection with) is accurate; noun POS matches."},
 "SB-1618": {"disp":"clean-candidate","conf":"high","why":"minimum → «мінімум»; definition (the smallest amount) is accurate; noun POS matches."},
 "SB-0799": {"disp":"clean-candidate","conf":"medium","why":"niche → «ніша»; definition (a position of opportunity one is well suited to, e.g. a market) captures the figurative business sense; noun POS matches."},
 "SB-1637": {"disp":"clean-candidate","conf":"high","why":"confirmed → «підтверджено»; definition (verified or ratified) is accurate and consistent."},
 "SB-1350": {"disp":"clean-candidate","conf":"high","why":"legal → «правовий; юридичний»; definition (relating to law or lawyers) is accurate; adjective POS matches with a good pair."},
 "SB-0970": {"disp":"clean-candidate","conf":"high","why":"recount → «докладно розповідати; переказувати»; definition (narrate an event in detail) is accurate; verb POS matches; the '1' suffix is a homograph disambiguator."},
 "SB-0113": {"disp":"clean-candidate","conf":"high","why":"bare → «голий»; definition (naked, uncovered) is accurate; adjective POS matches."},
 "SB-1628": {"disp":"clean-candidate","conf":"medium","why":"tapes → «стрічки»; definition (flexible material in a roll with an adhesive surface; sticky tape) fits one sense of tape; plural noun POS matches."},
 "SB-0807": {"disp":"clean-candidate","conf":"high","why":"nonsense → «нісенітниця»; definition (something foolish, illogical, meaningless) is accurate; noun POS matches."},
 "SB-0030": {"disp":"clean-candidate","conf":"high","why":"adjustment → «коригування»; definition (the act of adjusting something) is accurate; noun POS matches; missing period trivial."},
 "SB-0658": {"disp":"clean-candidate","conf":"high","why":"intermediate → «проміжний»; definition (lying between two extremes / mid-range) is accurate; adjective POS matches."},
 "SB-1734": {"disp":"clean-candidate","conf":"high","why":"device → «пристрій»; definition (any equipment made for a particular purpose, esp. mechanical/electrical) is accurate; noun POS matches."},
 "SB-1660": {"disp":"clean-candidate","conf":"high","why":"paradigm → «парадигма»; definition (a pattern/model; esp. a way of thinking or conceptual framework) is accurate; noun POS matches."},
 "SB-1384": {"disp":"clean-candidate","conf":"high","why":"computer → «комп'ютер»; definition (programmable electronic device performing calculations/logic) is accurate; trailing semicolon is trivial formatting."},
 "SB-1094": {"disp":"clean-candidate","conf":"high","why":"sovereignty → «суверенітет»; definition (state able to control resources and govern itself without coercion) is accurate; noun POS matches."},
 "SB-0268": {"disp":"clean-candidate","conf":"high","why":"content (adj) → «задоволений»; definition (satisfied with what one has, not needing more) is accurate; the '2' disambiguates from the noun; adjective POS matches."},
 "SB-0692": {"disp":"clean-candidate","conf":"high","why":"legacy → «спадок»; definition (something inherited from a predecessor or the past) is accurate; noun POS matches."},
 "SB-0215": {"disp":"clean-candidate","conf":"high","why":"companion → «компаньйон»; definition (a friend, acquaintance or partner one spends time with) is accurate; noun POS matches."},
 "SB-1546": {"disp":"clean-candidate","conf":"high","why":"conflict → «конфлікт»; definition (a clash or disagreement, often violent, between opposing parties) is accurate; noun POS matches."},
 "SB-1485": {"disp":"clean-candidate","conf":"high","why":"annual → «річний»; definition (occurring once a year) is accurate; adjective POS matches."},
 "SB-1377": {"disp":"clean-candidate","conf":"high","why":"aspects → «аспекти»; definition (any particular feature, part or element of something) is accurate; plural noun POS matches."},
 "SB-1016": {"disp":"clean-candidate","conf":"high","why":"revelation → «одкровення»; definition (the act of revealing or disclosing) is accurate; noun POS matches."},
 "SB-0859": {"disp":"clean-candidate","conf":"high","why":"peak → «пік»; definition (the highest value reached by a quantity over a period) is accurate and IELTS-relevant; noun POS matches."},
 "SB-1758": {"disp":"clean-candidate","conf":"high","why":"subordinate → «підлеглий»; definition (placed in a lower class, rank or position) is accurate; POS matches."},
 "SB-0020": {"disp":"clean-candidate","conf":"high","why":"accused → «обвинувачений»; definition (a person charged with an offence; defendant) is accurate; noun POS matches."},
 "SB-0008": {"disp":"clean-candidate","conf":"high","why":"academy → «академія»; definition (an institution of higher learning) is accurate; noun POS matches."},
 "SB-1524": {"disp":"P2","conf":"medium","flag":"pg","cat":"citation-form-morphology","target":"both","value":"передбачений; передбачено — Відомий або визначений заздалегідь.","why":"predicted glossed «передбачив» is a 3sg masculine past-tense verb, an odd citation for a participle/word-family entry; definition «відомо заздалегідь» is a lowercase fragment."},
 "SB-0434": {"disp":"clean-candidate","conf":"high","why":"embassy → «посольство»; definition (officials permanently representing a state in another state) is accurate; noun POS matches."},
 "SB-0086": {"disp":"clean-candidate","conf":"high","why":"aspire → «прагнути»; definition (to have a strong desire or ambition to achieve something) is accurate; verb POS matches."},
 "SB-0634": {"disp":"clean-candidate","conf":"high","why":"inspiration → «натхнення»; definition (process of stimulating the intellect, emotions or creativity) is accurate; noun POS matches."},
 "SB-0629": {"disp":"clean-candidate","conf":"high","why":"inmate → «в'язень»; definition (a person confined in an institution such as a prison or hospital) is accurate; noun POS matches."},
 "SB-0811": {"disp":"clean-candidate","conf":"high","why":"notify → «повідомляти»; definition (to inform someone of an event) is accurate; verb POS matches."},
 "SB-1711": {"disp":"clean-candidate","conf":"high","why":"revision → «перегляд»; definition (act/process of reviewing, editing and changing) is accurate; noun POS matches."},
 "SB-0920": {"disp":"clean-candidate","conf":"high","why":"processing → «обробка»; definition (searching, storing, classifying and transmitting data, esp. by computer) is accurate; noun POS matches."},
 "SB-0012": {"disp":"clean-candidate","conf":"high","why":"accomplishment → «досягнення»; definition (something achieved; an achievement) is accurate; noun POS matches."},
 "SB-1166": {"disp":"clean-candidate","conf":"high","why":"surgical → «хірургічний»; definition (relating to or used during surgery) is accurate; adjective POS matches."},
 "SB-1123": {"disp":"clean-candidate","conf":"high","why":"stimulus → «стимул»; definition (external phenomenon prompting a response or change) is accurate; noun POS matches."},
 "SB-0373": {"disp":"clean-candidate","conf":"high","why":"dilemma → «дилема»; definition (a choice between two or more equally undesirable alternatives) is accurate; noun POS matches."},
 "SB-0015": {"disp":"clean-candidate","conf":"high","why":"accountability → «підзвітність»; definition (state of being accountable; obligation to answer for something) is accurate; noun POS matches."},
 "SB-0267": {"disp":"clean-candidate","conf":"high","why":"contender → «претендент»; definition (someone who competes with one or more others) is accurate; noun POS matches."},
 "SB-1304": {"disp":"clean-candidate","conf":"high","why":"width → «ширина»; definition (measurement of something from side to side) is accurate; noun POS matches."},
 "SB-1650": {"disp":"clean-candidate","conf":"high","why":"grade → «клас»; definition (result of a test expressed as a number/letter; a mark) is accurate; noun POS matches."},
 "SB-0560": {"disp":"clean-candidate","conf":"high","why":"guidance → «керівництво»; definition (advice or counsel on a subject) is accurate; noun POS matches."},
 "SB-0753": {"disp":"clean-candidate","conf":"high","why":"memoir → «мемуари»; definition (autobiography; a book describing the author's personal experience) is accurate; lowercase start trivial."},
 "SB-0860": {"disp":"P2","conf":"high","flag":"u","cat":"truncated-definition","target":"definitionUa","value":"Член нижчого соціального класу, який працює на землі: дрібні фермери, орендарі, пайовики та батраки, що утворюють основну робочу силу в сільському господарстві та садівництві.","why":"peasant definition is truncated mid-word, ending «...та садівни...»; the gloss «селянин» is correct but the learner sees a broken word."},
 "SB-1615": {"disp":"clean-candidate","conf":"high","why":"intelligence → «інтелект»; definition (capacity of the mind to understand and apply knowledge) is accurate; trailing semicolon trivial."},
 "SB-1565": {"disp":"P2","conf":"medium","flag":"d","cat":"circular-restatement-definition","target":"definitionUa","value":"Змінений або частково скоригований без повної заміни.","why":"modified → «змінений» is fine, but the definition «змінений; змінено» merely restates the headword forms and teaches nothing."},
 "SB-0917": {"disp":"P2","conf":"high","flag":"u","cat":"dangling-punctuation","target":"definitionUa","value":"Постановка проблеми; такий, що має проблему або спричиняє її.","why":"problematic definition ends with a dangling colon «...проблеми(-й):» with no following text; content otherwise conveys the sense."},
 "SB-0842": {"disp":"clean-candidate","conf":"medium","why":"overwhelm → «переповнювати»; definition 'emotionally overcome' fits the emotional-overwhelm sense; verb POS matches."},
 "SB-0579": {"disp":"clean-candidate","conf":"high","why":"hierarchy → «ієрархія»; definition (system in which people/groups rank above others by status/authority) is accurate; noun POS matches."},
 "SB-0094": {"disp":"clean-candidate","conf":"high","why":"asylum → «притулок»; definition (a place of safety or refuge) is accurate; noun POS matches."},
 "SB-0589": {"disp":"clean-candidate","conf":"medium","why":"hostility → «ворожість»; definition restates the cognate ('state of hostility') — thin but not misleading; noun POS matches."},
 "SB-1619": {"disp":"clean-candidate","conf":"high","why":"motivation → «мотивація»; definition (an incentive or reason to do something) is accurate; noun POS matches."},
 "SB-1527": {"disp":"clean-candidate","conf":"high","why":"project → «проект»; definition (a planned undertaking with a specific goal carried out in stages) is accurate; noun POS matches."},
 "SB-0123": {"disp":"clean-candidate","conf":"high","why":"bench → «лава»; definition (a long seat with or without a back, e.g. in parks and schools) is accurate; noun POS matches."},
 "SB-1603": {"disp":"clean-candidate","conf":"high","why":"federal → «федеральний»; definition (of the national-government level in a federation, vs state/province) is accurate; adjective POS matches."},
 "SB-0206": {"disp":"clean-candidate","conf":"high","why":"columnist → «колумніст»; definition (a regular writer of a column in a magazine or newspaper) is accurate; noun POS matches."},
 "SB-0546": {"disp":"clean-candidate","conf":"high","why":"glory → «слава»; definition (honour, admiration or distinction by common consent; high reputation) is accurate; noun POS matches."},
 "SB-1740": {"disp":"clean-candidate","conf":"high","why":"format → «формат»; definition (the layout of a publication or document) is accurate; noun POS matches."},
 "SB-0278": {"disp":"clean-candidate","conf":"high","why":"cooperate → «співпрацювати»; definition (to work or act together for a common purpose) is accurate; verb POS matches."},
 "SB-0771": {"disp":"clean-candidate","conf":"high","why":"mining → «видобуток»; definition (extracting valuable resources, often minerals, from the earth) is accurate; noun POS matches."},
 "SB-0422": {"disp":"clean-candidate","conf":"high","why":"ecological → «екологічний»; definition (relating to ecology, the relations of organisms and environment) is accurate; adjective POS matches."},
 "SB-1530": {"disp":"clean-candidate","conf":"medium","why":"retained → «зберігається»; definition (continues in your keeping, use or memory) conveys the sense; lowercase/no-period trivial."},
 "SB-0403": {"disp":"clean-candidate","conf":"high","why":"doctrine → «доктрина»; definition (body of teachings of an ideology/religion or leader) is accurate; noun POS matches."},
 "SB-0925": {"disp":"clean-candidate","conf":"high","why":"profitable → «прибутковий»; definition (yielding profit) is accurate; adjective POS matches."},
 "SB-0906": {"disp":"clean-candidate","conf":"high","why":"prestigious → «престижний»; definition (of high prestige) is accurate; adjective POS matches."},
 "SB-1405": {"disp":"clean-candidate","conf":"high","why":"obtained → «отримано»; definition (received, gained or acquired in some way) is accurate and consistent."},
 "SB-0140": {"disp":"clean-candidate","conf":"medium","why":"boom → «бум»; definition (a low resonant sound, e.g. an explosion) selects the sound sense, and the gloss «бум» is consistent with that reading."},
 "SB-1310": {"disp":"clean-candidate","conf":"high","why":"worship → «поклоніння»; definition (to honour a deity with reverence; perform religious devotions) is accurate; noun/verb POS matches."},
 "SB-0720": {"disp":"clean-candidate","conf":"high","why":"long-time → «давній»; definition (existing or performing a role for a long time) is accurate; adjective POS matches."},
 "SB-0911": {"disp":"clean-candidate","conf":"high","why":"prevention → «профілактика»; definition (measures to limit health risks: campaigns, vaccination, early diagnosis) is accurate; noun POS matches."},
 "SB-0110": {"disp":"clean-candidate","conf":"high","why":"bail → «застава»; definition (security, usually money, exchanged for an arrested person's release pending trial) is accurate; noun POS matches."},
 "SB-1442": {"disp":"clean-candidate","conf":"high","why":"demonstrate → «продемонструвати»; definition (to show, present, or make evident; to prove) is accurate; verb POS matches."},
 "SB-1192": {"disp":"clean-candidate","conf":"high","why":"testify → «свідчити»; definition (to make a statement or give evidence under oath) is accurate; verb POS matches."},
 "SB-0294": {"disp":"clean-candidate","conf":"high","why":"corruption → «корупція»; definition (unethical practice incl. bribery, conflict of interest, nepotism) is accurate; noun POS matches."},
 "SB-0586": {"disp":"clean-candidate","conf":"high","why":"horn → «ріг»; definition (hard keratin growth projecting from the head of certain animals) is accurate; noun POS matches."},
 "SB-1652": {"disp":"clean-candidate","conf":"high","why":"hierarchical → «ієрархічний»; definition (relating to a hierarchy) is accurate; adjective POS matches."},
 "SB-1772": {"disp":"clean-candidate","conf":"high","why":"enormous → «величезний»; definition (extremely large, far exceeding usual size) is accurate; adjective POS matches."},
 "SB-0271": {"disp":"clean-candidate","conf":"high","why":"contractor → «підрядник»; definition (a person/company that builds or improves structures) is accurate; noun POS matches."},
 "SB-0626": {"disp":"clean-candidate","conf":"high","why":"inject → «вводити»; definition (to make an injection, esp. of medicine or drugs) is accurate; verb POS matches."},
 "SB-0519": {"disp":"clean-candidate","conf":"medium","why":"footage → «кадри»; definition (the amount of film/tape used to record something) conveys the sense; noun POS matches."},
 "SB-0233": {"disp":"clean-candidate","conf":"high","why":"conceal → «приховувати»; definition (hide from sight or general knowledge; keep secret) is accurate; verb POS matches."},
 "SB-1388": {"disp":"clean-candidate","conf":"medium","why":"construction → «будівництво»; definition (the process of constructing) is thin/near-circular but not misleading; noun POS matches."},
 "SB-1073": {"disp":"clean-candidate","conf":"high","why":"simultaneously → «одночасно»; definition (happening at the same time) is accurate; adverb POS matches."},
 "SB-0290": {"disp":"P2","conf":"medium","flag":"nd","cat":"imprecise-definition","target":"definitionUa","value":"Обмін листами; спілкування між людьми за допомогою листів.","why":"correspondence gloss «листування» is correct, but the definition opens with «взаємний обмін люб'язністю» (exchange of courtesy), an imprecise/odd rendering of 'exchange of communication'."},
 "SB-1273": {"disp":"clean-candidate","conf":"medium","why":"vessel → «судно»; definition (a craft for travel over water, air or space) selects the craft sense, consistent with the gloss; noun POS matches."},
 "SB-0545": {"disp":"clean-candidate","conf":"high","why":"glorious → «славний»; definition (showing attributes worthy of or receiving glory) is accurate; adjective POS matches."},
 "SB-1516": {"disp":"clean-candidate","conf":"medium","why":"obvious → «очевидний»; definition (easy to discover, see or understand; self-evident) conveys the sense; adjective POS matches."},
 "SB-0755": {"disp":"clean-candidate","conf":"high","why":"mentor → «ментор»; definition (a wise and trusted adviser or teacher) is accurate; «наставник» would also fit; noun POS matches."},
 "SB-1217": {"disp":"clean-candidate","conf":"high","why":"toss → «кинути»; definition (throw with an initial upward direction) is accurate; verb POS matches."},
 "SB-0386": {"disp":"clean-candidate","conf":"medium","why":"discretion → «розсуд»; definition (ability to make wise choices or decisions) captures the judgment sense consistent with the gloss; noun POS matches."},
 "SB-0312": {"disp":"clean-candidate","conf":"high","why":"crude → «сирий»; definition (in a natural, unprocessed state) fits the crude-oil sense; adjective POS matches."},
 "SB-1224": {"disp":"clean-candidate","conf":"high","why":"transaction → «транзакція»; definition (an exchange or trade of ideas, money, goods) is accurate; noun POS matches."},
 "SB-0788": {"disp":"clean-candidate","conf":"high","why":"motorist → «автомобіліст»; definition (one who drives a vehicle) is accurate; noun POS matches."},
 "SB-0232": {"disp":"clean-candidate","conf":"high","why":"compute → «обчислювати»; definition (to count, calculate) is accurate; verb POS matches."},
 "SB-0101": {"disp":"clean-candidate","conf":"high","why":"authentic → «справжній»; definition (of the same origin as claimed; genuine) is accurate; adjective POS matches."},
 "SB-0760": {"disp":"clean-candidate","conf":"medium","why":"merge → «злити»; definition (to combine into a whole) is accurate for the combining sense; verb POS matches."},
 "SB-1240": {"disp":"clean-candidate","conf":"high","why":"trophy → «трофей»; definition (an object awarded for success in competition or to mark an achievement) is accurate; noun POS matches."},
 "SB-0770": {"disp":"clean-candidate","conf":"medium","why":"minimize → «мінімізувати»; definition (to make something as small as possible; reduce) is accurate; verb POS matches."},
 "SB-0990": {"disp":"clean-candidate","conf":"high","why":"reminder → «нагадування»; definition (someone or something that reminds) is accurate; noun POS matches."},
 "SB-0723": {"disp":"clean-candidate","conf":"high","why":"loyalty → «вірність»; definition (faithfulness or devotion to a person, cause or nation) is accurate; noun POS matches."},
 "SB-0649": {"disp":"clean-candidate","conf":"medium","why":"intensity → «інтенсивність»; definition restates the cognate ('quality of being intense') — thin but not misleading; noun POS matches."},
 "SB-0345": {"disp":"clean-candidate","conf":"high","why":"dense → «щільний»; definition (having relatively high density) is accurate; adjective POS matches."},
 "SB-0468": {"disp":"clean-candidate","conf":"high","why":"eternal → «вічний»; definition (lasting forever; endless) is accurate; adjective POS matches."},
 "SB-0048": {"disp":"clean-candidate","conf":"medium","why":"align → «вирівняти»; definition (to bring into a line or into agreement) conveys the sense; verb POS matches."},
 "SB-1099": {"disp":"clean-candidate","conf":"high","why":"specialized → «спеціалізований»; definition (highly skilled in or specially adapted to a particular field) is accurate; adjective POS matches."},
 "SB-0245": {"disp":"clean-candidate","conf":"high","why":"confrontation → «конфронтація»; definition (the act of confronting or challenging another, esp. face to face) is accurate; noun POS matches."},
 "SB-1452": {"disp":"P2","conf":"medium","flag":"gn","cat":"grammatical-agreement-error","target":"definitionUa","value":"Мається на увазі без прямого висловлення; натякається.","why":"implies definition «Пропонується без прямого вказівки...» has a gender/case agreement error («прямого вказівки» should be «прямої вказівки»); phrasing is also awkward."},
 "SB-0996": {"disp":"clean-candidate","conf":"high","why":"replacement → «заміна»; definition (a person or thing taking the place of another; a substitute) is accurate; noun POS matches."},
 "SB-0183": {"disp":"clean-candidate","conf":"high","why":"chunk → «шматок»; definition (a large or significant part of something) is accurate; noun POS matches."},
 "SB-1642": {"disp":"clean-candidate","conf":"high","why":"deny → «заперечувати»; definition (to assert that something is untrue) is accurate; verb POS matches."},
 "SB-1451": {"disp":"clean-candidate","conf":"high","why":"immigration → «імміграція»; definition (moving to or entering a country not one's own for permanent residence) is accurate; noun POS matches."},
 "SB-1062": {"disp":"clean-candidate","conf":"high","why":"shareholder → «акціонер»; definition (one who owns shares in a corporation) is accurate; noun POS matches."},
 "SB-0437": {"disp":"P2","conf":"medium","flag":"sd","cat":"wrong-sense-in-definition","target":"definitionUa","value":"Акт піднімання в поле зору; вихід із приховування; поява.","why":"emergence gloss «поява» is correct, but the definition ends with «зовнішній вигляд» (physical looks), a wrong reading of the polysemous 'appearance' (coming into view)."},
 "SB-1022": {"disp":"clean-candidate","conf":"high","why":"rhetoric → «риторика»; definition (the art of using language, esp. public speaking, to persuade) is accurate; noun POS matches."},
 "SB-1082": {"disp":"clean-candidate","conf":"medium","why":"slot → «слот»; definition (a narrow recess, perforation or opening to receive a fitting piece) is accurate; noun POS matches."},
 "SB-0630": {"disp":"clean-candidate","conf":"medium","why":"insertion → «вставка»; definition (the act of inserting or something inserted) is near-circular but not misleading; noun POS matches."},
 "SB-0542": {"disp":"clean-candidate","conf":"high","why":"genocide → «геноцид»; definition (systematic, deliberate destruction of a group by ethnicity/religion/nationality) is accurate; noun POS matches."},
 "SB-1137": {"disp":"P2","conf":"medium","flag":"g","cat":"grammatical-case-error","target":"definitionUa","value":"Акт подання або надання, наприклад завершеної роботи.","why":"submission definition «...надання напр. завершена робота» has a case error («завершена робота» should be genitive «завершеної роботи») and an unexpanded abbreviation."},
 "SB-0689": {"disp":"clean-candidate","conf":"high","why":"layout → «макет»; definition (a structured arrangement of elements within given bounds) is accurate; noun POS matches."},
 "SB-0633": {"disp":"clean-candidate","conf":"high","why":"inspection → «огляд»; definition (the act of examining something, often closely) is accurate; noun POS matches."},
 "SB-0812": {"disp":"clean-candidate","conf":"high","why":"notorious → «горезвісний»; definition (widely known for something negative; infamous) is accurate; adjective POS matches."},
 "SB-0289": {"disp":"clean-candidate","conf":"high","why":"correspond → «відповідати»; definition (to be equivalent or similar in nature, quantity, quality, structure or function) is accurate; verb POS matches."},
 "SB-0846": {"disp":"clean-candidate","conf":"medium","why":"parental → «батьківський»; definition (relating to a parent) is accurate; adjective POS matches."},
 "SB-0514": {"disp":"clean-candidate","conf":"high","why":"fleet → «флот»; definition (a group of ships or vehicles) is accurate; noun POS matches."},
 "SB-1708": {"disp":"clean-candidate","conf":"high","why":"random → «випадковий»; definition (occurring without a particular cause; chance, unpredictable) is accurate; adjective POS matches."},
 "SB-1381": {"disp":"clean-candidate","conf":"medium","why":"commission → «комісія»; definition (the fee charged by an agent or broker for a transaction) selects the fee sense, which «комісія» covers; noun POS matches."},
 "SB-0524": {"disp":"clean-candidate","conf":"high","why":"forth → «вперед»; definition (outward, forward or away from a place; mostly in set expressions) is accurate; adverb POS matches."},
 "SB-1085": {"disp":"clean-candidate","conf":"medium","why":"soak → «замочити»; definition (to become saturated with liquid by immersion) conveys the sense; verb POS matches."},
 "SB-0060": {"disp":"clean-candidate","conf":"high","why":"amateur → «любитель»; definition (one who pursues an activity/art without doing it professionally) is accurate; noun/adj POS matches."},
 "SB-1431": {"disp":"clean-candidate","conf":"high","why":"comments → «коментарі»; definition (an oral or written remark) is accurate; plural noun POS matches."},
}
