# -*- coding: utf-8 -*-
"""Pass-B chunk 4 row-level judgments (hand-authored, blind). Schema: see chunk1.py."""

JUDGMENTS = {
 "SB-1713": {"disp":"clean-candidate","conf":"high","why":"tension → «напруга»; definition (a condition of being between two or more opposing forces) is accurate; noun POS matches."},
 "SB-0471": {"disp":"clean-candidate","conf":"high","why":"evolutionary → «еволюційний»; definition (relating to the biological theory of evolution) is accurate; adjective POS matches."},
 "SB-1771": {"disp":"P2","conf":"low","flag":"p","cat":"citation-form","target":"ua","value":"що зустрів; натрапив (на)","why":"encountered glossed «зіткнувся» is a 3sg masculine past finite verb, an inconsistent citation for a word-family entry (peers use participles/impersonals); the definition itself is fine."},
 "SB-0241": {"disp":"clean-candidate","conf":"high","why":"configuration → «конфігурація»; definition (the mutual arrangement of a set of things; how things are arranged or assembled) is accurate; noun POS matches."},
 "SB-0974": {"disp":"clean-candidate","conf":"high","why":"refuge → «притулок»; definition (a place providing safety, protection or shelter) is accurate; noun POS matches."},
 "SB-0802": {"disp":"clean-candidate","conf":"medium","why":"nominate → «номінувати»; definition (to name someone as a candidate for a role or office) is accurate despite the redundant «включно з посадою»; verb POS matches."},
 "SB-1769": {"disp":"clean-candidate","conf":"medium","why":"convinced → «переконаний»; definition (in a state of belief, esp. based on evidence) conveys the sense despite the trailing «але не обов'язково»; adjective POS matches."},
 "SB-0243": {"disp":"clean-candidate","conf":"high","why":"confirmation → «підтвердження»; definition (verification that something is true or has happened) is accurate; noun POS matches."},
 "SB-0728": {"disp":"clean-candidate","conf":"high","why":"magnitude → «величина»; definition (the absolute or relative size, degree or importance of something) is accurate; noun POS matches."},
 "SB-0117": {"disp":"clean-candidate","conf":"high","why":"battlefield → «поле бою»; definition (an area where a land battle is fought, not necessarily a field) is accurate; noun POS matches."},
 "SB-0261": {"disp":"clean-candidate","conf":"high","why":"constitutional → «конституційний»; definition (relating to a legal or political constitution) is accurate; adjective POS matches."},
 "SB-1716": {"disp":"clean-candidate","conf":"high","why":"uniform → «уніформа»; definition (distinctive clothing identifying members of a group, company, prisoners etc.) is accurate; noun POS matches."},
 "SB-0736": {"disp":"clean-candidate","conf":"medium","why":"manipulation → «маніпуляція»; definition (the practice or state of manipulating) is near-circular but not misleading; noun POS matches."},
 "SB-1522": {"disp":"clean-candidate","conf":"high","why":"parameters → «параметри»; definition (a value held constant within an experiment but varied across versions) is accurate; plural noun POS matches."},
 "SB-1591": {"disp":"clean-candidate","conf":"high","why":"author → «автор»; definition (the writer or creator of a work, esp. literary; a co-creator) is accurate; noun POS matches."},
 "SB-0041": {"disp":"clean-candidate","conf":"high","why":"aftermath → «наслідки (переважно негативні)»; definition (what follows, usually with a strongly negative connotation, implying a prior disaster) is accurate; noun POS matches."},
 "SB-0402": {"disp":"clean-candidate","conf":"high","why":"divine → «божественний»; definition (from or relating to a god) is accurate; adjective POS matches."},
 "SB-1411": {"disp":"clean-candidate","conf":"high","why":"primary → «первинний»; definition (first or earliest in a group or series) is accurate; adjective POS matches."},
 "SB-0438": {"disp":"clean-candidate","conf":"high","why":"empirical → «емпіричний»; definition (relating to or based on experience, as opposed to theory) is accurate; adjective POS matches."},
 "SB-1732": {"disp":"clean-candidate","conf":"high","why":"controversy → «суперечка»; definition (debate or discussion of opposing opinions; a quarrel) is accurate; noun POS matches."},
 "SB-1579": {"disp":"clean-candidate","conf":"high","why":"target → «мета»; definition (a goal or objective) is accurate; noun POS matches."},
 "SB-0480": {"disp":"clean-candidate","conf":"high","why":"execution → «виконання»; definition (the action, manner or style of carrying out actions, manoeuvres or performances) is accurate; noun POS matches."},
 "SB-0965": {"disp":"clean-candidate","conf":"high","why":"reassure → «заспокоювати»; definition (to assure again; to restore confidence; to free from fear or self-doubt) is accurate; verb POS matches."},
 "SB-0003": {"disp":"clean-candidate","conf":"high","why":"absence → «відсутність»; definition (the state of being away or apart from a place or communication) is accurate; noun POS matches."},
 "SB-0539": {"disp":"clean-candidate","conf":"high","why":"gaze → «погляд»; definition (to look steadily or intently) covers the n.,v. senses; POS tag matches."},
 "SB-1250": {"disp":"clean-candidate","conf":"high","why":"undoubtedly → «безсумнівно»; definition (without doubt; unambiguously) is accurate; adverb POS matches."},
 "SB-1665": {"disp":"clean-candidate","conf":"high","why":"quotation → «цитата»; definition (a fragment of expression repeated by another, e.g. from literature or a famous speech) is accurate; noun POS matches."},
 "SB-0791": {"disp":"clean-candidate","conf":"high","why":"namely → «а саме»; definition (specifically; that is) is accurate; adverb POS matches."},
 "SB-0915": {"disp":"clean-candidate","conf":"high","why":"privilege → «привілей»; definition (a specific benefit or advantage; a right or immunity enjoyed by some but not others) is accurate; noun POS matches."},
 "SB-1354": {"disp":"clean-candidate","conf":"high","why":"percent → «відсоток»; definition (per each hundred, forming a noun expressing proportion) is accurate; noun POS matches."},
 "SB-1260": {"disp":"clean-candidate","conf":"high","why":"vacuum → «вакуум»; definition (a region of space containing no matter) is accurate; noun POS matches."},
 "SB-1555": {"disp":"clean-candidate","conf":"medium","why":"expansion → «розширення»; definition (the action, process or instance of expanding) is near-circular but not misleading; noun POS matches."},
 "SB-1462": {"disp":"clean-candidate","conf":"high","why":"outcomes → «результати»; definition (what is produced or happens as a result of an event or process) is accurate; plural noun POS matches."},
 "SB-0192": {"disp":"clean-candidate","conf":"high","why":"cling → «чіплятися»; definition (to hold very tightly so as not to fall) is accurate; verb POS matches."},
 "SB-0019": {"disp":"clean-candidate","conf":"medium","why":"accusation → «звинувачення»; definition (the act of accusing) is near-circular but not misleading; noun POS matches."},
 "SB-0598": {"disp":"clean-candidate","conf":"high","why":"ignorance → «незнання»; definition (the state of being uninformed or uneducated; lack of knowledge) is accurate; noun POS matches."},
 "SB-0276": {"disp":"clean-candidate","conf":"high","why":"convict → «засуджувати»; definition (to find guilty as a result of a trial, or informally in a moral sense) is accurate; verb POS matches."},
 "SB-0726": {"disp":"clean-candidate","conf":"high","why":"magistrate → «суддя»; definition (a judicial officer with limited powers to administer and enforce the law) is accurate; noun POS matches."},
 "SB-1717": {"disp":"clean-candidate","conf":"high","why":"vehicle → «транспортний засіб»; definition (a device for carrying or transporting substances, objects, people or animals) is accurate; noun POS matches."},
 "SB-0580": {"disp":"clean-candidate","conf":"high","why":"high-profile → «гучний»; definition (important or well-publicised) is accurate; adjective POS matches."},
 "SB-0143": {"disp":"clean-candidate","conf":"high","why":"bow → «нахилятися; уклін»; definition (to tilt the head or upper body as a sign of respect; also the bow itself) covers the v.,n. senses; the disambiguator matches."},
 "SB-0676": {"disp":"clean-candidate","conf":"high","why":"justification → «виправдання»; definition (a reason or explanation giving convincing, morally acceptable support for conduct or belief) is accurate; noun POS matches."},
 "SB-0063": {"disp":"clean-candidate","conf":"medium","why":"amendment → «поправка»; definition (an addition or change, e.g. to a constitution) is accurate though slightly narrowed to constitutions; noun POS matches."},
 "SB-1357": {"disp":"clean-candidate","conf":"high","why":"principle → «принцип»; definition (a fundamental assumption or guiding belief) is accurate; noun POS matches."},
 "SB-1663": {"disp":"clean-candidate","conf":"high","why":"prohibited → «заборонено»; definition (forbidden; not permitted) is accurate; consistent gloss."},
 "SB-0291": {"disp":"clean-candidate","conf":"high","why":"correspondent → «кореспондент»; definition (someone who communicates with another person or publication in writing) is accurate; noun POS matches."},
 "SB-1515": {"disp":"clean-candidate","conf":"high","why":"mechanism → «механізм»; definition (any mechanical means for converting or controlling motion, or transmitting power) is accurate; noun POS matches."},
 "SB-0196": {"disp":"clean-candidate","conf":"high","why":"coalition → «коаліція»; definition (a temporary group or union of organisations formed for a specific advantage) is accurate; noun POS matches."},
 "SB-0258": {"disp":"clean-candidate","conf":"high","why":"constituency → «виборчий округ»; definition (a district represented by one or more elected officials) is accurate; noun POS matches."},
 "SB-1559": {"disp":"clean-candidate","conf":"medium","why":"generated → «створений»; definition (to bring into being; to produce) conveys the sense; consistent gloss for the family."},
 "SB-0182": {"disp":"clean-candidate","conf":"high","why":"chronic → «хронічний»; definition (of a problem, lasting over a long period) is accurate; adjective POS matches."},
 "SB-0458": {"disp":"clean-candidate","conf":"high","why":"enthusiast → «ентузіаст»; definition (a person full of or driven by enthusiasm) is accurate; noun POS matches."},
 "SB-1392": {"disp":"clean-candidate","conf":"high","why":"design → «дизайн»; definition (a plan of the structure and function of an artefact, building or system) is accurate; noun POS matches."},
 "SB-1638": {"disp":"clean-candidate","conf":"medium","why":"converted → «перетворений»; definition (form or function has changed) conveys the sense despite terse phrasing; consistent gloss."},
 "SB-0027": {"disp":"clean-candidate","conf":"high","why":"adaptation → «адаптація»; definition (the process of adapting or adjusting to a situation; modification) is accurate; noun POS matches."},
 "SB-0956": {"disp":"clean-candidate","conf":"high","why":"rape → «зґвалтування»; definition (to force someone into sexual acts without consent) is accurate and appropriately clinical; n.,v. POS matches."},
 "SB-0475": {"disp":"clean-candidate","conf":"high","why":"excess → «надлишок»; definition (the state of exceeding or going beyond limits; more than usual or proper) is accurate; n.,adj. POS matches."},
 "SB-1737": {"disp":"clean-candidate","conf":"high","why":"duration → «тривалість»; definition (a span of time or a particular length of time) is accurate; noun POS matches."},
 "SB-0288": {"disp":"clean-candidate","conf":"high","why":"correlation → «кореляція»; definition (a measure of the linear statistical relationship between two random variables) is accurate; noun POS matches."},
 "SB-0879": {"disp":"clean-candidate","conf":"high","why":"poll → «опитування»; definition (a survey of people, usually with statistical analysis to estimate wider opinion) is accurate; noun POS matches."},
 "SB-1083": {"disp":"clean-candidate","conf":"high","why":"smash → «розбити»; definition (to break something fragile forcefully) is accurate; verb POS matches."},
 "SB-0709": {"disp":"clean-candidate","conf":"high","why":"limb → «кінцівка»; definition (a main appendage of a human or animal used for movement, e.g. arm, leg or wing) is accurate; noun POS matches."},
 "SB-1468": {"disp":"clean-candidate","conf":"high","why":"reaction → «реакція»; definition (an action or statement in response to a stimulus or event) is accurate; noun POS matches."},
 "SB-1672": {"disp":"clean-candidate","conf":"high","why":"ultimately → «зрештою»; definition (in the end; finally) is accurate; adverb POS matches."},
 "SB-0325": {"disp":"clean-candidate","conf":"high","why":"debut → «дебют»; definition (a performer's first public appearance in sport, art or another field) is accurate; noun POS matches."},
 "SB-0163": {"disp":"clean-candidate","conf":"high","why":"capitalism → «капіталізм»; definition (an economic system based on private ownership of the means of production for profit) is accurate; noun POS matches."},
 "SB-1478": {"disp":"clean-candidate","conf":"high","why":"task → «завдання»; definition (a piece of work performed as part of one's duties) is accurate; noun POS matches."},
 "SB-1024": {"disp":"clean-candidate","conf":"high","why":"riot → «бунт»; definition (a violent disturbance of public order by a large group, often with violence or property damage) is accurate; noun POS matches."},
 "SB-0006": {"disp":"clean-candidate","conf":"high","why":"abundance → «достаток»; definition (a large quantity; a lot) is accurate; noun POS matches."},
 "SB-1491": {"disp":"clean-candidate","conf":"high","why":"code → «код»; definition (an instruction to a computer written in a programming language; source/machine/byte code) is accurate; noun POS matches."},
 "SB-1507": {"disp":"clean-candidate","conf":"high","why":"hence → «отже»; definition (as a result; therefore, for this reason) is accurate; adverb POS matches."},
 "SB-1450": {"disp":"clean-candidate","conf":"high","why":"illustrated → «ілюстрований»; definition (containing illustrations) is accurate; consistent gloss."},
 "SB-0564": {"disp":"clean-candidate","conf":"high","why":"halfway → «на півдорозі»; definition (half the way between two points) is accurate; adverb POS matches."},
 "SB-0776": {"disp":"clean-candidate","conf":"high","why":"misleading → «оманливий»; definition (deceptive or tending to mislead or create a false impression even if technically true) is accurate; adjective POS matches."},
 "SB-0158": {"disp":"clean-candidate","conf":"high","why":"burst → «лопнути»; definition (to break from internal pressure) is accurate; verb POS matches."},
 "SB-0930": {"disp":"clean-candidate","conf":"high","why":"propaganda → «пропаганда»; definition (public communication aimed at influencing an audience and promoting an agenda) is accurate; noun POS matches."},
 "SB-1045": {"disp":"clean-candidate","conf":"high","why":"scrutiny → «перевірка»; definition (intense examination of someone or something) is accurate; noun POS matches."},
 "SB-0966": {"disp":"clean-candidate","conf":"high","why":"rebel → «повстанець»; definition (a person who resists established authority, often violently) is accurate; noun POS matches."},
 "SB-0787": {"disp":"clean-candidate","conf":"high","why":"motive → «мотив»; definition (an incentive to act in a certain way; the reason or emotion prompting an action) is accurate; noun POS matches."},
 "SB-1361": {"disp":"clean-candidate","conf":"high","why":"research → «дослідження; досліджувати»; definition (diligent investigation to find or revise facts, principles or theories) is accurate; covers noun+verb senses."},
 "SB-1338": {"disp":"clean-candidate","conf":"high","why":"export → «експорт; експортувати»; definition (the act of exporting) is accurate; covers noun+verb senses."},
 "SB-0614": {"disp":"clean-candidate","conf":"medium","why":"indigenous → «корінний»; definition (born or originating in a country or region, esp. before invasion) conveys the sense despite the «Народився» framing; adjective POS matches."},
 "SB-1496": {"disp":"clean-candidate","conf":"high","why":"contrast → «контраст»; definition (the difference between two objects, people or concepts) is accurate; noun POS matches."},
 "SB-1033": {"disp":"clean-candidate","conf":"high","why":"rumour → «чутка»; definition (unverified information spread among people) is accurate; noun POS matches."},
 "SB-1602": {"disp":"clean-candidate","conf":"high","why":"expert → «експерт»; definition (a person with extensive knowledge or ability in a subject) is accurate; noun POS matches."},
 "SB-0896": {"disp":"clean-candidate","conf":"high","why":"premier → «прем'єр»; definition (the head of government in a parliament and leader of the cabinet) is accurate; noun POS matches."},
 "SB-1641": {"disp":"clean-candidate","conf":"high","why":"definite → «певний»; definition (without any doubt) is accurate; adjective POS matches."},
 "SB-0260": {"disp":"clean-candidate","conf":"high","why":"constitution → «конституція»; definition (a formal or informal system of primary principles and laws governing a government or institution) is accurate; noun POS matches."},
 "SB-1152": {"disp":"clean-candidate","conf":"high","why":"suicide → «самогубство»; definition (the act of intentionally killing oneself) is accurate; noun POS matches."},
 "SB-0782": {"disp":"clean-candidate","conf":"medium","why":"modification → «модифікація»; definition (the result of modifying something; a new or changed form) conveys the sense despite minor case slippage («нову»); noun POS matches."},
 "SB-1648": {"disp":"clean-candidate","conf":"high","why":"foundation → «основа»; definition (that on which everything is based; the lower supporting layer of a superstructure) is accurate; noun POS matches."},
 "SB-0199": {"disp":"clean-candidate","conf":"high","why":"cognitive → «когнітивний»; definition (relating to the mental functions dealing with logic, as opposed to affective/emotional) is accurate; adjective POS matches."},
 "SB-0346": {"disp":"clean-candidate","conf":"high","why":"density → «щільність»; definition (a measure of the mass of a substance contained in a unit volume) is accurate; noun POS matches."},
 "SB-1484": {"disp":"clean-candidate","conf":"high","why":"adequate → «адекватний»; definition (equal to or meeting a particular requirement) is accurate; adjective POS matches."},
 "SB-1461": {"disp":"clean-candidate","conf":"high","why":"negative → «негативний»; definition (not positive or neutral; bad; undesirable; unfavourable) is accurate; adjective POS matches."},
 "SB-1783": {"disp":"clean-candidate","conf":"high","why":"so-called → «т. зв»; definition (so named; commonly called) is accurate; the abbreviation matches Ukrainian usage; consistent gloss."},
 "SB-1644": {"disp":"clean-candidate","conf":"high","why":"eliminate → «ліквідувати»; definition (to remove completely, get rid of, put an end to) is accurate; verb POS matches."},
 "SB-0653": {"disp":"clean-candidate","conf":"high","why":"interface → «інтерфейс»; definition (a point of interconnection between systems or subsystems) is accurate; noun POS matches."},
 "SB-1545": {"disp":"clean-candidate","conf":"high","why":"compounds → «сполуки»; definition (anything made by combining several things) is accurate; plural noun POS matches."},
 "SB-1494": {"disp":"clean-candidate","conf":"high","why":"concentration → «концентрація»; definition (the action, process or ability of concentrating; the state of being focused) is accurate; noun POS matches."},
 "SB-0535": {"disp":"clean-candidate","conf":"high","why":"funeral → «похорон»; definition (a ceremony honouring and remembering a deceased person, often with the body present) is accurate; noun POS matches."},
 "SB-0385": {"disp":"clean-candidate","conf":"high","why":"discourse → «дискурс»; definition (expression in words, spoken or written) is accurate; noun POS matches."},
 "SB-0969": {"disp":"clean-candidate","conf":"high","why":"reconstruction → «реконструкція»; definition (the act of reconstructing something, not necessarily to a previous state) is accurate; noun POS matches."},
 "SB-1096": {"disp":"clean-candidate","conf":"high","why":"span → «охоплювати; тривати»; definition (to stretch across the distance between or across) is accurate; v.,n. POS matches."},
 "SB-0212": {"disp":"clean-candidate","conf":"high","why":"commissioner → «комісар»; definition (an official in charge of a government department, esp. police) is accurate; noun POS matches."},
 "SB-1669": {"disp":"clean-candidate","conf":"high","why":"survive → «вижити»; definition (of a person, to continue to live; to remain alive) is accurate; verb POS matches."},
 "SB-1253": {"disp":"clean-candidate","conf":"high","why":"unveil → «розкрити»; definition (to remove a veil from; to reveal; to disclose something hidden) is accurate; verb POS matches."},
 "SB-1561": {"disp":"clean-candidate","conf":"high","why":"image → «зображення»; definition (a visual or other representation of the external form of something in art) is accurate; noun POS matches."},
 "SB-1424": {"disp":"clean-candidate","conf":"high","why":"strategies → «стратегії»; definition (a plan of action aimed at achieving a specific goal) is accurate; plural noun POS matches."},
 "SB-0181": {"disp":"clean-candidate","conf":"high","why":"charter → «статут»; definition (a document issued by an authority creating an institution and defining its aims and privileges) is accurate; noun POS matches."},
 "SB-0562": {"disp":"clean-candidate","conf":"high","why":"gut → «кишка»; definition (the digestive tract, esp. the intestines) is accurate; noun POS matches."},
 "SB-0347": {"disp":"clean-candidate","conf":"high","why":"dependence → «залежність»; definition (the state of depending or relying on another) is accurate; noun POS matches."},
 "SB-0810": {"disp":"clean-candidate","conf":"high","why":"notably → «особливо»; definition (as a striking example; in a noticeable manner) is accurate; adverb POS matches."},
 "SB-0944": {"disp":"clean-candidate","conf":"high","why":"pulse → «пульс»; definition (the usually regular heartbeat felt when arteries near the skin are compressed) is accurate; noun POS matches."},
 "SB-0914": {"disp":"clean-candidate","conf":"high","why":"privatization → «приватизація»; definition (transfer of a company from public ownership and control to private) is accurate; noun POS matches."},
 "SB-1266": {"disp":"clean-candidate","conf":"high","why":"vein → «вена»; definition (a blood vessel transporting blood from the capillaries back to the heart) is accurate; noun POS matches."},
 "SB-1477": {"disp":"clean-candidate","conf":"high","why":"sufficient → «достатній»; definition (of a kind or amount that satisfies requirements or needs) is accurate; adjective POS matches."},
 "SB-1333": {"disp":"clean-candidate","conf":"high","why":"economic → «економічний»; definition (relating to the economy) is accurate; adjective POS matches."},
 "SB-0287": {"disp":"clean-candidate","conf":"high","why":"correlate → «співвідносити»; definition (to compare things and bring them into a relation with corresponding characteristics) is accurate; verb POS matches."},
 "SB-0763": {"disp":"clean-candidate","conf":"high","why":"methodology → «методологія»; definition (a set of methods, practices, procedures and rules used by those in a field) is accurate; noun POS matches."},
 "SB-0873": {"disp":"clean-candidate","conf":"high","why":"plea → «прохання»; definition (an appeal, request, urgent prayer or entreaty) is accurate; noun POS matches."},
 "SB-0381": {"disp":"clean-candidate","conf":"high","why":"discard → «відкинути»; definition (to throw away, cast off) is accurate; verb POS matches."},
 "SB-0871": {"disp":"clean-candidate","conf":"high","why":"pirate → «пірат»; definition (a criminal who robs at sea, usually attacking merchant vessels) is accurate; noun POS matches."},
 "SB-0890": {"disp":"clean-candidate","conf":"high","why":"predator → «хижак»; definition (an animal or organism that hunts and kills other non-plant organisms as prey, mainly for food) is accurate; noun POS matches."},
 "SB-1502": {"disp":"clean-candidate","conf":"medium","why":"emerged → «виник»; definition (to come into view) conveys the sense; consistent gloss for the family."},
 "SB-1482": {"disp":"clean-candidate","conf":"high","why":"volume → «обсяг»; definition (a three-dimensional measure of space of length, width and height, measured in cubic units) is accurate; noun POS matches."},
 "SB-1092": {"disp":"clean-candidate","conf":"high","why":"solo → «соло»; definition (a work or performance done by one person) is accurate; adj.,n. POS matches."},
 "SB-1761": {"disp":"clean-candidate","conf":"high","why":"team → «команда»; definition (any group of people engaged in one activity, esp. sport or work) is accurate; noun POS matches."},
 "SB-0764": {"disp":"clean-candidate","conf":"high","why":"midst → «посеред»; definition (a place in the middle of something, literal or metaphorical) is accurate; noun POS matches."},
 "SB-0754": {"disp":"clean-candidate","conf":"high","why":"memorial → «меморіал»; definition (something, e.g. a monument, by which someone or something is remembered) is accurate; noun POS matches."},
 "SB-0713": {"disp":"clean-candidate","conf":"high","why":"listing → «список»; definition (an entry in a list or catalogue) is accurate; noun POS matches."},
 "SB-0099": {"disp":"P2","conf":"medium","flag":"kp","cat":"pos-gloss-mismatch","target":"ua","value":"приписувати; атрибут","why":"attribute (v., n.): the definition describes the verb ('associate ownership/authorship with someone' = приписувати), but the gloss «атрибут» gives only the noun; the verb sense is missing."},
 "SB-0018": {"disp":"clean-candidate","conf":"high","why":"accumulation → «накопичення»; definition (the act of accumulating or gathering, as in a heap) is accurate; noun POS matches."},
 "SB-0318": {"disp":"clean-candidate","conf":"high","why":"custody → «опіка»; definition (the legal right to care for something or someone, esp. children) is accurate; noun POS matches."},
 "SB-1352": {"disp":"clean-candidate","conf":"high","why":"method → «метод»; definition (a process by which a task is performed; a way of doing something) is accurate; noun POS matches."},
 "SB-0959": {"disp":"clean-candidate","conf":"high","why":"ray → «промінь»; definition (a beam of light or radiation) is accurate; noun POS matches."},
 "SB-0320": {"disp":"clean-candidate","conf":"high","why":"cynical → «цинічний»; definition (sceptical of the honesty, sincerity or motives of others) is accurate; adjective POS matches."},
 "SB-1346": {"disp":"clean-candidate","conf":"high","why":"interpretation → «тлумачення; інтерпретація»; definition (the act of interpreting or explaining something unclear; a translation; a version) is accurate; noun POS matches."},
 "SB-0218": {"disp":"clean-candidate","conf":"high","why":"compel → «змушувати»; definition (to force, constrain or coerce) is accurate; verb POS matches."},
 "SB-1359": {"disp":"clean-candidate","conf":"high","why":"process → «процес; обробляти»; definition (a series of events leading to a result or product) is accurate; covers noun+verb senses."},
 "SB-0441": {"disp":"clean-candidate","conf":"high","why":"encompass → «охоплювати»; definition (to include within its scope; to encircle or surround; to contain) is accurate; verb POS matches."},
 "SB-1536": {"disp":"clean-candidate","conf":"high","why":"sum → «сума»; definition (a quantity obtained by adding or aggregating) is accurate; noun POS matches."},
 "SB-0681": {"disp":"clean-candidate","conf":"high","why":"landlord → «орендодавець»; definition (a person who leases out real property; a lessor) is accurate; noun POS matches."},
 "SB-1675": {"disp":"clean-candidate","conf":"high","why":"voluntary → «добровільний»; definition (done, given or acting of one's own free will) is accurate; adjective POS matches."},
 "SB-0179": {"disp":"clean-candidate","conf":"high","why":"characterize → «характеризувати»; definition (to be typical of) is accurate; verb POS matches."},
 "SB-1119": {"disp":"clean-candidate","conf":"medium","why":"statistical → «статистичний»; definition (of or relating to statistics) is accurate; adjective POS matches."},
 "SB-0035": {"disp":"clean-candidate","conf":"high","why":"adolescent → «підліток»; definition (a person in adolescence; one who has reached puberty but is not yet an adult) is accurate; noun POS matches."},
 "SB-0251": {"disp":"clean-candidate","conf":"high","why":"consciousness → «свідомість»; definition (the state of being conscious or aware; awareness) is accurate; noun POS matches."},
 "SB-0980": {"disp":"clean-candidate","conf":"high","why":"regulatory → «регулятивний»; definition (regulating or relating to regulation) is accurate; adjective POS matches."},
 "SB-1172": {"disp":"clean-candidate","conf":"high","why":"suspicious → «підозрілий»; definition (distrustful or inclined to suspect) is accurate; adjective POS matches."},
 "SB-0566": {"disp":"clean-candidate","conf":"high","why":"handful → «жменя»; definition (a quantity the hand can grasp or hold) is accurate; noun POS matches."},
 "SB-0431": {"disp":"clean-candidate","conf":"high","why":"elite → «еліта»; definition (a special group or social class of higher status with corresponding power and privileges) is accurate; noun POS matches."},
 "SB-1249": {"disp":"clean-candidate","conf":"high","why":"undermine → «підривати»; definition (to weaken or act against; to hinder, sabotage) is accurate; verb POS matches."},
 "SB-1156": {"disp":"clean-candidate","conf":"high","why":"superior → «вищий»; definition (higher in rank, status or quality) is accurate; adjective POS matches."},
 "SB-1508": {"disp":"clean-candidate","conf":"high","why":"hypothesis → «гіпотеза»; definition (a tentative assumption explaining an observation, testable by further study or experiment) is accurate; noun POS matches."},
 "SB-0095": {"disp":"clean-candidate","conf":"high","why":"atrocity → «злодіяння»; definition (an extremely cruel act; a horrific act of injustice) is accurate; noun POS matches."},
 "SB-0217": {"disp":"clean-candidate","conf":"high","why":"compassion → «співчуття»; definition (a deep awareness of others' suffering, with the motivation to relieve it) is accurate; noun POS matches."},
 "SB-1739": {"disp":"clean-candidate","conf":"high","why":"ethical → «етичний»; definition (relating to accepted principles of right and wrong, esp. in an organisation or profession) is accurate; adjective POS matches."},
 "SB-0239": {"disp":"clean-candidate","conf":"high","why":"confer → «надавати»; definition (to grant into possession; to bestow) is accurate for the 'grant' sense; verb POS matches."},
 "SB-1422": {"disp":"clean-candidate","conf":"high","why":"select → «вибрати»; definition (to choose one or more items from a set, esp. of options) is accurate; verb POS matches."},
 "SB-0599": {"disp":"clean-candidate","conf":"high","why":"imagery → «зображення»; definition (rhetorical decoration in writing or speech; vivid descriptions evoking sensory images) is accurate; noun POS matches."},
 "SB-1183": {"disp":"clean-candidate","conf":"high","why":"taxpayer → «платник податків»; definition (a person subject or obliged to pay tax) is accurate; noun POS matches."},
 "SB-1074": {"disp":"clean-candidate","conf":"high","why":"sin → «гріх»; definition (a violation of divine will or religious law) is accurate; noun POS matches."},
 "SB-0888": {"disp":"clean-candidate","conf":"high","why":"precedent → «прецедент»; definition (a past action usable as an example to help decide the outcome of similar future cases) is accurate; noun POS matches."},
 "SB-0091": {"disp":"clean-candidate","conf":"high","why":"assert → «стверджувати»; definition (to declare with confidence or firmly; to state positively) is accurate; verb POS matches."},
 "SB-1228": {"disp":"clean-candidate","conf":"high","why":"transmission → «передача»; definition (the act of transmitting, e.g. data signals or electricity) is accurate; noun POS matches."},
 "SB-0800": {"disp":"clean-candidate","conf":"high","why":"noble → «благородний»; definition (having honourable qualities; moral elevation and freedom from anything petty or base) is accurate; adjective POS matches."},
 "SB-0523": {"disp":"clean-candidate","conf":"high","why":"formulate → «формулювати»; definition (to state in a clear and definite form) is accurate; verb POS matches."},
 "SB-0955": {"disp":"clean-candidate","conf":"high","why":"ranking → «рейтинг»; definition (a relative placement in a list) is accurate; noun POS matches."},
 "SB-0644": {"disp":"clean-candidate","conf":"high","why":"integrated → «інтегрований»; definition (composed and coordinated to form a whole) is accurate; consistent gloss."},
 "SB-0047": {"disp":"clean-candidate","conf":"high","why":"alien → «чужий»; definition (not belonging to the same country, land or government or its citizens; foreign) is accurate; adjective POS matches."},
 "SB-0732": {"disp":"clean-candidate","conf":"high","why":"mandate → «мандат; офіційні повноваження»; definition (an official or authoritative command; an order, commission, or authorisation) is accurate; noun POS matches."},
 "SB-0089": {"disp":"clean-candidate","conf":"high","why":"assemble → «зібрати»; definition (to gather together) is accurate; verb POS matches."},
 "SB-0138": {"disp":"clean-candidate","conf":"high","why":"boast → «хвалитися»; definition (to brag; to speak loudly in praise of oneself) is accurate; verb POS matches."},
 "SB-0059": {"disp":"clean-candidate","conf":"high","why":"aluminium → «алюміній»; definition (a light silvery metal from bauxite, element Al, atomic number 13) is factually correct; noun POS matches."},
 "SB-0367": {"disp":"clean-candidate","conf":"high","why":"diagnose → «діагностувати»; definition (to determine which disease is causing a person's signs and symptoms) is accurate; verb POS matches."},
 "SB-0957": {"disp":"clean-candidate","conf":"high","why":"ratio → «співвідношення»; definition (a number representing a comparison between two named things) is accurate; noun POS matches."},
 "SB-1445": {"disp":"clean-candidate","conf":"high","why":"emphasis → «наголос»; definition (special weight or force given to something considered important) is accurate; noun POS matches."},
 "SB-1068": {"disp":"clean-candidate","conf":"high","why":"shrink → «скорочуватися»; definition (to become smaller; to contract) is accurate; verb POS matches."},
 "SB-1375": {"disp":"clean-candidate","conf":"high","why":"affect → «впливати»; definition (to influence or change) is accurate; verb POS matches."},
 "SB-0595": {"disp":"clean-candidate","conf":"high","why":"ideological → «ідеологічний»; definition (relating to one or more ideologies) is accurate; adjective POS matches."},
 "SB-1207": {"disp":"clean-candidate","conf":"high","why":"tide → «приплив»; definition (the daily fluctuation of sea level caused by the gravitational pull of the Moon and Sun) is accurate; noun POS matches."},
 "SB-0952": {"disp":"clean-candidate","conf":"high","why":"rage → «лють»; definition (intense uncontrolled anger) is accurate; noun POS matches."},
 "SB-1646": {"disp":"clean-candidate","conf":"high","why":"file → «файл»; definition (a collection of documents gathered and archived together) is accurate; noun POS matches."},
 "SB-0353": {"disp":"clean-candidate","conf":"high","why":"deputy → «заступник»; definition (one appointed to substitute for another and authorised to act on their behalf) is accurate; noun POS matches."},
 "SB-1573": {"disp":"clean-candidate","conf":"high","why":"psychology → «психологія»; definition (the study of the human mind) is accurate; noun POS matches."},
 "SB-1608": {"disp":"clean-candidate","conf":"high","why":"incentive → «стимул»; definition (something that motivates, excites or encourages) is accurate; noun POS matches."},
 "SB-0087": {"disp":"clean-candidate","conf":"high","why":"assassination → «вбивство»; definition (the killing of a person, esp. for political motives or personal gain) is accurate; noun POS matches."},
 "SB-0968": {"disp":"clean-candidate","conf":"high","why":"recipient → «одержувач»; definition (one who receives) is accurate; noun POS matches."},
 "SB-1503": {"disp":"clean-candidate","conf":"medium","why":"error → «помилка»; definition (an accidental incorrect action or false statement made unintentionally) is accurate though it restates the gloss; noun POS matches."},
 "SB-0248": {"disp":"clean-candidate","conf":"high","why":"congressional → «конгресовий»; definition (of or relating to a congress) is accurate; adjective POS matches."},
 "SB-0796": {"disp":"clean-candidate","conf":"high","why":"nest → «гніздо»; definition (a structure built by a bird to hatch eggs and raise young) is accurate; noun POS matches."},
 "SB-1633": {"disp":"clean-candidate","conf":"high","why":"chemical → «хімічний»; definition (of or related to chemistry) is accurate; adjective POS matches."},
 "SB-1069": {"disp":"clean-candidate","conf":"high","why":"shrug → «знизати плечима»; definition (to raise the shoulders to express uncertainty, unconcern or fear) is accurate; verb POS matches."},
 "SB-0822": {"disp":"clean-candidate","conf":"medium","why":"offering → «пропозиція»; definition (the act by which something is offered) conveys the sense; noun POS matches."},
 "SB-1292": {"disp":"clean-candidate","conf":"high","why":"weaken → «ослабити»; definition (to make weaker or less strong) is accurate; verb POS matches."},
 "SB-0808": {"disp":"clean-candidate","conf":"high","why":"noon → «полудень»; definition (the time of day when the Sun appears to reach its highest point; solar noon) is accurate; noun POS matches."},
 "SB-1597": {"disp":"clean-candidate","conf":"high","why":"diversity → «різноманітність»; definition (the quality of being diverse or different; difference or dissimilarity) is accurate; noun POS matches."},
 "SB-0903": {"disp":"clean-candidate","conf":"high","why":"preside → «головувати»; definition (to act as president or chair) is accurate; verb POS matches."},
 "SB-1293": {"disp":"clean-candidate","conf":"high","why":"weave → «плести»; definition (to form something by passing lengths or threads of material under one another) is accurate; verb POS matches."},
 "SB-1086": {"disp":"clean-candidate","conf":"high","why":"soar → «парити»; definition (to fly high effortlessly, like a bird) is accurate; verb POS matches."},
 "SB-0543": {"disp":"clean-candidate","conf":"high","why":"glance → «погляд»; definition (to direct the eyes at something, often briefly) covers the n.,v. senses; POS tag matches."},
 "SB-0868": {"disp":"clean-candidate","conf":"high","why":"physician → «лікар»; definition (a doctor trained in medicine) is accurate; noun POS matches."},
 "SB-0339": {"disp":"clean-candidate","conf":"high","why":"delegate → «делегат»; definition (a person authorised to act as a representative of another) is accurate; noun POS matches."},
 "SB-0501": {"disp":"clean-candidate","conf":"high","why":"feat → «подвиг; визначне досягнення»; definition (a relatively rare or difficult achievement) is accurate; noun POS matches."},
 "SB-0485": {"disp":"clean-candidate","conf":"high","why":"experimental → «експериментальний»; definition (relating to or based on experiment) is accurate; adjective POS matches."},
 "SB-1075": {"disp":"clean-candidate","conf":"high","why":"situated → «розташований»; definition (located in a particular place) is accurate; adjective POS matches."},
 "SB-1236": {"disp":"clean-candidate","conf":"high","why":"tribute → «данина»; definition (an acknowledgement of gratitude, respect or admiration; an accompanying gift) is accurate; noun POS matches."},
 "SB-1125": {"disp":"clean-candidate","conf":"high","why":"storage → «зберігання»; definition (the act of storing goods; the state of being stored) is accurate; noun POS matches."},
 "SB-1480": {"disp":"clean-candidate","conf":"high","why":"techniques → «техніки»; definition (a way of achieving or doing something, esp. requiring skill or knowledge) is accurate; plural noun POS matches."},
 "SB-0995": {"disp":"clean-candidate","conf":"high","why":"rental → «оренда»; definition (a payment for renting something) is accurate; noun POS matches."},
 "SB-1221": {"disp":"clean-candidate","conf":"high","why":"trademark → «товарний знак»; definition (a word, symbol or phrase identifying a company's product and distinguishing it from others) is accurate; noun POS matches."},
 "SB-1150": {"disp":"clean-candidate","conf":"high","why":"suck → «смоктати»; definition (to use the mouth and lips to draw in liquid, esp. milk from the breast) is accurate; verb POS matches."},
 "SB-1348": {"disp":"clean-candidate","conf":"high","why":"issues → «питання; проблеми»; definition (important matters or problems needing discussion or resolution) is accurate; plural noun POS matches."},
 "SB-0872": {"disp":"clean-candidate","conf":"high","why":"pit → «яма»; definition (a hole in the ground) is accurate; noun POS matches."},
 "SB-1186": {"disp":"clean-candidate","conf":"high","why":"tender → «ніжний»; definition (sensitive or painful to the touch) is accurate for this sense; adjective POS matches."},
 "SB-1525": {"disp":"clean-candidate","conf":"high","why":"prior → «попередній»; definition (coming earlier in order or time; former, previous) is accurate; adjective POS matches."},
 "SB-1721": {"disp":"clean-candidate","conf":"high","why":"visual → «візуальний»; definition (relating to or affecting sight) is accurate; adjective POS matches."},
 "SB-0482": {"disp":"clean-candidate","conf":"high","why":"exile → «вигнання»; definition (the state of being banished from one's home or country) is accurate; noun POS matches."},
 "SB-1006": {"disp":"clean-candidate","conf":"high","why":"residue → «залишок»; definition (what is retained or left after other elements are removed) is accurate; noun POS matches."},
 "SB-0742": {"disp":"clean-candidate","conf":"high","why":"mask → «маска»; definition (a covering, or partial covering, for the face used to disguise or protect) is accurate; noun POS matches."},
 "SB-0201": {"disp":"clean-candidate","conf":"high","why":"collaborate → «співпрацювати»; definition (to work together with others toward a common goal) is accurate; verb POS matches."},
 "SB-1312": {"disp":"clean-candidate","conf":"high","why":"worthy → «гідний»; definition (having worth, merit or value) is accurate; adjective POS matches."},
 "SB-1730": {"disp":"clean-candidate","conf":"high","why":"concurrent → «одночасний»; definition (occurring at the same time; simultaneous) is accurate; adjective POS matches."},
 "SB-0303": {"disp":"clean-candidate","conf":"high","why":"courtesy → «ввічливість»; definition (polite behaviour) is accurate; noun POS matches."},
 "SB-0761": {"disp":"clean-candidate","conf":"high","why":"merger → «злиття»; definition (the legal combination of two or more corporations into one legal entity) is accurate; noun POS matches."},
 "SB-1379": {"disp":"clean-candidate","conf":"high","why":"categories → «категорії»; definition (groups into which things with similar properties are combined) is accurate; plural noun POS matches."},
 "SB-0081": {"disp":"clean-candidate","conf":"high","why":"arm → «озброювати»; definition (to provide with armour or weapons) is accurate; verb POS matches."},
 "SB-1349": {"disp":"clean-candidate","conf":"high","why":"labour → «праця; робоча сила»; definition (effort expended on a task; to toil, work) is accurate; covers noun+verb senses."},
}
