# -*- coding: utf-8 -*-
"""Pass-B chunk 2 row-level judgments (hand-authored, blind). Schema: see chunk1.py."""

JUDGMENTS = {
 "SB-1439": {"disp":"clean-candidate","conf":"high","why":"corporate → «корпоративний»; definition (relating to a corporation) is accurate; adjective POS matches."},
 "SB-0262": {"disp":"clean-candidate","conf":"high","why":"constraint → «обмеження»; definition (that which restrains; a limitation) is accurate; noun POS matches."},
 "SB-0620": {"disp":"clean-candidate","conf":"medium","why":"infect → «заразити»; definition (bring a body into contact with a disease-causing agent) conveys the sense; trailing semicolon trivial."},
 "SB-0628": {"disp":"clean-candidate","conf":"high","why":"injustice → «несправедливість»; definition (violation of another's rights) is accurate; noun POS matches."},
 "SB-1140": {"disp":"clean-candidate","conf":"high","why":"subsidy → «субсидія»; definition (financial support or aid, e.g. a grant) is accurate; noun POS matches."},
 "SB-0127": {"disp":"clean-candidate","conf":"high","why":"betray → «зраджувати»; definition (break trust or reveal hidden information/true character) is accurate; verb POS matches."},
 "SB-0464": {"disp":"clean-candidate","conf":"high","why":"erect → «звести»; definition (assemble by joining materials or parts) is accurate; verb POS matches."},
 "SB-1370": {"disp":"clean-candidate","conf":"medium","why":"structure → «структура; структурувати»; definition (a cohesive whole made of separate parts) conveys the sense; noun+verb pair matches the family."},
 "SB-1374": {"disp":"clean-candidate","conf":"high","why":"administration → «адміністрування»; definition (the act of administering; management of public affairs) is accurate; noun POS matches."},
 "SB-0359": {"disp":"clean-candidate","conf":"high","why":"destructive → «руйнівний»; definition (causing destruction; harmful) is accurate; adjective POS matches."},
 "SB-1560": {"disp":"clean-candidate","conf":"high","why":"generation → «покоління»; definition (people born in a certain period sharing cultural ties) is accurate; noun POS matches."},
 "SB-1562": {"disp":"clean-candidate","conf":"high","why":"licence → «ліцензія»; definition (official permission for an activity, possession or use) is accurate; noun POS matches."},
 "SB-0533": {"disp":"clean-candidate","conf":"medium","why":"functional → «функціональний»; definition (useful; serving a purpose, performing a function) conveys the sense; adjective POS matches."},
 "SB-1120": {"disp":"clean-candidate","conf":"high","why":"steer → «керувати»; definition (control the course of a vessel/vehicle/craft via rudder, oar or wheel) is accurate; verb POS matches."},
 "SB-0522": {"disp":"clean-candidate","conf":"high","why":"formula → «формула»; definition (a plan or method to solve a problem or reach a result) is accurate; noun POS matches."},
 "SB-0366": {"disp":"clean-candidate","conf":"high","why":"devise → «придумати»; definition (use one's intellect to plan or design something) is accurate; verb POS matches."},
 "SB-1101": {"disp":"clean-candidate","conf":"high","why":"specimen → «зразок»; definition (a single instance representing a class; an example) is accurate; noun POS matches."},
 "SB-1047": {"disp":"clean-candidate","conf":"high","why":"secular → «світський»; definition (not especially religious; worldly/civil vs spiritual) is accurate; adjective POS matches."},
 "SB-0779": {"disp":"clean-candidate","conf":"high","why":"mobility → «мобільність»; definition (ability to move or be moved) is accurate; noun POS matches."},
 "SB-1463": {"disp":"clean-candidate","conf":"high","why":"partnership → «партнерство»; definition (association of two or more persons to run a business) is accurate; noun POS matches."},
 "SB-1345": {"disp":"P2","conf":"medium","flag":"sd","cat":"mistranslation-in-definition","target":"definitionUa","value":"Людина, яку розглядають окремо, а не як частину групи людей.","why":"individual gloss «окремий; особа» is right, but the definition renders 'considered singly' as «яку вважають самотньою» (considered lonely), which shifts the meaning to loneliness."},
 "SB-0877": {"disp":"clean-candidate","conf":"high","why":"plunge → «зануритися»; definition (dive, jump or throw oneself into water/liquid; submerge) is accurate; verb POS matches."},
 "SB-0756": {"disp":"clean-candidate","conf":"high","why":"merchant → «купець»; definition (a person who trades goods for profit) is accurate; noun POS matches."},
 "SB-1397": {"disp":"clean-candidate","conf":"high","why":"focus → «фокус»; definition (concentration of attention) is accurate; noun POS matches."},
 "SB-1316": {"disp":"clean-candidate","conf":"high","why":"analysis → «аналіз»; definition (breaking a complex thing into components for study) is accurate; noun POS matches."},
 "SB-1254": {"disp":"clean-candidate","conf":"high","why":"upcoming → «майбутній»; definition (happening or appearing in the relatively near future) is accurate; adjective POS matches."},
 "SB-1436": {"disp":"clean-candidate","conf":"high","why":"contribution → «внесок»; definition (something given that adds to a larger whole) is accurate; noun POS matches."},
 "SB-1223": {"disp":"clean-candidate","conf":"high","why":"trailer → «трейлер»; definition (an unpowered wheeled vehicle towed behind another to carry equipment) is accurate; noun POS matches."},
 "SB-0534": {"disp":"clean-candidate","conf":"high","why":"fundraising → «збір коштів»; definition (raising money by soliciting donations from individuals and companies) is accurate; noun POS matches."},
 "SB-1242": {"disp":"clean-candidate","conf":"high","why":"trustee → «довірена особа»; definition (one holding property in trust for beneficiaries) is accurate; noun POS matches."},
 "SB-1151": {"disp":"clean-candidate","conf":"high","why":"sue → «судитися»; definition (bring a legal, usually civil, action against someone) is accurate; verb POS matches."},
 "SB-0358": {"disp":"clean-candidate","conf":"high","why":"desktop → «робочий стіл»; definition (the main GUI of an OS showing icons, windows and wallpaper) is accurate; noun POS matches."},
 "SB-1410": {"disp":"clean-candidate","conf":"medium","why":"previous → «попередній»; definition (occurring before something else in time or order) is accurate; leading restatement of the gloss is trivial."},
 "SB-0466": {"disp":"clean-candidate","conf":"high","why":"essence → «суть»; definition (the intrinsic nature of a thing or idea) is accurate; noun POS matches."},
 "SB-1557": {"disp":"clean-candidate","conf":"medium","why":"external → «зовнішній»; definition (outside of something; on the exterior) conveys the sense; adjective POS matches."},
 "SB-1288": {"disp":"clean-candidate","conf":"high","why":"warehouse → «склад»; definition (a place for storing large quantities of goods in logistics) is accurate; noun POS matches."},
 "SB-1415": {"disp":"clean-candidate","conf":"high","why":"regulations → «нормативні акти»; definition (a rule issued by an organisation to guide members' conduct) is accurate; plural noun POS matches."},
 "SB-1072": {"disp":"clean-candidate","conf":"high","why":"simulation → «моделювання»; definition (something imitating a system to predict real behaviour) is accurate; noun POS matches."},
 "SB-0704": {"disp":"clean-candidate","conf":"medium","why":"liberation → «звільнення»; definition (the act or state of liberating) is near-circular but not misleading; noun POS matches."},
 "SB-1202": {"disp":"clean-candidate","conf":"high","why":"thought-provoking → «що спонукає до роздумів»; definition (interesting in a way that challenges one's beliefs/views) is accurate; adjective POS matches."},
 "SB-0729": {"disp":"clean-candidate","conf":"high","why":"mainland → «материк»; definition (a continent; the main land as opposed to islands or a peninsula) is accurate; noun POS matches."},
 "SB-1133": {"disp":"clean-candidate","conf":"high","why":"strive → «прагнути»; definition (make strenuous, earnest and persistent efforts to achieve a result) is accurate; verb POS matches."},
 "SB-0894": {"disp":"clean-candidate","conf":"high","why":"prejudice → «упередження»; definition (a negative judgement formed in advance without knowledge of the facts) is accurate; noun POS matches."},
 "SB-0587": {"disp":"clean-candidate","conf":"high","why":"hostage → «заручник»; definition (a person seized to compel another party to act via threat of harm) is accurate; noun POS matches."},
 "SB-1457": {"disp":"clean-candidate","conf":"medium","why":"link → «посилання»; definition (a connection between places, people, events, things or ideas) covers the general 'link' sense; noun POS matches."},
 "SB-0611": {"disp":"clean-candidate","conf":"high","why":"incur → «понести»; definition (bring upon oneself, esp. something harmful or burdensome) is accurate; verb POS matches."},
 "SB-0168": {"disp":"clean-candidate","conf":"high","why":"casino → «казино»; definition (a public building or hall for gambling) is accurate; noun POS matches."},
 "SB-0596": {"disp":"clean-candidate","conf":"high","why":"ideology → «ідеологія»; definition (a doctrine, philosophy or set of beliefs of a person or group) is accurate; noun POS matches."},
 "SB-0097": {"disp":"clean-candidate","conf":"high","why":"attendance → «присутність»; definition (the act of attending; the state of being present) is accurate; noun POS matches."},
 "SB-0118": {"disp":"P2","conf":"medium","flag":"cn","cat":"literal-calque","target":"definitionUa","value":"Водойма (особливо частина моря), оточена увігнутою береговою лінією.","why":"bay definition opens «Тіло води», a literal calque of 'body of water'; natural Ukrainian is «водойма». The gloss «затока» itself is correct."},
 "SB-0120": {"disp":"clean-candidate","conf":"high","why":"beast → «звір»; definition (an animal, esp. a large or dangerous land vertebrate) is accurate; noun POS matches."},
 "SB-0494": {"disp":"clean-candidate","conf":"high","why":"faction → «фракція»; definition (a group, esp. within a political body, sharing a distinct opinion) is accurate; noun POS matches."},
 "SB-0096": {"disp":"clean-candidate","conf":"high","why":"attain → «досягти»; definition (obtain an object or desired result) is accurate; verb POS matches."},
 "SB-0348": {"disp":"clean-candidate","conf":"high","why":"depict → «зображувати»; definition (represent something using words, sounds, images or other means) is accurate; verb POS matches."},
 "SB-0198": {"disp":"clean-candidate","conf":"high","why":"cocktail → «коктейль»; definition (a mixed alcoholic drink) is accurate; noun POS matches."},
 "SB-0592": {"disp":"clean-candidate","conf":"high","why":"humble → «скромний»; definition (having a low opinion of oneself; not proud or arrogant) is accurate; adjective POS matches."},
 "SB-1576": {"disp":"clean-candidate","conf":"high","why":"revenue → «дохід»; definition (total income obtained from a particular source) is accurate; noun POS matches."},
 "SB-1750": {"disp":"clean-candidate","conf":"medium","why":"qualitative → «якісний»; definition (of descriptions/differences based on quality rather than quantity) conveys the sense; adjective POS matches."},
 "SB-0114": {"disp":"P2","conf":"medium","flag":"ds","cat":"circular-and-wrong-term","target":"definitionUa","value":"Кругла циліндрична посудина, довша за висотою, ніж завширшки, опукла посередині, зроблена з клепок, скріплених обручами, з плоскими днищами.","why":"barrel definition is near-circular («посудина, така як бочка») and uses «держаків» (handles) where barrel staves are «клепки»."},
 "SB-1722": {"disp":"clean-candidate","conf":"high","why":"accommodation → «проживання»; definition (lodging provided to travellers in hotels/cruise ships or to inmates) is accurate; noun POS matches."},
 "SB-1540": {"disp":"P2","conf":"medium","flag":"n","cat":"calqued-infinitive-definition","target":"definitionUa","value":"Змінити форму або структуру.","why":"alter definition «Щоб змінити форму або структуру» reads as a purpose clause ('in order to change'), a calque of the English infinitive style rather than a definition."},
 "SB-0508": {"disp":"clean-candidate","conf":"high","why":"firearm → «вогнепальна зброя»; definition (a personal weapon using explosive powder to propel a projectile) is accurate; noun POS matches."},
 "SB-0792": {"disp":"clean-candidate","conf":"high","why":"nationwide → «загальнонаціональний»; definition (extending over the whole nation) is accurate; adjective POS matches."},
 "SB-1755": {"disp":"clean-candidate","conf":"medium","why":"rigid → «жорсткий»; definition (stiff, not flexible) is accurate and contrasts with «гнучкий»; adjective POS matches."},
 "SB-0674": {"disp":"clean-candidate","conf":"high","why":"jurisdiction → «юрисдикція»; definition (the power or authority to interpret and apply the law) is accurate; noun POS matches."},
 "SB-0297": {"disp":"clean-candidate","conf":"high","why":"counselling → «консультування»; definition (professional help in understanding and resolving personal difficulties) is accurate; noun POS matches."},
 "SB-0573": {"disp":"clean-candidate","conf":"medium","why":"harvest → «урожай»; definition (bring in a crop; reap; gather) leans to the verb senses, consistent with the n.,v. POS tag."},
 "SB-0172": {"disp":"clean-candidate","conf":"high","why":"cattle → «худоба»; definition (domestic animals of the species Bos taurus and related bovines) is accurate; the Latin binomial is a legitimate scientific name, not language leakage."},
 "SB-0578": {"disp":"clean-candidate","conf":"high","why":"heritage → «спадщина»; definition (tradition or values passed down from earlier generations) is accurate; noun POS matches."},
 "SB-1544": {"disp":"P2","conf":"medium","flag":"k","cat":"ua-definition-sense-mismatch","target":"both","value":"ua: «клауза; підрядне речення» OR definitionUa about a contract/document clause","why":"clause gloss «пункт» selects the document/contract sense, but the definition describes a grammatical clause (group of words with a subject and verb); the two senses are inconsistent."},
 "SB-0204": {"disp":"clean-candidate","conf":"high","why":"collision → «зіткнення»; definition (an event where two or more bodies act on each other in a short time) is accurate; noun POS matches."},
 "SB-1322": {"disp":"clean-candidate","conf":"medium","why":"available → «доступний; наявний»; definition (readily accessible) is thin/near-circular but not misleading; adjective POS matches."},
 "SB-0313": {"disp":"clean-candidate","conf":"high","why":"crush → «розчавити»; definition (press between two hard objects, deforming or compacting) is accurate; verb POS matches."},
 "SB-1239": {"disp":"clean-candidate","conf":"high","why":"triumph → «тріумф»; definition (a decisive success after effort or conflict; a victory) is accurate; noun POS matches."},
 "SB-1332": {"disp":"clean-candidate","conf":"medium","why":"distribution → «розподіл; поширення»; definition (the act or state of distributing) is near-circular but not misleading; noun POS matches."},
 "SB-1738": {"disp":"clean-candidate","conf":"medium","why":"erosion → «ерозія»; definition (the result of wearing away, e.g. a glacier on rock or the sea on a cliff) conveys the sense despite using the cognate."},
 "SB-0388": {"disp":"clean-candidate","conf":"high","why":"dismissal → «звільнення»; definition (removal from a position; the fact or process of being dismissed from work) is accurate; noun POS matches."},
 "SB-0054": {"disp":"clean-candidate","conf":"high","why":"alliance → «альянс»; definition (a union or connection of interests between families, states or parties) is accurate; noun POS matches."},
 "SB-0711": {"disp":"clean-candidate","conf":"high","why":"line-up → «склад учасників; програма»; definition (the set of people or performers taking part in an event/team/programme) is accurate; noun POS matches."},
 "SB-0687": {"disp":"clean-candidate","conf":"high","why":"lawn → «газон»; definition (grass-covered ground, usually around a house, carefully mown) is accurate; noun POS matches."},
 "SB-0694": {"disp":"clean-candidate","conf":"high","why":"legislation → «законодавство»; definition (law enacted by a legislative or governing body) is accurate; noun POS matches."},
 "SB-0362": {"disp":"clean-candidate","conf":"high","why":"detention → «затримання»; definition (temporary custody or arrest) is accurate; noun POS matches."},
 "SB-0551": {"disp":"clean-candidate","conf":"high","why":"grave (serious) → «серйозний; тяжкий»; definition (extremely serious, dangerous or causing significant concern) is accurate; the disambiguation matches; adjective POS correct."},
 "SB-1175": {"disp":"P2","conf":"high","flag":"n","cat":"redundant-word-repetition","target":"definitionUa","value":"...призначена для рубання, колення та удару.","why":"sword definition lists «рубання» three times ('для рубання, удару, рубання та/або рубання'), a redundant repetition; the gloss «меч» is correct."},
 "SB-0513": {"disp":"clean-candidate","conf":"medium","why":"flee → «тікати»; definition (run away; escape) is accurate though near-circular with the gloss; verb POS matches."},
 "SB-0281": {"disp":"clean-candidate","conf":"high","why":"coordination → «координація»; definition (making different people or things work together toward a goal) is accurate; noun POS matches."},
 "SB-0912": {"disp":"clean-candidate","conf":"high","why":"prey → «здобич»; definition (a living creature, usually an animal, eaten by another) is accurate; noun POS matches."},
 "SB-0740": {"disp":"clean-candidate","conf":"high","why":"marine → «морський»; definition (belonging to or characteristic of the sea) is accurate; adjective POS matches."},
 "SB-0671": {"disp":"clean-candidate","conf":"high","why":"isolation → «ізоляція»; definition (the state of being isolated, separated or remote from others) is accurate; noun POS matches."},
 "SB-1144": {"disp":"clean-candidate","conf":"medium","why":"substitution → «заміна»; definition (the act or state of substituting) is near-circular but not misleading; noun POS matches."},
 "SB-0242": {"disp":"clean-candidate","conf":"high","why":"confine → «обмежити»; definition (restrict someone/something to a certain area; keep within limits) is accurate; verb POS matches."},
 "SB-0430": {"disp":"clean-candidate","conf":"medium","why":"eligible → «придатний»; definition (permitted and meeting required conditions to take part or be chosen) conveys the sense; adjective POS matches."},
 "SB-0751": {"disp":"clean-candidate","conf":"high","why":"melody → «мелодія»; definition (a sequence of notes making up a musical phrase) is accurate; noun POS matches."},
 "SB-0821": {"disp":"clean-candidate","conf":"high","why":"odds → «шанси»; definition (the ratio of the probability of an event to that of its not occurring) is accurate; noun POS matches."},
 "SB-0987": {"disp":"clean-candidate","conf":"medium","why":"remainder → «залишок»; definition (the part(s) left after some were removed) is accurate; noun POS matches."},
 "SB-1131": {"disp":"clean-candidate","conf":"high","why":"strip → «смужка»; definition (a long, narrow piece of material, land or other surface) is accurate; the disambiguation matches; noun POS correct."},
 "SB-0134": {"disp":"clean-candidate","conf":"high","why":"bleed → «кровоточити»; definition (to shed blood through a damaged blood vessel) is accurate; verb POS matches."},
 "SB-0470": {"disp":"clean-candidate","conf":"high","why":"evoke → «викликати»; definition (bring a manifestation of something to mind or imagination) is accurate; verb POS matches."},
 "SB-0132": {"disp":"clean-candidate","conf":"high","why":"blade → «лезо»; definition (the cutting part of a knife, sword, razor or tool) is accurate; noun POS matches."},
 "SB-0252": {"disp":"clean-candidate","conf":"high","why":"consecutive → «послідовний»; definition (following one after another, in turn, without a break) is accurate; adjective POS matches."},
 "SB-1456": {"disp":"clean-candidate","conf":"high","why":"layer → «шар»; definition (one thickness of a material covering a surface) is accurate; noun POS matches."},
 "SB-0115": {"disp":"clean-candidate","conf":"high","why":"bass → «бас»; definition (a low-pitched sound or a low-register instrument or voice) is accurate; the disambiguation matches; noun POS correct."},
 "SB-0882": {"disp":"P2","conf":"medium","flag":"ks","cat":"ua-definition-sense-mismatch","target":"ua","value":"портфель (інвестиційний)","why":"portfolio definition describes an investment portfolio, but the gloss «портфоліо» is the creative/works sense; the investment sense in Ukrainian is «(інвестиційний) портфель»."},
 "SB-1520": {"disp":"clean-candidate","conf":"high","why":"overall → «в цілому»; definition (in general; taking everything into account) is accurate; adverb POS matches."},
 "SB-1115": {"disp":"clean-candidate","conf":"high","why":"stabilize → «стабілізувати»; definition (to make stable) is accurate; verb POS matches."},
 "SB-1661": {"disp":"clean-candidate","conf":"high","why":"phenomenon → «явище»; definition (a thing, event or process perceived by the senses) is accurate; noun POS matches."},
 "SB-0446": {"disp":"clean-candidate","conf":"medium","why":"endorse → «схвалити»; definition (express support/approval, esp. officially; give an endorsement) is accurate; verb POS matches."},
 "SB-0016": {"disp":"clean-candidate","conf":"high","why":"accountable → «підзвітний»; definition (obliged to answer for one's actions; responsible) is accurate; adjective POS matches."},
 "SB-1340": {"disp":"clean-candidate","conf":"medium","why":"financial → «фінансовий»; definition (relating to finance) is accurate; adjective POS matches; plural agreement in the gloss-def is trivial."},
 "SB-1554": {"disp":"clean-candidate","conf":"high","why":"evolution → «еволюція»; definition (the process of development) is accurate; noun POS matches."},
 "SB-1141": {"disp":"clean-candidate","conf":"high","why":"substantial → «істотний»; definition (large in size, amount or value; considerable) is accurate; adjective POS matches."},
 "SB-1670": {"disp":"clean-candidate","conf":"high","why":"thesis → «теза»; definition (an extended scholarly work or a main claim supported by evidence) is accurate; noun POS matches."},
 "SB-0036": {"disp":"clean-candidate","conf":"high","why":"adoption → «усиновлення»; definition (accepting another's child as one's own) is accurate; noun POS matches."},
 "SB-1178": {"disp":"clean-candidate","conf":"high","why":"synthesis → «синтез»; definition (forming something complex by combining simpler things) is accurate; noun POS matches."},
 "SB-1580": {"disp":"clean-candidate","conf":"high","why":"transition → «перехід»; definition (the process of changing from one form, state or place to another) is accurate; noun POS matches."},
 "SB-0026": {"disp":"clean-candidate","conf":"high","why":"acute → «гострий»; definition (intense; keen; sharp) is accurate; adjective POS matches."},
 "SB-0610": {"disp":"clean-candidate","conf":"high","why":"inclusion → «включення»; definition (the act of including, i.e. adding something to a group or set) is accurate; noun POS matches."},
 "SB-0205": {"disp":"clean-candidate","conf":"high","why":"colonial → «колоніальний»; definition (of or relating to a colony) is accurate; adjective POS matches."},
 "SB-1566": {"disp":"clean-candidate","conf":"high","why":"monitoring → «моніторинг»; definition (continuous or regular observation to detect signals or changes) is accurate; noun POS matches."},
 "SB-0581": {"disp":"clean-candidate","conf":"medium","why":"hint → «підказка»; definition (to imply without direct statement; to give a clue) covers the n.,v. senses; POS tag matches."},
 "SB-0654": {"disp":"clean-candidate","conf":"high","why":"interfere → «заважати»; definition (to involve oneself in a way that causes disturbance) is accurate; verb POS matches."},
 "SB-0222": {"disp":"clean-candidate","conf":"high","why":"competence → «компетентність»; definition (the quality or state of being competent; ability to perform a role) is accurate; noun POS matches."},
 "SB-1610": {"disp":"clean-candidate","conf":"high","why":"index → «індекс»; definition (an alphabetical list of items and their location) is accurate; noun POS matches."},
 "SB-0631": {"disp":"clean-candidate","conf":"high","why":"insider → «інсайдер»; definition (a person with special knowledge of a group's inner workings) is accurate; noun POS matches."},
 "SB-1649": {"disp":"clean-candidate","conf":"high","why":"global → «глобальний»; definition (relating to all parts of the world) is accurate; adjective POS matches."},
 "SB-0253": {"disp":"clean-candidate","conf":"high","why":"consensus → «консенсус»; definition (general agreement among members of a group) is accurate; noun POS matches."},
 "SB-0685": {"disp":"clean-candidate","conf":"high","why":"laser → «лазер»; definition (a device producing a monochromatic coherent beam of light) is accurate; noun POS matches."},
 "SB-0693": {"disp":"clean-candidate","conf":"medium","why":"legendary → «легендарний»; definition (having incredible greatness; remarkable enough to give rise to stories) conveys the sense; adjective POS matches."},
 "SB-0257": {"disp":"clean-candidate","conf":"high","why":"consolidate → «консолідувати»; definition (to combine into a single whole; to unite or join) is accurate; verb POS matches."},
 "SB-1498": {"disp":"clean-candidate","conf":"high","why":"debate → «дебати»; definition (an argument or discussion in an orderly or formal setting, often ending in a vote) is accurate; noun POS matches."},
 "SB-1430": {"disp":"clean-candidate","conf":"high","why":"circumstances → «обставини»; definition (the conditions and facts affecting a situation or event) is accurate; plural noun POS matches."},
 "SB-1414": {"disp":"clean-candidate","conf":"high","why":"region → «область»; definition (a significant, connected part of space or surface; a tract of land) is accurate; noun POS matches."},
 "SB-0076": {"disp":"clean-candidate","conf":"high","why":"arbitrary → «довільний»; definition (based on personal discretion, not on objective distinction) is accurate; adjective POS matches."},
 "SB-0160": {"disp":"clean-candidate","conf":"high","why":"calculation → «розрахунок»; definition (the act or process of calculating) is accurate; noun POS matches."},
 "SB-1060": {"disp":"clean-candidate","conf":"high","why":"set-up → «установка»; definition (a way of organising or a set of equipment prepared for a purpose) is accurate; noun POS matches."},
 "SB-0895": {"disp":"clean-candidate","conf":"high","why":"preliminary → «попередній»; definition (in preparation for the main matter; initial, introductory) is accurate; adjective POS matches."},
 "SB-1330": {"disp":"clean-candidate","conf":"high","why":"definition → «визначення»; definition (a statement of the meaning of a word or symbol; a dictionary definition) is accurate; noun POS matches."},
 "SB-0757": {"disp":"clean-candidate","conf":"high","why":"mercy → «милосердя»; definition (forgiveness or compassion, esp. toward the less fortunate) is accurate; noun POS matches."},
 "SB-1066": {"disp":"clean-candidate","conf":"high","why":"shipping → «доставка»; definition (the transport of goods) is accurate; noun POS matches."},
 "SB-1509": {"disp":"clean-candidate","conf":"high","why":"implications → «наслідки»; definition (a possible or indirect effect or result of a decision or action) is accurate; plural noun POS matches."},
 "SB-0765": {"disp":"clean-candidate","conf":"high","why":"migration → «міграція»; definition (an instance of moving to live elsewhere for a time) is accurate; noun POS matches."},
 "SB-1302": {"disp":"clean-candidate","conf":"high","why":"widen → «розширити»; definition (to make wide or wider) is accurate; verb POS matches."},
 "SB-1184": {"disp":"clean-candidate","conf":"high","why":"tempt → «спокусити»; definition (to provoke someone toward wrongdoing, esp. by promising reward; to lure) is accurate; verb POS matches."},
 "SB-1466": {"disp":"clean-candidate","conf":"high","why":"proportion → «пропорція»; definition (an amount that is a part of a whole sum or number) is accurate; noun POS matches."},
 "SB-1582": {"disp":"clean-candidate","conf":"high","why":"version → «версія»; definition (a particular form or variation of something) is accurate; noun POS matches."},
 "SB-1497": {"disp":"clean-candidate","conf":"high","why":"cycle → «цикл»; definition (a process that returns to its start and repeats in the same sequence) is accurate; noun POS matches."},
 "SB-0370": {"disp":"clean-candidate","conf":"high","why":"dictator → «диктатор»; definition (a totalitarian leader of a country or government) is accurate; noun POS matches."},
 "SB-0078": {"disp":"clean-candidate","conf":"high","why":"archive → «архів»; definition (a place storing historical documents or media kept for historical interest) is accurate; noun POS matches."},
 "SB-0122": {"disp":"P2","conf":"medium","flag":"p","cat":"pos-mismatch-in-definition","target":"definitionUa","value":"Той, кого дуже люблять; ніжно улюблений.","why":"beloved (adj) is defined with past-tense verb forms «Дуже любив, ніжно любив» ('loved'), a POS mismatch; an adjectival definition is needed."},
 "SB-1118": {"disp":"clean-candidate","conf":"high","why":"stark → «разючий; суворий»; definition (plain-looking; barren, desolate) is accurate; adjective POS matches."},
 "SB-1459": {"disp":"clean-candidate","conf":"high","why":"maximum → «максимум»; definition (the highest limit) is accurate; noun POS matches."},
 "SB-0376": {"disp":"clean-candidate","conf":"high","why":"dip → «занурювати; опускатися»; definition (to lower into a liquid) is accurate; verb POS matches."},
 "SB-0337": {"disp":"clean-candidate","conf":"medium","why":"deficit → «дефіцит»; definition (a situation/amount where expenditure exceeds income) conveys the sense despite slightly awkward phrasing; noun POS matches."},
 "SB-1229": {"disp":"clean-candidate","conf":"high","why":"transparency → «прозорість»; definition (openness; availability for inspection) is accurate; noun POS matches."},
 "SB-1563": {"disp":"clean-candidate","conf":"high","why":"medical → «медичний»; definition (of or relating to the practice of medicine) is accurate; adjective POS matches."},
 "SB-1057": {"disp":"clean-candidate","conf":"high","why":"separation → «розділення»; definition (the act of separating two or more things, or the condition of being separated) is accurate; noun POS matches."},
 "SB-0211": {"disp":"clean-candidate","conf":"high","why":"commerce → «комерція»; definition (the exchange or buying and selling of goods, esp. large-scale trade) is accurate; noun POS matches."},
 "SB-1712": {"disp":"clean-candidate","conf":"high","why":"schedule → «графік»; definition (a procedural plan giving the sequence of operations and their planned times) is accurate; noun POS matches."},
 "SB-0393": {"disp":"clean-candidate","conf":"high","why":"disrupt → «порушувати»; definition (to throw into confusion or disorder) is accurate; verb POS matches."},
 "SB-1521": {"disp":"clean-candidate","conf":"high","why":"parallel → «паралельний»; definition (equidistant at all points) is accurate; adjective POS matches."},
 "SB-1380": {"disp":"clean-candidate","conf":"high","why":"chapter → «розділ»; definition (one of the main divisions of a published work, esp. a book) is accurate; noun POS matches."},
 "SB-0335": {"disp":"clean-candidate","conf":"high","why":"defensive → «оборонний»; definition (relating to defence, as opposed to attack) is accurate; adjective POS matches."},
 "SB-1366": {"disp":"clean-candidate","conf":"high","why":"significant → «значний; суттєвий»; definition (having a noticeable or large effect) is accurate; adjective POS matches."},
 "SB-1031": {"disp":"clean-candidate","conf":"high","why":"rotation → «обертання»; definition (the act of turning around a centre or axis) is accurate; noun POS matches."},
 "SB-0719": {"disp":"clean-candidate","conf":"high","why":"long-standing → «давній»; definition (existing for a long time; of long existence) is accurate; adjective POS matches."},
 "SB-0499": {"disp":"clean-candidate","conf":"high","why":"fate → «доля»; definition (a supposed force or divine will determining events) is accurate; noun POS matches."},
 "SB-0387": {"disp":"clean-candidate","conf":"high","why":"discrimination → «дискримінація»; definition (differential, disadvantageous treatment of a person or group by class/category) is accurate; noun POS matches."},
 "SB-0305": {"disp":"clean-candidate","conf":"medium","why":"crawl → «повзати»; definition (to move slowly on hands and knees or dragging the body) is accurate though it restates the gloss; verb POS matches."},
 "SB-1617": {"disp":"clean-candidate","conf":"medium","why":"lecture → «лекція»; definition (a spoken lesson or exposition, usually to a group) conveys the sense; noun POS matches."},
 "SB-0774": {"disp":"clean-candidate","conf":"high","why":"miracle → «чудо»; definition (an event inexplicable by natural law and thus deemed supernatural) is accurate; noun POS matches."},
 "SB-1158": {"disp":"clean-candidate","conf":"medium","why":"supervision → «нагляд»; definition (the act or instance of supervising) is near-circular but not misleading; noun POS matches."},
 "SB-0943": {"disp":"clean-candidate","conf":"medium","why":"psychiatric → «психіатричний»; definition (of or relating to psychiatry) is accurate; adjective POS matches."},
 "SB-0537": {"disp":"clean-candidate","conf":"high","why":"gambling → «азартні ігри»; definition (an activity balancing winning and losing, governed by skill and chance, with a stake) is accurate; noun POS matches."},
 "SB-0648": {"disp":"clean-candidate","conf":"high","why":"intensify → «посилити»; definition (to become or make intense or more intense) is accurate; verb POS matches."},
 "SB-0444": {"disp":"clean-candidate","conf":"high","why":"endeavour → «зусилля»; definition (an earnest or persistent attempt to achieve a goal) is accurate; noun POS matches."},
 "SB-0001": {"disp":"clean-candidate","conf":"medium","why":"abolish → «скасувати»; definition (the ending of a law, system, institution, custom or practice) conveys the sense though framed nominally; verb gloss correct."},
 "SB-0408": {"disp":"clean-candidate","conf":"high","why":"dose → «доза»; definition (a measured portion of medicine taken at one time) is accurate; noun POS matches."},
 "SB-0993": {"disp":"clean-candidate","conf":"high","why":"renew → «відновити»; definition (to make new again; to restore freshness or original condition) is accurate; verb POS matches."},
 "SB-1479": {"disp":"clean-candidate","conf":"high","why":"technical → «технічний»; definition (of or relating to technology) is accurate; adjective POS matches."},
 "SB-0107": {"disp":"clean-candidate","conf":"high","why":"backdrop → «фон»; definition (the setting or background of a staged performance) is accurate; noun POS matches."},
 "SB-0520": {"disp":"clean-candidate","conf":"high","why":"foreigner → «іноземець»; definition (a person from another country) is accurate; noun POS matches."},
 "SB-0282": {"disp":"clean-candidate","conf":"high","why":"coordinator → «координатор»; definition (one who or that which coordinates) is accurate; noun POS matches."},
 "SB-0429": {"disp":"clean-candidate","conf":"high","why":"elevate → «підняти»; definition (to raise something to a higher position) is accurate; verb POS matches."},
 "SB-1532": {"disp":"clean-candidate","conf":"high","why":"statistics → «статистика»; definition (systematic collection of measurement or observation data, often demographic) is accurate; noun POS matches."},
 "SB-0591": {"disp":"clean-candidate","conf":"high","why":"humanity → «людство»; definition (humankind; people as a group) is accurate; noun POS matches."},
 "SB-1752": {"disp":"clean-candidate","conf":"high","why":"relaxed → «розслаблений»; definition (free from tension or anxiety; at ease; unhurried) is accurate; adjective POS matches."},
 "SB-0479": {"disp":"clean-candidate","conf":"high","why":"execute → «виконувати»; definition (to carry out; to put into action) selects the IELTS-relevant 'carry out' sense; verb POS matches."},
 "SB-1606": {"disp":"clean-candidate","conf":"high","why":"gender → «стать»; definition (identification as man/woman/other and the associated social role) is accurate; noun POS matches."},
 "SB-0656": {"disp":"clean-candidate","conf":"medium","why":"interim → «тимчасовий»; definition (temporary) is thin/near-circular but not misleading; adjective POS matches."},
 "SB-0104": {"disp":"clean-candidate","conf":"high","why":"autonomy → «автономія»; definition (the right or condition of self-government; freedom to act independently) is accurate; noun POS matches."},
 "SB-0975": {"disp":"clean-candidate","conf":"medium","why":"refusal → «відмова»; definition (the act of refusing) is near-circular but not misleading; noun POS matches."},
 "SB-0847": {"disp":"clean-candidate","conf":"high","why":"parish → «парафія»; definition (an administrative part of a diocese with its own church) is accurate; noun POS matches."},
 "SB-1291": {"disp":"clean-candidate","conf":"high","why":"warrior → «воїн»; definition (a person actively engaged in battle, conflict or war; a soldier) is accurate; noun POS matches."},
 "SB-0999": {"disp":"clean-candidate","conf":"high","why":"reproduce → «відтворювати»; definition (to create offspring or organisms sexually or asexually) is accurate; verb POS matches."},
 "SB-1209": {"disp":"clean-candidate","conf":"high","why":"timber → «деревина»; definition (trees in a forest regarded as a source of wood) is accurate; noun POS matches."},
 "SB-1235": {"disp":"clean-candidate","conf":"high","why":"tribunal → «трибунал»; definition (an assembly of one or more judges to conduct judicial business; a court) is accurate; noun POS matches."},
 "SB-1010": {"disp":"clean-candidate","conf":"high","why":"respectively → «відповідно»; definition (in a relative manner, matching items in listed order) is accurate; adverb POS matches."},
 "SB-0559": {"disp":"clean-candidate","conf":"high","why":"guerrilla → «партизан»; definition (a soldier in a small independent group fighting by surprise raids) is accurate; noun POS matches."},
 "SB-0979": {"disp":"clean-candidate","conf":"high","why":"regulator → «регулятор»; definition (a device that controls or limits something) is accurate; noun POS matches."},
 "SB-0949": {"disp":"clean-candidate","conf":"high","why":"quota → «квота»; definition (a stated number or percentage serving as a maximum, minimum or target) is accurate; noun POS matches."},
 "SB-1688": {"disp":"clean-candidate","conf":"medium","why":"detected → «виявлено»; definition (being noticed) conveys the sense though the gerund phrasing is terse; consistent gloss."},
 "SB-0746": {"disp":"clean-candidate","conf":"high","why":"maximize → «максимізувати»; definition (to make as large as possible) is accurate; verb POS matches."},
 "SB-0833": {"disp":"clean-candidate","conf":"medium","why":"outing → «виїзд»; definition (a walk or excursion) conveys the sense; «прогулянка/вилазка» would also fit; noun POS matches."},
 "SB-0500": {"disp":"clean-candidate","conf":"high","why":"favourable → «сприятливий»; definition (expressing or indicating favour; approving, encouraging) is accurate; adjective POS matches."},
 "SB-1244": {"disp":"clean-candidate","conf":"high","why":"turnout → «явка»; definition (the number or proportion of people attending or participating, esp. in elections) is accurate; noun POS matches."},
 "SB-0065": {"disp":"clean-candidate","conf":"high","why":"analogy → «аналогія»; definition (a similarity or equivalence between situations used as a basis for explanation) is accurate; noun POS matches."},
 "SB-0435": {"disp":"clean-candidate","conf":"medium","why":"embed → «вбудовувати»; definition (to encapsulate within another document or data file) is accurate for the data sense; verb POS matches."},
 "SB-1076": {"disp":"clean-candidate","conf":"high","why":"sketch → «ескіз»; definition (a quickly made freehand drawing, not a finished work) is accurate; noun POS matches."},
 "SB-0743": {"disp":"clean-candidate","conf":"high","why":"massacre → «різанина»; definition (the killing of a significant number with little resistance and indiscriminate violence) is accurate; noun POS matches."},
 "SB-0590": {"disp":"clean-candidate","conf":"high","why":"humanitarian → «гуманітарний»; definition (relating to human welfare) is accurate; adjective POS matches."},
 "SB-1662": {"disp":"clean-candidate","conf":"high","why":"priority → «пріоритет»; definition (the relative importance of an item) is accurate; noun POS matches."},
 "SB-0635": {"disp":"clean-candidate","conf":"high","why":"instinct → «інстинкт»; definition (a natural or innate impulse or behaviour) is accurate; noun POS matches."},
 "SB-1723": {"disp":"clean-candidate","conf":"high","why":"analogous → «аналогічний»; definition (corresponding to something else; having a similarity or like proportion) is accurate; adjective POS matches."},
 "SB-1686": {"disp":"clean-candidate","conf":"high","why":"currency → «валюта»; definition (money or other items used to conduct transactions) is accurate; noun POS matches."},
 "SB-1564": {"disp":"clean-candidate","conf":"high","why":"mental → «психічний»; definition (relating to the mind or the individual's full emotional and intellectual response) is accurate; adjective POS matches."},
 "SB-1692": {"disp":"clean-candidate","conf":"high","why":"eventually → «зрештою»; definition (in the end; later, esp. after a long time or series of problems) is accurate; adverb POS matches."},
 "SB-1438": {"disp":"clean-candidate","conf":"high","why":"core → «ядро»; definition (the essential part of a thing surrounded by other essential things) is accurate; noun POS matches."},
 "SB-1191": {"disp":"clean-candidate","conf":"high","why":"terrific → «чудовий»; definition (extremely good; excellent, amazing) is accurate; adjective POS matches."},
 "SB-0379": {"disp":"clean-candidate","conf":"high","why":"directory → «каталог»; definition (a structured list of file names and attributes on a storage device) is accurate for the computing sense; noun POS matches."},
 "SB-1382": {"disp":"clean-candidate","conf":"high","why":"community → «громада»; definition (a group sharing characteristics such as language, law, religion or tradition) is accurate; noun POS matches."},
 "SB-1658": {"disp":"clean-candidate","conf":"high","why":"media → «ЗМІ»; definition (the means and institutions of publishing and broadcasting information) is accurate; noun POS matches."},
 "SB-0700": {"disp":"clean-candidate","conf":"high","why":"lesser → «менший»; definition (smaller in size, value or importance of two things) is accurate; adjective POS matches."},
 "SB-0186": {"disp":"clean-candidate","conf":"high","why":"citizenship → «громадянство»; definition (the state or status of being a citizen) is accurate; noun POS matches."},
 "SB-0768": {"disp":"clean-candidate","conf":"high","why":"mill → «млин»; definition (a device for grinding substances such as grain or seeds) is accurate; noun POS matches."},
 "SB-0400": {"disp":"clean-candidate","conf":"high","why":"disturbing → «тривожний»; definition (causing distress or worry; upsetting or alarming) is accurate; adjective POS matches."},
 "SB-1432": {"disp":"clean-candidate","conf":"high","why":"components → «компоненти»; definition (a smaller self-contained part of a larger entity) is accurate; plural noun POS matches."},
 "SB-1303": {"disp":"P2","conf":"high","flag":"u","cat":"dangling-punctuation","target":"definitionUa","value":"Особа, яка втратила чоловіка/дружину і не одружилася повторно.","why":"widow definition ends with a dangling colon «...повторно:» and no following text; content otherwise conveys the sense."},
 "SB-0088": {"disp":"clean-candidate","conf":"medium","why":"assault → «напад»; definition (to attack, physically or figuratively) covers the n.,v. senses; POS tag matches."},
 "SB-0795": {"disp":"clean-candidate","conf":"high","why":"neighbouring → «сусідній»; definition (located next to or near another place or territory) is accurate; adjective POS matches."},
 "SB-1719": {"disp":"clean-candidate","conf":"high","why":"virtually → «практично»; definition (almost, but not quite) is accurate; adverb POS matches."},
}
