# -*- coding: utf-8 -*-
"""Pass-B chunk 3 row-level judgments (hand-authored, blind). Schema: see chunk1.py."""

JUDGMENTS = {
 "SB-1280": {"disp":"clean-candidate","conf":"high","why":"violate → «порушувати»; definition (breach or disregard a rule or convention) is accurate; verb POS matches."},
 "SB-0093": {"disp":"clean-candidate","conf":"high","why":"assurance → «запевнення»; definition (the act of assuring; a statement meant to inspire confidence) is accurate; noun POS matches."},
 "SB-1647": {"disp":"clean-candidate","conf":"high","why":"finite → «кінцевий»; definition (having a definite limit, end or bounded quantity) is accurate; adjective POS matches."},
 "SB-1208": {"disp":"clean-candidate","conf":"high","why":"tighten → «затягувати»; definition (to make tighter/denser) is accurate; verb POS matches."},
 "SB-1122": {"disp":"clean-candidate","conf":"high","why":"stereotype → «стереотип»; definition (a widely held, oversimplified image of a person or group) is accurate; noun POS matches."},
 "SB-0856": {"disp":"clean-candidate","conf":"medium","why":"pathway → «шлях»; definition (a footpath or other track) conveys the sense though it restates «шлях/доріжка»; noun POS matches."},
 "SB-0338": {"disp":"clean-candidate","conf":"high","why":"defy → «кинути виклик»; definition (to refuse to obey) is accurate; verb POS matches."},
 "SB-1363": {"disp":"clean-candidate","conf":"high","why":"role → «роль»; definition (the expected behaviour of an individual in society) is accurate; noun POS matches."},
 "SB-1434": {"disp":"clean-candidate","conf":"medium","why":"constant → «постійний»; definition (unchanging in time or space) is accurate though it restates the gloss; adjective POS matches."},
 "SB-1558": {"disp":"clean-candidate","conf":"medium","why":"fundamental → «фундаментальний»; definition (basic; extremely important) conveys the sense; adjective POS matches."},
 "SB-1108": {"disp":"clean-candidate","conf":"high","why":"spotlight → «центр уваги; прожектор»; definition (the focus of attention; the main or most important part) is accurate; noun POS matches."},
 "SB-0360": {"disp":"clean-candidate","conf":"high","why":"detain → «затримувати»; definition (prevent someone from proceeding by holding them back or claiming their attention) is accurate; verb POS matches."},
 "SB-1400": {"disp":"clean-candidate","conf":"high","why":"institute → «інститут»; definition (an organisation founded to promote a cause) is accurate; noun POS matches."},
 "SB-0492": {"disp":"clean-candidate","conf":"high","why":"extremist → «екстреміст»; definition (a person holding and advocating extreme views; a radical or fanatic) is accurate; noun POS matches."},
 "SB-0180": {"disp":"clean-candidate","conf":"high","why":"charm → «чарівність»; definition (the ability to persuade, please or delight) is accurate; noun POS matches."},
 "SB-0022": {"disp":"clean-candidate","conf":"medium","why":"acquisition → «придбання»; definition (the act or process of acquiring) is near-circular but not misleading; noun POS matches."},
 "SB-0845": {"disp":"clean-candidate","conf":"high","why":"parameter → «параметр»; definition (a value held constant within an experiment but varied across versions) is accurate; noun POS matches."},
 "SB-1598": {"disp":"clean-candidate","conf":"high","why":"edition → «видання»; definition (the whole number of copies of a work printed and issued at one time) is accurate; noun POS matches."},
 "SB-1443": {"disp":"P2","conf":"high","flag":"u","cat":"truncated-definition","target":"definitionUa","value":"Оригінальний або офіційний запис, що використовується як основа, доказ або підтвердження чогось; будь-який письмовий носій інформації.","why":"document definition is truncated, ending «...має відношення до такого до...»; it also repeats «документ» several times. Gloss «документ» is correct."},
 "SB-1252": {"disp":"clean-candidate","conf":"high","why":"unprecedented → «безпрецедентний»; definition (never seen, done or felt before; without precedent) is accurate; adjective POS matches."},
 "SB-0936": {"disp":"clean-candidate","conf":"medium","why":"prosperity → «процвітання»; definition (the condition of prospering: good fortune and wealth) conveys the sense; noun POS matches."},
 "SB-0445": {"disp":"clean-candidate","conf":"high","why":"endless → «нескінченний»; definition (having no end) is accurate; adjective POS matches."},
 "SB-1613": {"disp":"clean-candidate","conf":"medium","why":"input → «введення»; definition (data entered into a process to shape or influence its result) conveys the sense despite slightly odd phrasing; noun POS matches."},
 "SB-0071": {"disp":"clean-candidate","conf":"high","why":"appetite → «апетит»; definition (a desire to eat food or drink) is accurate; noun POS matches."},
 "SB-0695": {"disp":"clean-candidate","conf":"high","why":"legislative → «законодавчий»; definition (making laws or having the power to make laws) is accurate; adjective POS matches."},
 "SB-1705": {"disp":"clean-candidate","conf":"high","why":"plus → «плюс»; definition (a positive quantity) is accurate; noun POS matches."},
 "SB-1155": {"disp":"clean-candidate","conf":"high","why":"superb → «чудовий»; definition (first-class; of the highest quality; exceptionally good) is accurate; adjective POS matches."},
 "SB-0937": {"disp":"clean-candidate","conf":"high","why":"protective → «захисний»; definition (serving or intended to protect) is accurate; adjective POS matches."},
 "SB-0284": {"disp":"clean-candidate","conf":"high","why":"copper → «мідь»; definition (a red-brown metal, symbol Cu, atomic number 29) is factually correct; noun POS matches."},
 "SB-1311": {"disp":"clean-candidate","conf":"high","why":"worthwhile → «вартий»; definition (good and important enough to spend time, effort or money on) is accurate; adjective POS matches."},
 "SB-0886": {"disp":"clean-candidate","conf":"high","why":"practitioner → «практик»; definition (a person engaged in a profession or art, esp. law or medicine) is accurate; noun POS matches."},
 "SB-0200": {"disp":"clean-candidate","conf":"high","why":"coincide → «збігатися»; definition (to occur at the same time) is accurate; verb POS matches."},
 "SB-0457": {"disp":"clean-candidate","conf":"high","why":"enterprise → «підприємство»; definition (a company, business, organisation or other purposeful activity) is accurate; noun POS matches."},
 "SB-0864": {"disp":"clean-candidate","conf":"high","why":"personnel → «персонал»; definition (the group of people in an organisation, e.g. employees or military members) is accurate; noun POS matches."},
 "SB-1063": {"disp":"clean-candidate","conf":"high","why":"shatter → «розбити»; definition (to break something forcefully into pieces) is accurate; verb POS matches."},
 "SB-0887": {"disp":"clean-candidate","conf":"high","why":"preach → «проповідувати»; definition (to proclaim by public discourse; to deliver in a sermon) is accurate; verb POS matches."},
 "SB-0342": {"disp":"clean-candidate","conf":"high","why":"demon → «демон»; definition (an evil supernatural spirit) is accurate; noun POS matches."},
 "SB-1733": {"disp":"clean-candidate","conf":"high","why":"conversely → «навпаки»; definition (from another point of view; on the other hand) is accurate; adverb POS matches."},
 "SB-0472": {"disp":"clean-candidate","conf":"medium","why":"exaggerate → «перебільшувати»; definition (to overstate; to describe more than the fact) is accurate though near-circular; verb POS matches."},
 "SB-0040": {"disp":"clean-candidate","conf":"high","why":"affection → «прихильність»; definition (a feeling of love or strong attachment) is accurate; noun POS matches."},
 "SB-1258": {"disp":"clean-candidate","conf":"high","why":"utilize → «використовувати»; definition (to put something to practical use for a purpose) is accurate; verb POS matches."},
 "SB-0053": {"disp":"clean-candidate","conf":"high","why":"allegedly → «нібито»; definition (according to someone's claim) is accurate; adverb POS matches."},
 "SB-0854": {"disp":"clean-candidate","conf":"high","why":"patch → «латка»; definition (a piece of cloth sewn or fixed onto clothing to repair or reinforce it) is accurate; noun POS matches."},
 "SB-0977": {"disp":"clean-candidate","conf":"high","why":"regardless → «незалежно»; definition (paying no attention to; ignoring) is accurate; adverb POS matches."},
 "SB-1001": {"disp":"clean-candidate","conf":"high","why":"republic → «республіка»; definition (a state where sovereignty rests with the people or their representatives, not a monarch) is accurate; noun POS matches."},
 "SB-1042": {"disp":"clean-candidate","conf":"high","why":"sceptical → «скептичний»; definition (inclined to doubt the truth or validity of a claim) is accurate; adjective POS matches."},
 "SB-0697": {"disp":"clean-candidate","conf":"high","why":"legitimate → «законний»; definition (in accordance with law or established legal forms and requirements) is accurate; adjective POS matches."},
 "SB-0567": {"disp":"clean-candidate","conf":"medium","why":"handling → «поводження»; definition (touching, controlling, managing or using with the hands) conveys the sense despite the verb-framed phrasing; noun POS matches."},
 "SB-0806": {"disp":"clean-candidate","conf":"high","why":"non-profit → «неприбутковий»; definition (an organisation or activity whose main aim is not making profit) is accurate; adjective POS matches."},
 "SB-0561": {"disp":"clean-candidate","conf":"high","why":"guilt → «вина»; definition (responsibility for wrongful acts) is accurate; noun POS matches."},
 "SB-1353": {"disp":"clean-candidate","conf":"high","why":"occur → «відбуватися; траплятися»; definition (to happen or take place) is accurate; verb POS matches."},
 "SB-1683": {"disp":"clean-candidate","conf":"high","why":"conformity → «відповідність»; definition (the state of conforming, following a set of rules, norms or a standard) is accurate; noun POS matches."},
 "SB-0365": {"disp":"clean-candidate","conf":"high","why":"devil → «диявол»; definition (the chief devil; Satan) is accurate; noun POS matches."},
 "SB-0752": {"disp":"clean-candidate","conf":"high","why":"memo → «записка»; definition (a short note; a memorandum) is accurate; noun POS matches."},
 "SB-0600": {"disp":"clean-candidate","conf":"high","why":"immense → «величезний»; definition (huge, gigantic, very large) is accurate; adjective POS matches."},
 "SB-0714": {"disp":"clean-candidate","conf":"high","why":"literacy → «грамотність»; definition (the ability to read and write) is accurate; noun POS matches."},
 "SB-0715": {"disp":"clean-candidate","conf":"high","why":"liver → «печінка»; definition (a large organ that stores and metabolises nutrients, destroys toxins and produces bile) is accurate; noun POS matches."},
 "SB-0984": {"disp":"clean-candidate","conf":"medium","why":"relevance → «релевантність»; definition (the property or state of being relevant or pertinent) is near-circular but not misleading; noun POS matches."},
 "SB-1653": {"disp":"clean-candidate","conf":"high","why":"identical → «однакові»; definition (having complete similarity, exactly the same set of characteristics; indistinguishable) is accurate; adjective POS matches."},
 "SB-0983": {"disp":"clean-candidate","conf":"medium","why":"rejection → «відмова»; definition (the act of rejecting) is accurate; noun POS matches; overlap with refusal is acceptable."},
 "SB-1135": {"disp":"clean-candidate","conf":"high","why":"stumble → «спотикатися»; definition (to trip or fall; to walk clumsily) is accurate; verb POS matches."},
 "SB-0460": {"disp":"clean-candidate","conf":"high","why":"entity → «сутність»; definition (something existing as a distinct unit, often used for organisations without physical form) is accurate; noun POS matches."},
 "SB-1358": {"disp":"clean-candidate","conf":"high","why":"procedure → «процедура»; definition (a specific way of performing a task) is accurate; noun POS matches."},
 "SB-0210": {"disp":"clean-candidate","conf":"high","why":"commentator → «коментатор»; definition (a person giving a live description of a public event, esp. sport, for a media audience) is accurate; noun POS matches."},
 "SB-1371": {"disp":"P2","conf":"high","flag":"u","cat":"truncated-definition","target":"definitionUa","value":"Послідовне твердження або набір ідей, що пояснюють спостережувані факти чи явища та правильно передбачають нові.","why":"theory definition is truncated, ending «...відомого чи спос...»; the gloss «теорія» is correct but the learner sees an unfinished sentence."},
 "SB-1136": {"disp":"clean-candidate","conf":"high","why":"stun → «оглушити»; definition (to incapacitate, esp. causing disorientation or loss of consciousness) is accurate; verb POS matches."},
 "SB-0190": {"disp":"clean-candidate","conf":"high","why":"clash → «зіткнення»; definition (opposition or contradiction between conflicting interests, views or aims) is accurate; noun POS matches."},
 "SB-1724": {"disp":"clean-candidate","conf":"medium","why":"anticipated → «очікуваний»; definition (expected; planned) conveys the sense despite terse phrasing; consistent gloss."},
 "SB-1418": {"disp":"clean-candidate","conf":"high","why":"resources → «ресурси»; definition (something used to achieve a goal, e.g. raw materials or personnel) is accurate; plural noun POS matches."},
 "SB-0039": {"disp":"clean-candidate","conf":"high","why":"aesthetic → «естетичний»; definition (concerned with beauty, artistic effect or appearance) is accurate; adjective POS matches."},
 "SB-1087": {"disp":"clean-candidate","conf":"medium","why":"socialist → «соціалістичний»; definition (relating to, supporting or advocating socialism) conveys the sense; adjective POS matches."},
 "SB-0129": {"disp":"clean-candidate","conf":"high","why":"biography → «біографія»; definition (the life story of a person, esp. published) is accurate; noun POS matches."},
 "SB-1190": {"disp":"clean-candidate","conf":"high","why":"terrain → «місцевість; рельєф»; definition (a tract of land or its features) is accurate; noun POS matches."},
 "SB-1058": {"disp":"clean-candidate","conf":"medium","why":"serial → «серійний»; definition (relating to or arranged in a series/row) conveys the sense; adjective POS matches."},
 "SB-0718": {"disp":"clean-candidate","conf":"high","why":"logic → «логіка»; definition (a method of linear, step-by-step reasoning; the basis of the scientific method) is accurate; noun POS matches."},
 "SB-1455": {"disp":"clean-candidate","conf":"high","why":"interaction → «взаємодія»; definition (a conversation or exchange between people) is accurate; noun POS matches."},
 "SB-0478": {"disp":"clean-candidate","conf":"high","why":"exclusively → «виключно»; definition (to the exclusion of anything or anyone else) is accurate; adverb POS matches."},
 "SB-0361": {"disp":"clean-candidate","conf":"high","why":"detection → «виявлення»; definition (the act or process of detecting or discovering something new, hidden or disguised) is accurate; noun POS matches."},
 "SB-1401": {"disp":"clean-candidate","conf":"high","why":"investment → «інвестиції»; definition (placing capital expecting income or profit from its use or rise in value) is accurate; noun POS matches."},
 "SB-0518": {"disp":"clean-candidate","conf":"medium","why":"fluid → «рідина»; definition (a liquid, as opposed to solid or gas) selects the liquid sense consistent with the gloss; noun POS matches."},
 "SB-1277": {"disp":"clean-candidate","conf":"high","why":"vice → «порок»; definition (bad or immoral behaviour) is accurate; noun POS matches."},
 "SB-0924": {"disp":"clean-candidate","conf":"medium","why":"productivity → «продуктивність»; definition (the state of being productive, fruitful or efficient) is near-circular but not misleading; noun POS matches."},
 "SB-0588": {"disp":"clean-candidate","conf":"high","why":"hostile → «ворожий»; definition (unfriendly; befitting an enemy; showing ill will and intent to obstruct or harm) is accurate; adjective POS matches."},
 "SB-0553": {"disp":"clean-candidate","conf":"high","why":"grid → «сітка»; definition (an electricity-delivery system of substations, transformers and generators connected by wire) is accurate; noun POS matches."},
 "SB-1539": {"disp":"clean-candidate","conf":"high","why":"academic → «академічний»; definition (belonging to an academy or higher-education institution or a scholarly society) is accurate; adjective POS matches."},
 "SB-1759": {"disp":"clean-candidate","conf":"medium","why":"supplementary → «додатковий»; definition (additional; added to provide what is needed) conveys the sense though it restates the gloss; adjective POS matches."},
 "SB-1368": {"disp":"clean-candidate","conf":"high","why":"source → «джерело»; definition (the person, place or thing from which something comes or is obtained) is accurate; noun POS matches."},
 "SB-0436": {"disp":"clean-candidate","conf":"high","why":"embody → «втілювати»; definition (to represent in physical or concrete form; to personify) is accurate; verb POS matches."},
 "SB-0188": {"disp":"clean-candidate","conf":"high","why":"civilian → «цивільний»; definition (a person in civil life, esp. not an active member of the armed forces) is accurate; n./adj. POS matches."},
 "SB-1139": {"disp":"clean-candidate","conf":"high","why":"subscription → «підписка»; definition (access to a resource for a period of time, usually paid) is accurate; noun POS matches."},
 "SB-1114": {"disp":"clean-candidate","conf":"high","why":"stability → «стабільність»; definition (the condition of being stable or in equilibrium, hence resistant to change) is accurate; noun POS matches."},
 "SB-0453": {"disp":"clean-candidate","conf":"high","why":"enquire → «запитувати»; definition (to ask for information or pose a question to find something out) is accurate; verb POS matches."},
 "SB-0605": {"disp":"clean-candidate","conf":"high","why":"inability → «неспроможність»; definition (lack of ability to do something; incapacity) is accurate; noun POS matches."},
 "SB-0892": {"disp":"clean-candidate","conf":"high","why":"predominantly → «переважно»; definition (in a predominant manner; most often or by a large margin) is accurate; adverb POS matches."},
 "SB-0528": {"disp":"clean-candidate","conf":"high","why":"franchise → «франшиза»; definition (permission granted by a company to sell or distribute its goods/services in a territory) is accurate; noun POS matches."},
 "SB-0323": {"disp":"clean-candidate","conf":"high","why":"dawn → «світанок»; definition (the period of morning twilight just before sunrise) is accurate; noun POS matches."},
 "SB-0314": {"disp":"clean-candidate","conf":"high","why":"crystal → «кристал»; definition (a solid whose atoms/molecules have long-range order in a periodic 3D structure) is accurate; noun POS matches."},
 "SB-0775": {"disp":"clean-candidate","conf":"high","why":"misery → «страждання»; definition (great unhappiness; intense bodily or mental pain; distress; grief) is accurate; noun POS matches."},
 "SB-0098": {"disp":"clean-candidate","conf":"high","why":"attorney → «адвокат»; definition (a lawyer who advises or represents others in legal matters as a profession) is accurate; noun POS matches."},
 "SB-0741": {"disp":"clean-candidate","conf":"high","why":"marketplace → «ринок»; definition (the world of commerce and trade) is accurate for the figurative sense; noun POS matches."},
 "SB-1091": {"disp":"clean-candidate","conf":"high","why":"solidarity → «солідарність»; definition (bonds of unity around a common goal or against a common enemy; mutual support in a group) is accurate; noun POS matches."},
 "SB-0503": {"disp":"clean-candidate","conf":"medium","why":"fibre → «клітковина»; definition (dietary fibre) selects the nutrition sense consistent with the gloss; noun POS matches."},
 "SB-1342": {"disp":"clean-candidate","conf":"high","why":"identified → «визначений; ідентифікований»; definition (recognised or determined as a specific person, thing or phenomenon) is accurate; consistent gloss."},
 "SB-0825": {"disp":"clean-candidate","conf":"medium","why":"opt → «обирати; робити вибір»; definition (to choose; to select) is accurate though it restates the gloss; verb POS matches."},
 "SB-0075": {"disp":"clean-candidate","conf":"high","why":"appreciation → «вдячність»; definition (a fair estimation of quality/value; recognition of excellence; gratitude and esteem) is accurate; noun POS matches."},
 "SB-1009": {"disp":"clean-candidate","conf":"high","why":"respective → «відповідний»; definition (relating to particular persons or things, each to each; particular; own) is accurate; adjective POS matches."},
 "SB-1533": {"disp":"clean-candidate","conf":"high","why":"status → «статус»; definition (a person's condition, position or standing relative to others) is accurate; noun POS matches."},
 "SB-0176": {"disp":"clean-candidate","conf":"high","why":"cemetery → «кладовище»; definition (a place where the dead are buried; a graveyard or memorial park) is accurate; noun POS matches."},
 "SB-0419": {"disp":"clean-candidate","conf":"high","why":"earnings → «заробіток»; definition (wages, money earned, income) is accurate; noun POS matches."},
 "SB-0790": {"disp":"clean-candidate","conf":"high","why":"mutual → «взаємний»; definition (having the same relation, one to another) is accurate; adjective POS matches."},
 "SB-0056": {"disp":"clean-candidate","conf":"high","why":"allocation → «виділення»; definition (the process of distributing things, esp. money or other resources) is accurate; noun POS matches."},
 "SB-1639": {"disp":"clean-candidate","conf":"high","why":"couple → «пара»; definition (two partners in a romantic or sexual relationship) is accurate; noun POS matches."},
 "SB-1089": {"disp":"clean-candidate","conf":"medium","why":"solely → «виключно»; definition (alone; exclusively) is accurate though it restates the gloss; adverb POS matches."},
 "SB-1020": {"disp":"clean-candidate","conf":"high","why":"revive → «оживити»; definition (figuratively, to bring out of decline/neglect/obscurity; to make active again; to resuscitate) is accurate; verb POS matches."},
 "SB-0769": {"disp":"clean-candidate","conf":"medium","why":"minimal → «мінімальний»; definition (the smallest possible amount, quantity or degree) conveys the sense despite noun-framing; adjective POS matches."},
 "SB-1568": {"disp":"clean-candidate","conf":"high","why":"notion → «поняття»; definition (a mental perception of anything knowable or imaginable; an idea, concept) is accurate; noun POS matches."},
 "SB-1025": {"disp":"clean-candidate","conf":"high","why":"rip → «рвати; розривати»; definition (to separate parts, esp. of something fragile like paper or fabric, by cutting or tearing) is accurate; verb POS matches."},
 "SB-1601": {"disp":"clean-candidate","conf":"medium","why":"exceed → «перевищувати»; definition (to go beyond a limit; to surpass) is accurate; verb POS matches."},
 "SB-1476": {"disp":"clean-candidate","conf":"medium","why":"specified → «зазначено»; definition (carefully explained) conveys the sense though 'named explicitly' would be more precise; consistent gloss."},
 "SB-0326": {"disp":"clean-candidate","conf":"high","why":"decision-making → «прийняття рішень»; definition (the process of analysing possibilities and choosing one) is accurate; noun POS matches."},
 "SB-1678": {"disp":"clean-candidate","conf":"high","why":"ambiguous → «неоднозначний»; definition (open to many interpretations) is accurate; adjective POS matches."},
 "SB-1399": {"disp":"clean-candidate","conf":"high","why":"injury → «травма»; definition (damage to the body of a living being) is accurate; noun POS matches."},
 "SB-1473": {"disp":"clean-candidate","conf":"high","why":"sequence → «послідовність»; definition (a set of things placed in a set order; a series) is accurate; noun POS matches."},
 "SB-1163": {"disp":"clean-candidate","conf":"high","why":"suppress → «придушити»; definition (to put an end to, esp. by force; to crush, destroy; to forbid, subdue) is accurate; verb POS matches."},
 "SB-1534": {"disp":"clean-candidate","conf":"high","why":"stress → «стрес»; definition (emotional pressure felt by a person or other animal) is accurate; noun POS matches."},
 "SB-0442": {"disp":"clean-candidate","conf":"high","why":"encouragement → «заохочення»; definition (words or actions that raise someone's confidence) is accurate; noun POS matches."},
 "SB-1049": {"disp":"clean-candidate","conf":"high","why":"segment → «сегмент»; definition (one of the parts into which a body is naturally divided; a section, portion) is accurate; noun POS matches."},
 "SB-0136": {"disp":"clean-candidate","conf":"high","why":"bless → «благословляти»; definition (to invoke divine favour) is accurate; verb POS matches."},
 "SB-1246": {"disp":"clean-candidate","conf":"high","why":"twist → «крутити»; definition (to turn the ends of something, usually thread or rope, in opposite directions, often with force) is accurate; v.,n. POS matches."},
 "SB-0664": {"disp":"clean-candidate","conf":"high","why":"invisible → «невидимий»; definition (impossible to see; out of view; not seen) is accurate; adjective POS matches."},
 "SB-0238": {"disp":"clean-candidate","conf":"medium","why":"condemn → «засуджувати»; definition (to criticise or censure sharply) is accurate though it restates the gloss; verb POS matches."},
 "SB-1373": {"disp":"clean-candidate","conf":"high","why":"achieve → «досягти»; definition (to carry out successfully; to accomplish) is accurate; verb POS matches."},
 "SB-1369": {"disp":"clean-candidate","conf":"high","why":"specific → «конкретний; специфічний»; definition (explicit or definite) is accurate; adjective POS matches."},
 "SB-1511": {"disp":"clean-candidate","conf":"medium","why":"internal → «внутрішній»; definition (of or located inside) conveys the sense despite the calqued 'З або' opening; adjective POS matches."},
 "SB-1124": {"disp":"P2","conf":"medium","flag":"kn","cat":"imprecise-gloss","target":"ua","value":"розмішувати; помішувати","why":"the definition describes stirring the particles of a liquid, but the gloss «ворушити» (to move/stir slightly) is imprecise for that sense; «помішувати/розмішувати» fits the liquid-stirring meaning."},
 "SB-0259": {"disp":"clean-candidate","conf":"high","why":"constitute → «становити»; definition (to make up something as its parts; to form or formally establish) is accurate; verb POS matches."},
 "SB-1041": {"disp":"clean-candidate","conf":"high","why":"scattered → «розкиданий»; definition (dispersed, broken into disconnected units) is accurate; adjective POS matches."},
 "SB-1241": {"disp":"clean-candidate","conf":"high","why":"troubled → «стурбований»; definition (anxious, worried, tormented by cares) is accurate; adjective POS matches."},
 "SB-1594": {"disp":"clean-candidate","conf":"medium","why":"capable → «здатний»; definition (skilled and effective; having the abilities required for a task) conveys the sense; adjective POS matches."},
 "SB-0285": {"disp":"clean-candidate","conf":"high","why":"copyright → «авторське право»; definition (the legal right determining who may publish, copy and distribute a work) is accurate; noun POS matches."},
 "SB-0672": {"disp":"clean-candidate","conf":"high","why":"judicial → «судовий»; definition (relating to the administration of justice) is accurate; adjective POS matches."},
 "SB-0352": {"disp":"clean-candidate","conf":"medium","why":"deprive → «позбавляти»; definition (to take something away from someone and keep it from them; to deny) is accurate; verb POS matches."},
 "SB-1263": {"disp":"clean-candidate","conf":"high","why":"vanish → «зникати»; definition (to become invisible or disappear from view imperceptibly) is accurate; verb POS matches."},
 "SB-0042": {"disp":"clean-candidate","conf":"high","why":"aggression → «агресія»; definition (hostile or destructive behaviour or actions) is accurate; noun POS matches."},
 "SB-0963": {"disp":"clean-candidate","conf":"high","why":"rear → «задній»; definition (the back or rearmost part; that which is behind or last in order) is accurate; adj.,n. POS matches."},
 "SB-1623": {"disp":"clean-candidate","conf":"high","why":"preceding → «попередній»; definition (occurring before something else in time, place, rank or sequence) is accurate; adjective POS matches."},
 "SB-0585": {"disp":"clean-candidate","conf":"high","why":"horizon → «горизонт»; definition (the visible horizontal line where sky appears to meet the ground in the distance) is accurate; noun POS matches."},
 "SB-1481": {"disp":"clean-candidate","conf":"high","why":"technology → «технології»; definition (useful skills or mechanisms people have developed, incl. in pre-scientific eras) is accurate; noun POS matches."},
 "SB-0368": {"disp":"clean-candidate","conf":"high","why":"diagnosis → «діагноз»; definition (the process or instance of identifying the nature and cause of a medical condition) is accurate; noun POS matches."},
 "SB-1690": {"disp":"clean-candidate","conf":"medium","why":"displacement → «переміщення»; definition (the act or state of displacing; putting out of place) conveys the sense; noun POS matches."},
 "SB-1225": {"disp":"clean-candidate","conf":"high","why":"transcript → «стенограма»; definition (something transcribed; a written copy in the same words as the original) is accurate; noun POS matches."},
 "SB-0900": {"disp":"clean-candidate","conf":"high","why":"prescription → «рецепт»; definition (a written order from an authorised practitioner for medicine or treatment such as lenses) is accurate; noun POS matches."},
 "SB-0511": {"disp":"clean-candidate","conf":"high","why":"flaw → «недолік»; definition (a defect, error or imperfection, esp. a hidden one) is accurate; noun POS matches."},
 "SB-1212": {"disp":"clean-candidate","conf":"high","why":"tolerance → «толерантність»; definition (the ability or practice of tolerating; acceptance of others' beliefs; absence of bigotry) is accurate; noun POS matches."},
 "SB-0904": {"disp":"clean-candidate","conf":"high","why":"presidency → «президентство»; definition (the office or role of a president) is accurate; noun POS matches."},
 "SB-1542": {"disp":"clean-candidate","conf":"high","why":"capacity → «місткість»; definition (the ability to hold, receive or absorb) is accurate; noun POS matches."},
 "SB-1627": {"disp":"P2","conf":"high","flag":"n","cat":"redundant-word-repetition","target":"definitionUa","value":"Компанія, що належить материнській або холдинговій компанії; також дочірня компанія.","why":"subsidiary definition repeats «дочірньою компанією або дочірньою компанією» (identical phrase either side of 'або'), a redundant repetition; the gloss is correct."},
 "SB-0455": {"disp":"clean-candidate","conf":"high","why":"enrol → «зарахувати»; definition (to officially register or sign up for a course, programme or institution) is accurate; verb POS matches."},
 "SB-1709": {"disp":"clean-candidate","conf":"medium","why":"reinforced → «посилений»; definition (was or contains reinforcement) conveys the sense despite terse phrasing; consistent gloss."},
 "SB-1749": {"disp":"clean-candidate","conf":"high","why":"portion → «частина»; definition (an allotted amount) is accurate; noun POS matches."},
 "SB-0055": {"disp":"clean-candidate","conf":"high","why":"allocate → «виділити»; definition (to set aside for a particular purpose) is accurate; verb POS matches."},
 "SB-0489": {"disp":"clean-candidate","conf":"high","why":"exploitation → «експлуатація»; definition (improper use of something for selfish ends) is accurate; noun POS matches."},
 "SB-1699": {"disp":"clean-candidate","conf":"high","why":"inevitably → «неминуче»; definition (in a way that cannot be avoided or prevented) is accurate; adverb POS matches."},
 "SB-0084": {"disp":"clean-candidate","conf":"medium","why":"ash → «попіл»; definition (the residue of a fire) is accurate; «Тверді» would be more precise than «Суцільні» but the sense is clear; noun POS matches."},
 "SB-0748": {"disp":"clean-candidate","conf":"high","why":"meantime → «тим часом»; definition (the time spent waiting for another event; the time in between) is accurate; noun POS matches."},
 "SB-1337": {"disp":"clean-candidate","conf":"high","why":"evidence → «докази; свідчення»; definition (facts or observations presented to support a claim) is accurate; noun POS matches."},
 "SB-0971": {"disp":"clean-candidate","conf":"high","why":"referendum → «референдум»; definition (a direct popular vote on a proposed law or constitutional amendment) is accurate; noun POS matches."},
 "SB-0678": {"disp":"clean-candidate","conf":"high","why":"kidney → «нирка»; definition (an organ that filters blood to form urine) is accurate; noun POS matches."},
 "SB-1227": {"disp":"clean-candidate","conf":"high","why":"transit → «транзит»; definition (the transport of people or goods, esp. in a public transport system) is accurate; noun POS matches."},
 "SB-1200": {"disp":"clean-candidate","conf":"medium","why":"thereby → «тим самим»; definition (by that; thus or as a consequence of that) conveys the sense; adverb POS matches."},
 "SB-1715": {"disp":"clean-candidate","conf":"high","why":"theme → «тема»; definition (the subject, esp. of conversation or an artistic work) is accurate; noun POS matches."},
 "SB-1282": {"disp":"clean-candidate","conf":"high","why":"virtue → «чеснота»; definition (conformity to moral principles; good moral conduct) is accurate; noun POS matches."},
 "SB-1500": {"disp":"clean-candidate","conf":"high","why":"dimensions → «розміри»; definition (measurable characteristics of size; also aspects of a complex issue) is accurate; plural noun POS matches."},
 "SB-1458": {"disp":"clean-candidate","conf":"high","why":"location → «розташування»; definition (a specific point or place in physical space) is accurate; noun POS matches."},
 "SB-1697": {"disp":"clean-candidate","conf":"high","why":"implicit → «неявний»; definition (implied indirectly, without direct expression) is accurate; adjective POS matches."},
 "SB-0045": {"disp":"clean-candidate","conf":"high","why":"albeit → «хоча»; definition (a conjunction meaning 'although' or 'even though') is accurate; conjunction POS matches."},
 "SB-0733": {"disp":"clean-candidate","conf":"medium","why":"mandatory → «обов'язковий»; definition (compulsory; required or ordered by authority) is accurate though it restates the gloss; adjective POS matches."},
 "SB-0938": {"disp":"clean-candidate","conf":"high","why":"protocol → «протокол»; definition (a set of formal rules describing how to transmit or exchange data, esp. over a network) is accurate; noun POS matches."},
 "SB-0839": {"disp":"clean-candidate","conf":"high","why":"overly → «надмірно»; definition (to an excessive degree) is accurate; adverb POS matches."},
 "SB-0650": {"disp":"clean-candidate","conf":"high","why":"intensive → «інтенсивний»; definition (carried out with intensity or to a considerable degree; thorough) is accurate; adjective POS matches."},
 "SB-0622": {"disp":"clean-candidate","conf":"medium","why":"influential → «впливовий»; definition (possessing or exercising influence) conveys the sense despite noun-framing; adjective POS matches."},
 "SB-0433": {"disp":"clean-candidate","conf":"high","why":"embarrassment → «збентеження»; definition (discomfort from shyness or awareness of breaching a social rule; humiliation) is accurate; noun POS matches."},
 "SB-0310": {"disp":"clean-candidate","conf":"high","why":"critique → «критика»; definition (an essay that criticises or reviews another work) is accurate; noun POS matches."},
 "SB-0905": {"disp":"clean-candidate","conf":"high","why":"presidential → «президентський»; definition (relating to a president or the presidency) is accurate; adjective POS matches."},
 "SB-0187": {"disp":"clean-candidate","conf":"high","why":"civic → «громадянський»; definition (relating to a citizen or to good citizenship and its rights and duties) is accurate; adjective POS matches."},
 "SB-0010": {"disp":"clean-candidate","conf":"high","why":"acceptance → «прийняття»; definition (the act of accepting; receiving something offered with approval; a favourable reception) is accurate; noun POS matches."},
 "SB-0153": {"disp":"clean-candidate","conf":"high","why":"buffer → «буфер»; definition (a portion of memory allocated for temporary data storage, often before sending to a device) is accurate; noun POS matches."},
 "SB-0823": {"disp":"clean-candidate","conf":"high","why":"offspring → «потомство»; definition (a person's daughter or son; a person's child) is accurate; noun POS matches."},
 "SB-0178": {"disp":"clean-candidate","conf":"high","why":"chaos → «хаос»; definition (any state of disorder; a confused or amorphous mixture) is accurate; noun POS matches."},
 "SB-1289": {"disp":"clean-candidate","conf":"medium","why":"warfare → «війна»; definition (the conduct of war or armed conflict against an enemy) conveys the sense; «ведення війни/воєнні дії» would be more precise but the def clarifies it."},
 "SB-1325": {"disp":"clean-candidate","conf":"high","why":"consistent → «послідовний; узгоджений; сталий»; definition (of a regular, reliable character) is accurate; adjective POS matches."},
 "SB-0547": {"disp":"clean-candidate","conf":"high","why":"governance → «управління»; definition (the process or power of governing; government or administration) is accurate; noun POS matches."},
 "SB-0407": {"disp":"clean-candidate","conf":"high","why":"donor → «донор»; definition (one who makes a donation) is accurate; noun POS matches."},
 "SB-1403": {"disp":"clean-candidate","conf":"high","why":"journal → «журнал»; definition (a periodical with academic or professional articles; also a personal diary) is accurate; noun POS matches."},
 "SB-1760": {"disp":"clean-candidate","conf":"medium","why":"suspended → «призупинено»; definition (made to stop for a time; interrupted or delayed) conveys the sense despite the awkward «Змусив»; consistent gloss."},
 "SB-1664": {"disp":"clean-candidate","conf":"high","why":"publication → «публікація»; definition (the act of issuing a printed or other edition) is accurate; noun POS matches."},
 "SB-1768": {"disp":"clean-candidate","conf":"medium","why":"conceived → «задуманий»; definition (formed in the mind) conveys the sense despite terse phrasing; consistent gloss."},
 "SB-0270": {"disp":"clean-candidate","conf":"high","why":"continually → «постійно»; definition (in a regular or repeated sequence; very often) is accurate; adverb POS matches."},
 "SB-1065": {"disp":"clean-candidate","conf":"medium","why":"sheer → «чистий»; definition (utter; complete; pure) conveys the intensifier sense; adjective POS matches."},
 "SB-1510": {"disp":"clean-candidate","conf":"medium","why":"imposed → «нав'язаний»; definition (set out authoritatively as binding) conveys the sense despite terse phrasing; consistent gloss."},
 "SB-1391": {"disp":"clean-candidate","conf":"high","why":"cultural → «культурний»; definition (relating to culture) is accurate; adjective POS matches."},
 "SB-0568": {"disp":"clean-candidate","conf":"high","why":"handy → «зручний»; definition (easy to use, useful) is accurate; adjective POS matches."},
 "SB-1129": {"disp":"clean-candidate","conf":"medium","why":"strategic → «стратегічний»; definition (relating to strategy) is accurate; adjective POS matches."},
 "SB-0747": {"disp":"clean-candidate","conf":"high","why":"meaningful → «значущий»; definition (having meaning; significant) is accurate; adjective POS matches."},
 "SB-0837": {"disp":"clean-candidate","conf":"high","why":"outsider → «сторонній»; definition (one who is not part of a community or organisation) is accurate; noun POS matches."},
 "SB-0299": {"disp":"clean-candidate","conf":"high","why":"counter → «заперечувати; протиставляти аргумент»; definition (to respond to a claim with an opposing argument or evidence) is accurate; the disambiguation matches; verb POS correct."},
 "SB-1746": {"disp":"clean-candidate","conf":"high","why":"military → «військовий»; definition (relating to the armed forces such as army, marines, navy and air force) is accurate; adjective POS matches."},
 "SB-0639": {"disp":"clean-candidate","conf":"high","why":"insufficient → «недостатній»; definition (not enough; of a kind or amount that does not meet requirements) is accurate; adjective POS matches."},
 "SB-0910": {"disp":"clean-candidate","conf":"high","why":"prevalence → «поширеність»; definition (the quality or condition of being prevalent; wide extension or spread) is accurate; noun POS matches."},
 "SB-1078": {"disp":"clean-candidate","conf":"high","why":"slam → «грюкнути»; definition (to shut with sudden force, producing an impact and noise) is accurate; verb POS matches."},
 "SB-1219": {"disp":"clean-candidate","conf":"medium","why":"toxic → «токсичний»; definition (strongly negative or harmful) covers the figurative sense; the literal 'poisonous' sense is also carried by «токсичний»; adjective POS matches."},
 "SB-1327": {"disp":"clean-candidate","conf":"high","why":"contract → «договір; укладати контракт; скорочуватися»; definition (an agreement between parties to perform work, usually written) is accurate; the family covers noun+verb senses."},
 "SB-1018": {"disp":"clean-candidate","conf":"high","why":"reverse → «змінювати на протилежне; рухатися назад»; definition (to change direction, order or outcome to the opposite; also to move backward) is accurate; verb POS matches."},
 "SB-0185": {"disp":"clean-candidate","conf":"high","why":"circulation → «обіг»; definition (the act of passing from place to place or person to person; free diffusion) is accurate; noun POS matches."},
 "SB-0853": {"disp":"clean-candidate","conf":"high","why":"pastor → «пастор»; definition (someone with spiritual authority over a group of people) is accurate; noun POS matches."},
 "SB-1552": {"disp":"clean-candidate","conf":"medium","why":"entities → «сутності»; definition (something existing as a distinct unit, often for organisations without physical form) matches the entity family; plural noun POS."},
 "SB-1203": {"disp":"clean-candidate","conf":"high","why":"thread → «нитка»; definition (a cord formed by spinning or twisting textile fibres, used in needlework) is accurate; noun POS matches."},
 "SB-0375": {"disp":"clean-candidate","conf":"high","why":"diminish → «зменшувати»; definition (to make smaller) is accurate; verb POS matches."},
 "SB-0023": {"disp":"clean-candidate","conf":"high","why":"acre → «акр»; definition (an English unit of land area, standardised as 4840 sq yards / 4046.86 sq metres) is accurate; noun POS matches."},
 "SB-0077": {"disp":"clean-candidate","conf":"high","why":"architectural → «архітектурний»; definition (relating to architecture) is accurate; adjective POS matches."},
 "SB-1339": {"disp":"clean-candidate","conf":"high","why":"factors → «чинники; фактори»; definition (one of the elements, circumstances or influences contributing to a result) is accurate; plural noun POS matches."},
 "SB-1774": {"disp":"clean-candidate","conf":"high","why":"intrinsic → «внутрішній»; definition (innate, inherent, inseparable from the thing itself, essential) is accurate; adjective POS matches."},
 "SB-1112": {"disp":"clean-candidate","conf":"high","why":"squeeze → «стискати»; definition (to exert pressure simultaneously from two or more sides) is accurate; verb POS matches."},
 "SB-1245": {"disp":"clean-candidate","conf":"high","why":"turnover → «оборот»; definition (the amount of money taken as sales in a given period) is accurate; noun POS matches."},
 "SB-1599": {"disp":"clean-candidate","conf":"high","why":"enhanced → «посилений»; definition (in a version or form improved or better than another standard form) is accurate; consistent gloss."},
 "SB-1469": {"disp":"clean-candidate","conf":"high","why":"registered → «зареєстрований»; definition (having entered one's name on an official list or a register) is accurate; consistent gloss."},
 "SB-1667": {"disp":"clean-candidate","conf":"high","why":"somewhat → «дещо»; definition (to a limited extent or degree; not completely) is accurate; adverb POS matches."},
 "SB-0126": {"disp":"clean-candidate","conf":"high","why":"beneficiary → «бенефіціар»; definition (one who benefits or receives an advantage) is accurate; noun POS matches."},
 "SB-0165": {"disp":"clean-candidate","conf":"high","why":"cargo → «вантаж»; definition (freight carried by a ship, aircraft or vehicle) is accurate; noun POS matches."},
 "SB-1651": {"disp":"clean-candidate","conf":"high","why":"guarantee → «гарантія»; definition (anything that ensures a particular outcome) is accurate; noun POS matches."},
}
